[package]
name = "app"
version = "0.1.0"
authors = ["fig developers"]
edition = "2021"
rust-version = "1.57"
description = "A Tauri App"
homepage = "https://fig.io"
publish = false
default-run = "app"

[build-dependencies]
tauri-build = { version = "1.0.0-rc.4", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0-rc.4", features = ["api-all"] }
prost = "0.9.0"
fig_proto = { path = "../../rust-lib/fig_proto" }
windows = { version = "0.34.0", features = ["Win32_System_Com","Win32_UI_Accessibility","Win32_UI_WindowsAndMessaging","Win32_Foundation","Win32_System_Ole","Win32_Networking_WinSock","Win32_Storage_FileSystem"] }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
