[package]
name = "fig_api_client"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
fig_request = { path = "../fig_request" }
fig_settings = { path = "../fig_settings" }
fig_util = { path = "../fig_util" }
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.85"
time = { version = "0.3.14", features = ["serde"] }
url = { version = "2.3.1", features = ["serde"] }
