[package]
name = "fig_api_client"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
fig_request = { path = "../fig_request" }
fig_settings = { path = "../fig_settings" }
fig_util = { path = "../fig_util" }
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.86"
time = { version = "0.3.14", features = ["serde"] }
url = { version = "2.3.1", features = ["serde"] }
