[package]
name = "fig-proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
bytes = "1.1.0"
prost = "0.9.0"

[build-dependencies]
prost-build = "0.9.0"
