// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub(crate) fn de_user_input_message_context<'a, I>(
    tokens: &mut ::std::iter::Peekable<I>,
    _value: &'a [u8],
    depth: u32,
) -> ::std::result::Result<
    Option<crate::model::user_input_message_context_internal::Builder>,
    ::aws_smithy_json::deserialize::error::DeserializeError,
>
where
    I: Iterator<
        Item = Result<
            ::aws_smithy_json::deserialize::Token<'a>,
            ::aws_smithy_json::deserialize::error::DeserializeError,
        >,
    >,
{
    if depth >= 128u32 {
        return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(
            "maximum nesting depth exceeded",
        ));
    }
    match tokens.next().transpose()? {
        Some(::aws_smithy_json::deserialize::Token::ValueNull { .. }) => Ok(None),
        Some(::aws_smithy_json::deserialize::Token::StartObject { .. }) => {
            #[allow(unused_mut)]
            let mut builder = crate::model::user_input_message_context_internal::Builder::default();
            loop {
                match tokens.next().transpose()? {
                    Some(::aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
                    Some(::aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => {
                        match key.to_unescaped()?.as_ref() {
                            "editorState" => {
                                builder = builder.set_editor_state(
                                    crate::protocol_serde::shape_editor_state::de_editor_state(
                                        tokens,
                                        _value,
                                        depth + 1,
                                    )?,
                                );
                            },
                            "envState" => {
                                builder = builder.set_env_state(crate::protocol_serde::shape_env_state::de_env_state(
                                    tokens,
                                    _value,
                                    depth + 1,
                                )?);
                            },
                            "additionalContext" => {
                                builder = builder.set_additional_context(
                                    crate::protocol_serde::shape_additional_content_list::de_additional_content_list(
                                        tokens,
                                        _value,
                                        depth + 1,
                                    )?,
                                );
                            },
                            "toolResults" => {
                                builder = builder.set_tool_results(
                                    crate::protocol_serde::shape_tool_results::de_tool_results(
                                        tokens,
                                        _value,
                                        depth + 1,
                                    )?,
                                );
                            },
                            "tools" => {
                                builder = builder.set_tools(crate::protocol_serde::shape_tools::de_tools(
                                    tokens,
                                    _value,
                                    depth + 1,
                                )?);
                            },
                            _ => ::aws_smithy_json::deserialize::token::skip_value(tokens)?,
                        }
                    },
                    other => {
                        return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(
                            format!("expected object key or end object, found: {other:?}"),
                        ));
                    },
                }
            }
            Ok(Some(builder))
        },
        _ => Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(
            "expected start object or null",
        )),
    }
}
