// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(clippy::unnecessary_wraps)]
pub async fn de_generate_assistant_response_http_request<B>(
    #[allow(unused_variables)] request: ::http_1x::Request<B>,
) -> std::result::Result<
    crate::input::GenerateAssistantResponseInput,
    ::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection,
>
where
    B: ::aws_smithy_http_server::body::HttpBody + Send,
    B::Data: Send,
    ::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection:
        From<<B as ::aws_smithy_http_server::body::HttpBody>::Error>,
{
    Ok({
        #[allow(unused_mut)]
        let mut input = crate::input::generate_assistant_response_input_internal::Builder::default();
        #[allow(unused_variables)]
        let ::aws_smithy_runtime_api::http::RequestParts { uri, headers, body, .. } =
            ::aws_smithy_runtime_api::http::Request::try_from(request)?.into_parts();
        let bytes = {
            use ::http_body_util::BodyExt;
            body.collect().await?.to_bytes()
        };
        if !bytes.is_empty() {
            ::aws_smithy_http_server::protocol::content_type_header_classifier_smithy(
                &headers,
                Some("application/x-amz-json-1.0"),
            )?;
            input = crate::protocol_serde::shape_generate_assistant_response::de_generate_assistant_response(
                bytes.as_ref(),
                input,
            )?;
        }
        input.build()?
    })
}

#[allow(clippy::unnecessary_wraps)]
pub fn ser_generate_assistant_response_http_response(
    #[allow(unused_variables)] output: crate::output::GenerateAssistantResponseOutput,
) -> std::result::Result<
    ::aws_smithy_http_server::response::Response,
    ::aws_smithy_http_server::protocol::aws_json::rejection::ResponseRejection,
> {
    Ok({
        #[allow(unused_mut)]
        let mut builder = ::http_1x::Response::builder();
        builder = ::aws_smithy_http::header::set_response_header_if_absent(
            builder,
            ::http_1x::header::CONTENT_TYPE,
            "application/x-amz-json-1.0",
        );
        let http_status: u16 = 200;
        builder = builder.status(http_status);
        let body = ::aws_smithy_http_server::body::boxed(::http_body_util::StreamBody::new({
            let error_marshaller = crate::event_stream_serde::ChatResponseStreamErrorMarshaller::new();
            let marshaller = crate::event_stream_serde::ChatResponseStreamMarshaller::new();
            let signer = ::aws_smithy_eventstream::frame::NoOpSigner {};
            output
                .generate_assistant_response_response
                .into_body_stream(marshaller, error_marshaller, signer)
        }));
        builder.body(body)?
    })
}

#[allow(clippy::unnecessary_wraps)]
pub fn ser_generate_assistant_response_http_error(
    error: &crate::error::GenerateAssistantResponseError,
) -> std::result::Result<
    ::aws_smithy_http_server::response::Response,
    ::aws_smithy_http_server::protocol::aws_json::rejection::ResponseRejection,
> {
    Ok({
        match error {
            crate::error::GenerateAssistantResponseError::AccessDeniedException(output) => {
                let payload =
                    crate::protocol_serde::shape_access_denied_exception::ser_access_denied_exception_error(output)?;
                #[allow(unused_mut)]
                let mut builder = ::http_1x::Response::builder();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_TYPE,
                    "application/x-amz-json-1.0",
                );
                let content_length = payload.len();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_LENGTH,
                    content_length,
                );
                builder
                    .status(403)
                    .body(::aws_smithy_http_server::body::to_boxed(payload))?
            },
            crate::error::GenerateAssistantResponseError::InternalServerException(output) => {
                let payload =
                    crate::protocol_serde::shape_internal_server_exception::ser_internal_server_exception_error(
                        output,
                    )?;
                #[allow(unused_mut)]
                let mut builder = ::http_1x::Response::builder();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_TYPE,
                    "application/x-amz-json-1.0",
                );
                let content_length = payload.len();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_LENGTH,
                    content_length,
                );
                builder
                    .status(500)
                    .body(::aws_smithy_http_server::body::to_boxed(payload))?
            },
            crate::error::GenerateAssistantResponseError::ServiceQuotaExceededException(output) => {
                let payload = crate::protocol_serde::shape_service_quota_exceeded_exception::ser_service_quota_exceeded_exception_error(output)?;
                #[allow(unused_mut)]
                let mut builder = ::http_1x::Response::builder();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_TYPE,
                    "application/x-amz-json-1.0",
                );
                let content_length = payload.len();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_LENGTH,
                    content_length,
                );
                builder
                    .status(402)
                    .body(::aws_smithy_http_server::body::to_boxed(payload))?
            },
            crate::error::GenerateAssistantResponseError::ServiceUnavailableException(output) => {
                let payload = crate::protocol_serde::shape_service_unavailable_exception::ser_service_unavailable_exception_error(output)?;
                #[allow(unused_mut)]
                let mut builder = ::http_1x::Response::builder();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_TYPE,
                    "application/x-amz-json-1.0",
                );
                let content_length = payload.len();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_LENGTH,
                    content_length,
                );
                builder
                    .status(503)
                    .body(::aws_smithy_http_server::body::to_boxed(payload))?
            },
            crate::error::GenerateAssistantResponseError::ThrottlingException(output) => {
                let payload =
                    crate::protocol_serde::shape_throttling_exception::ser_throttling_exception_error(output)?;
                #[allow(unused_mut)]
                let mut builder = ::http_1x::Response::builder();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_TYPE,
                    "application/x-amz-json-1.0",
                );
                let content_length = payload.len();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_LENGTH,
                    content_length,
                );
                builder
                    .status(429)
                    .body(::aws_smithy_http_server::body::to_boxed(payload))?
            },
            crate::error::GenerateAssistantResponseError::ValidationError(output) => {
                let payload = crate::protocol_serde::shape_validation_error::ser_validation_error_error(output)?;
                #[allow(unused_mut)]
                let mut builder = ::http_1x::Response::builder();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_TYPE,
                    "application/x-amz-json-1.0",
                );
                let content_length = payload.len();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_LENGTH,
                    content_length,
                );
                builder
                    .status(400)
                    .body(::aws_smithy_http_server::body::to_boxed(payload))?
            },
            crate::error::GenerateAssistantResponseError::ValidationException(output) => {
                let payload =
                    crate::protocol_serde::shape_validation_exception::ser_validation_exception_error(output)?;
                #[allow(unused_mut)]
                let mut builder = ::http_1x::Response::builder();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_TYPE,
                    "application/x-amz-json-1.0",
                );
                let content_length = payload.len();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_LENGTH,
                    content_length,
                );
                builder
                    .status(400)
                    .body(::aws_smithy_http_server::body::to_boxed(payload))?
            },
        }
    })
}

pub(crate) fn de_generate_assistant_response(
    _value: &[u8],
    mut builder: crate::input::generate_assistant_response_input_internal::Builder,
) -> ::std::result::Result<
    crate::input::generate_assistant_response_input_internal::Builder,
    ::aws_smithy_json::deserialize::error::DeserializeError,
> {
    let mut tokens_owned =
        ::aws_smithy_json::deserialize::json_token_iter(crate::protocol_serde::or_empty_doc(_value)).peekable();
    let tokens = &mut tokens_owned;
    #[allow(unused_variables)]
    let depth = 0u32;
    ::aws_smithy_json::deserialize::token::expect_start_object(tokens.next())?;
    loop {
        match tokens.next().transpose()? {
            Some(::aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
            Some(::aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => match key.to_unescaped()?.as_ref() {
                "conversationState" => {
                    builder = builder.set_conversation_state(
                        crate::protocol_serde::shape_conversation_state::de_conversation_state(
                            tokens,
                            _value,
                            depth + 1,
                        )?,
                    );
                },
                "profileArn" => {
                    builder = builder.set_profile_arn(
                        ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?
                            .map(|s| s.to_unescaped().map(|u| u.into_owned()))
                            .transpose()?,
                    );
                },
                "agentMode" => {
                    builder = builder.set_agent_mode(
                        ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?
                            .map(|s| s.to_unescaped().map(|u| u.into_owned()))
                            .transpose()?,
                    );
                },
                "additionalModelRequestFields" => {
                    builder = builder.set_additional_model_request_fields(Some(
                        ::aws_smithy_json::deserialize::token::expect_document(tokens)?,
                    ));
                },
                "systemPrompt" => {
                    builder = builder.set_system_prompt(
                        ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?
                            .map(|s| s.to_unescaped().map(|u| u.into_owned()))
                            .transpose()?,
                    );
                },
                _ => ::aws_smithy_json::deserialize::token::skip_value(tokens)?,
            },
            other => {
                return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(
                    format!("expected object key or end object, found: {other:?}"),
                ));
            },
        }
    }
    if tokens.next().is_some() {
        return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(
            "found more JSON tokens after completing parsing",
        ));
    }
    Ok(builder)
}
