// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_metadata_event(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::model::MetadataEvent,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.token_usage {
        #[allow(unused_mut)]
        let mut object_2 = object.key("tokenUsage").start_object();
        crate::protocol_serde::shape_token_usage::ser_token_usage(&mut object_2, var_1)?;
        object_2.finish();
    }
    if let Some(var_3) = &input.stop_reason {
        object.key("stopReason").string(var_3.as_str());
    }
    if let Some(var_4) = &input.stop_details {
        #[allow(unused_mut)]
        let mut object_5 = object.key("stopDetails").start_object();
        crate::protocol_serde::shape_stop_details::ser_stop_details(&mut object_5, var_4)?;
        object_5.finish();
    }
    Ok(())
}
