// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_metering_event(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::model::MeteringEvent,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.usage {
        object.key("usage").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::Float((*var_1).into()),
        );
    }
    if let Some(var_2) = &input.unit {
        object.key("unit").string(var_2.as_str());
    }
    if let Some(var_3) = &input.unit_plural {
        object.key("unitPlural").string(var_3.as_str());
    }
    Ok(())
}
