// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_document_citation_event(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::model::DocumentCitationEvent,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.source {
        object.key("source").string(var_1.as_str());
    }
    if let Some(var_2) = &input.title {
        object.key("title").string(var_2.as_str());
    }
    if let Some(var_3) = &input.location {
        #[allow(unused_mut)]
        let mut object_4 = object.key("location").start_object();
        crate::protocol_serde::shape_document_citation_location::ser_document_citation_location(&mut object_4, var_3)?;
        object_4.finish();
    }
    if let Some(var_5) = &input.source_content {
        let mut array_6 = object.key("sourceContent").start_array();
        for item_7 in var_5 {
            {
                #[allow(unused_mut)]
                let mut object_8 = array_6.value().start_object();
                crate::protocol_serde::shape_document_citation_source_content::ser_document_citation_source_content(
                    &mut object_8,
                    item_7,
                )?;
                object_8.finish();
            }
        }
        array_6.finish();
    }
    Ok(())
}
