// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_tool_use_event(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::model::ToolUseEvent,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.tool_use_id {
        object.key("toolUseId").string(var_1.as_str());
    }
    if let Some(var_2) = &input.name {
        object.key("name").string(var_2.as_str());
    }
    if let Some(var_3) = &input.input {
        object.key("input").string(var_3.as_str());
    }
    if let Some(var_4) = &input.stop {
        object.key("stop").boolean(*var_4);
    }
    Ok(())
}
