// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_document_citation_source_content(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::model::DocumentCitationSourceContent,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.text {
        object.key("text").string(var_1.as_str());
    }
    Ok(())
}
