// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_document_citation_web_location(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::model::DocumentCitationWebLocation,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.url {
        object.key("url").string(var_1.as_str());
    }
    if let Some(var_2) = &input.domain {
        object.key("domain").string(var_2.as_str());
    }
    Ok(())
}
