// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_stop_details(
    object_5: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::model::StopDetails,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    match input {
        crate::model::StopDetails::Refusal(inner) => {
            #[allow(unused_mut)]
            let mut object_1 = object_5.key("refusal").start_object();
            crate::protocol_serde::shape_refusal_details::ser_refusal_details(&mut object_1, inner)?;
            object_1.finish();
        },
    }
    Ok(())
}
