// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_throttling_exception_error(
    value: &crate::error::ThrottlingException,
) -> ::std::result::Result<String, ::aws_smithy_types::error::operation::SerializationError> {
    let mut out = ::std::string::String::new();
    let mut object = ::aws_smithy_json::serialize::JsonObjectWriter::new(&mut out);
    crate::protocol_serde::shape_throttling_exception::ser_throttling_exception(&mut object, value)?;
    object
        .key("__type")
        .string("com.amazon.kiro.runtimeservice#ThrottlingException");
    object.finish();
    Ok(out)
}

pub fn ser_throttling_exception(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::error::ThrottlingException,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.message {
        object.key("message").string(var_1.as_str());
    }
    if let Some(var_2) = &input.reason {
        object.key("reason").string(var_2.as_str());
    }
    if let Some(var_3) = &input.retry_after_milliseconds {
        object.key("retryAfterMilliseconds").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::NegInt((*var_3).into()),
        );
    }
    Ok(())
}
