// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_reasoning_content_event(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::model::ReasoningContentEvent,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.text {
        object.key("text").string(var_1.as_str());
    }
    if let Some(var_2) = &input.redacted_content {
        object
            .key("redactedContent")
            .string_unchecked(&::aws_smithy_types::base64::encode(var_2));
    }
    if let Some(var_3) = &input.signature {
        object.key("signature").string(var_3.as_str());
    }
    Ok(())
}
