// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_refusal_details(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::model::RefusalDetails,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.category {
        object.key("category").string(var_1.as_str());
    }
    if let Some(var_2) = &input.explanation {
        object.key("explanation").string(var_2.as_str());
    }
    if let Some(var_3) = &input.recommended_model {
        object.key("recommendedModel").string(var_3.as_str());
    }
    Ok(())
}
