[package]
name = "fig_update"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
once_cell = "1.13.1"
reqwest = { version = "0.11.11", features = ["json"] }
semver = "1.0.13"
serde = { version = "1.0.143", features = ["derive"] }
fig_util = { path = "../fig_util" }
tracing = "0.1.36"
tokio = "1.20.1"
cfg-if = "1.0.0"
thiserror = "1.0.32"
