[options]
library = "IBus"
version = "1.0"
target_path = "."
min_cfg_version = "1.5"
work_mode = "sys"
girs_directories = ["../gir-files"]

external_libraries = [
    "Gio",
    "GLib",
    "GObject",
]
