version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "grant0417"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "grant0417"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "grant0417"

