[package]
name = "fig-telemetry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.55"
fig-auth = { path = "../fig-auth" }
fig-settings = { path = "../fig-settings" }
serde = "1.0.136"
reqwest = { version = "0.11.9", features = ["json"] }
