[package]
name = "fig_release"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
color-eyre = "0.6.2"
dialoguer = { version = "0.10.2", features = ["fuzzy-select", "editor"] }
eyre = "0.6.8"
fig_request = { path = "../../lib/fig_request" }
fig_settings = { path = "../../lib/fig_settings" }
fig_util = { path = "../../lib/fig_util" }
semver = "1.0.16"
serde = { version = "1.0.152", features = ["derive"] }
strum = "0.24.1"
time = { version = "0.3.17", features = ["macros", "formatting"] }
tokio = { version = "1", features = ["full"] }
toml_edit = "0.17.1"
