[package]
name = "fig_release"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
dialoguer = { version = "0.10.2", features = ["fuzzy-select", "editor"] }
eyre = "0.6.8"
fig_request = { path = "../../rust-lib/fig_request" }
fig_settings = { path = "../../rust-lib/fig_settings" }
fig_util = { path = "../../rust-lib/fig_util" }
once_cell = "1.15.0"
semver = "1.0.14"
serde = { version = "1.0.145", features = ["derive"] }
serde_yaml = "0.9.13"
time = { version = "0.3.14", features = ["macros", "formatting"] }
tokio = { version = "1", features = ["full"] }
toml_edit = "0.15.0"
