excluded:
  - fig/Local IPC/local.pb.swift
  - fig/iTerm/iterm.pb.swift
  - swift-api-bindings/Sources/FigAPIBindings/*.pb.swift

 # To see which rules are most prominent in the repo:
 # swiftlint lint --enable-all-rules 2>/dev/null | sed -r 's/.*\((.*)\).*/\1/' | sort | uniq -c | sort
disabled_rules:
  - cyclomatic_complexity
  - function_body_length
  - file_length

indentation: 2

type_name:
  min_length: 4
  allowed_symbols: ["_"]
