[workspace]
members = [
    "fig_cli",
    "fig_ibus_engine",
    "fig_desktop",
    "figterm",
    "rust-lib/*"
]

default-members = [
    "fig_cli",
    "fig_desktop",
    "figterm",
    "rust-lib/*",
]

[profile.release]
lto = true
codegen-units = 1

