[workspace]
resolver = "2"
members = [
    "fig_cli",
    "fig_desktop",
    "figterm",
    "rust-lib/*",
]
exclude = [
    "fig_ibus_engine",
]

[profile.release]
debug = 1
incremental = true
lto = "off"

[profile.dev.package.backtrace]
opt-level = 3

