[workspace]
resolver = "2"
members = [
    "fig_cli",
    "fig_desktop",
    "fig_installer",
    "figterm",
    "tests/stress/stress_server",
    "tests/stress/stress_client",
    "rust-lib/*",
    "rust-lib/macos_accessibility_position/accessibility-master/*",
    "rust-lib/macos_accessibility_position/appkit-nsworkspace-bindings",
]
exclude = [
    "fig_ibus_engine",
]

[profile.release]
debug = 1
incremental = true
lto = "off"

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3

[profile.dev.package.backtrace]
opt-level = 3

[patch.crates-io]
tokio = { git = "https://github.com/sullivan-sean/tokio" }
mio = { git = "https://github.com/sullivan-sean/mio" }
