[workspace]
members = [
    "figcli",
    "figterm",
    "rust-lib/alacritty_terminal",
    "rust-lib/fig-auth",
    "rust-lib/fig-color",
    "rust-lib/fig-directories",
    "rust-lib/fig-ipc",
    "rust-lib/fig-proto",
    "rust-lib/fig-settings",
    "rust-lib/fig-telemetry",
    "rust-lib/ibus",
    "rust-lib/ibus/ibus-sys",
    "rust-lib/linux-test",
    "fig-ibus-engine",
    "daemon",
    "linux-app/src-tauri",
    "winfig/src-tauri",
    "fig-tauri/src-tauri",
    "rust-lib/fig-log",
]

[profile.release]
debug = true
