[workspace]
members = [
    "fig_cli",
    #"fig_ibus_engine",
    "fig_tauri/src-tauri",
    "figterm",
    #"rust-lib/*",
    #"rust-lib/ibus/ibus-sys",
]

default-members = [
    "fig_cli",
    "fig_tauri/src-tauri",
    "figterm",
    "rust-lib/alacritty_terminal",
    "rust-lib/fig_auth",
    "rust-lib/fig_color",
    "rust-lib/fig_directories",
    "rust-lib/fig_ipc",
    "rust-lib/fig_log",
    "rust-lib/fig_proto",
    "rust-lib/fig_settings",
    "rust-lib/fig_telemetry",
    "rust-lib/fig_util",
    "rust-lib/system_socket",
]
