[build]
pre-build = ["apt-get update && apt-get --assume-yes install unzip zsh"]

[build.env]
passthrough = [
    "AMAZON_Q_BUILD_TARGET_TRIPLE",
    "AMAZON_Q_BUILD_VARIANT",
    "AMAZON_Q_BUILD_HASH",
    "AMAZON_Q_BUILD_DATETIME",
    "AMAZON_Q_BUILD_SKIP_FISH_TESTS",
    "AMAZON_Q_BUILD_SKIP_SHELLCHECK_TESTS",
    "Q_TELEMETRY_CLIENT_ID",
]
