[build]
pre-build = ["apt-get update && apt-get --assume-yes install unzip zsh libclang-dev libssl-dev pkg-config"]

[build.env]
passthrough = [
    "KIRO_VERSION",
    "AMAZON_Q_BUILD_TARGET_TRIPLE",
    "AMAZON_Q_BUILD_VARIANT",
    "AMAZON_Q_BUILD_HASH",
    "AMAZON_Q_BUILD_DATETIME",
    "Q_TELEMETRY_CLIENT_ID",
    "BUN_EXECUTABLE_PATH",
    "BUN_EXECUTABLE_PATH_X86_64",
    "BUN_EXECUTABLE_PATH_AARCH64",
    "BUN_RUNTIME_SHA256",
    "BUN_RUNTIME_SHA256_X86_64",
    "BUN_RUNTIME_SHA256_AARCH64",
    "TUI_JS_PATH",
    "TUI_JS_SHA256",
    "DISABLE_V2_BUN",
    "NODE_EXECUTABLE_PATH",
    "NODE_EXECUTABLE_PATH_X86_64",
    "NODE_EXECUTABLE_PATH_AARCH64",
    "NODE_RUNTIME_SHA256",
    "NODE_RUNTIME_SHA256_X86_64",
    "NODE_RUNTIME_SHA256_AARCH64",
    "KAS_BUNDLE_PATH",
    "KAS_BUNDLE_SHA256",
]
