targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "aarch64-apple-darwin" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
ignore = [ "RUSTSEC-2020-0071" ]
severity-threshold = "medium"

[licenses]
default = "allow"
copyleft = "deny"
private = { ignore = true }
allow = [
  "MPL-2.0"
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [ { path = "LICENSE", hash = 0xbd0eed23 } ]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"

[[bans.deny]]
name = "openssl"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = [
  "https://github.com/sullivan-sean/tokio",
  "https://github.com/sullivan-sean/mio",
  "https://github.com/grant0417/skim"
]
