[files]
extend-exclude = [
  "tests",
  "lib/amzn-codewhisperer-client",
  "lib/amzn-codewhisperer-streaming-client",
  "lib/amzn-consolas-client",
  "lib/amzn-qdeveloper-streaming-client",
  "lib/aws-toolkit-telemetry-definitions/def.json",
  "lib/zbus",
  "lib/zbus_names",
  "packages/fuzzysort",
  "apps/dashboard/public/license/NOTICE.txt",
]

[default]
extend-ignore-re = [
    # Ignore lines with trailing `spellchecker:disable-line`
    "(?Rm)^.*(#|//)\\s*spellchecker:disable-line$"
]

[default.extend-words]
# These are correct in the context of Fig, but aren't normal words
iterm = "iterm"
preedit = "preedit"
xmodifiers = "xmodifiers"
zvariant = "zvariant"
ser = "ser"
sur = "sur"
ratatui = "ratatui"

[type.rust.extend-identifiers]
# typos really wanted to correct 2ND -> 2AND
FROM_LEFT_2ND_BUTTON_PRESSED = "FROM_LEFT_2ND_BUTTON_PRESSED"
