[files]
extend-exclude = [
  "__tests__",
  "lib/amzn-codewhisperer-client",
  "lib/amzn-codewhisperer-streaming-client",
  "lib/amzn-consolas-client",
  "lib/aws-toolkit-telemetry-definitions/def.json",
  "packages/fuzzysort",
  "apps/dashboard/public/license/NOTICE.txt",
]

[default.extend-words]
# These are correct in the context of Fig, but aren't normal words
iterm = "iterm"
preedit = "preedit"
xmodifiers = "xmodifiers"
zvariant = "zvariant"
ser = "ser"
sur = "sur"

[type.rust.extend-identifiers]
# typos really wanted to correct 2ND -> 2AND
FROM_LEFT_2ND_BUTTON_PRESSED = "FROM_LEFT_2ND_BUTTON_PRESSED"
