// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_external_identity_source(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::types::ExternalIdentitySource,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    {
        object.key("issuerUrl").string(input.issuer_url.as_str());
    }
    {
        object.key("clientId").string(input.client_id.as_str());
    }
    if let Some(var_1) = &input.subscription_start_type {
        object.key("subscriptionStartType").string(var_1.as_str());
    }
    if let Some(var_2) = &input.jit_subscription_role_arn {
        object.key("jitSubscriptionRoleArn").string(var_2.as_str());
    }
    if let Some(var_3) = &input.oidc_claim_keys {
        #[allow(unused_mut)]
        let mut object_4 = object.key("oidcClaimKeys").start_object();
        crate::protocol_serde::shape_oidc_claim_keys::ser_oidc_claim_keys(&mut object_4, var_3)?;
        object_4.finish();
    }
    Ok(())
}
