// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_external_identity_source(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::types::ExternalIdentitySource,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    {
        object.key("issuerUrl").string(input.issuer_url.as_str());
    }
    {
        object.key("clientId").string(input.client_id.as_str());
    }
    if let Some(var_1) = &input.subscription_start_type {
        object.key("subscriptionStartType").string(var_1.as_str());
    }
    Ok(())
}
