[package]
name = "fig_install"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
cfg-if = "1.0.0"
crossterm = "0.24.0"
fig_api_client = { version = "0.1.0", path = "../fig_api_client" }
fig_auth = { path = "../fig_auth" }
fig_request = { path = "../fig_request" }
fig_settings = { path = "../fig_settings" }
fig_util = { path = "../fig_util" }
flume = "0.10.14"
futures = "0.3.21"
git2 = { version = "0.15.0", features = ["vendored-openssl", "vendored-libgit2"] }
once_cell = { version = "1.13.0", features = ["parking_lot"] }
parking_lot = "0.12.1"
regex = "1.6.0"
reqwest = { version = "0.11.10", default-features = false, features = ["json", "rustls-tls-webpki-roots"] }
serde = { version = "1.0.142", features = ["derive"] }
serde_json = "1.0.83"
tempfile = "3.3.0"
thiserror = "1.0.32"
time = { version = "=0.3.12", features = ["serde-human-readable"] }
tokio = "1.20.1"
tracing = "0.1.36"
url = { version = "2.2.2", features = ["serde"] }

