[package]
name = "fig_install"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
bitflags = "1.3.2"
camino = "1.1.1"
cfg-if = "1.0.0"
fig_daemon = { path = "../fig_daemon" }
fig_request = { path = "../fig_request" }
fig_integrations = { path = "../fig_integrations" }
fig_util = { path = "../fig_util" }
once_cell = "1.15.0"
regex = "1.6.0"
reqwest = { version = "0.11.12", default-features = false }
semver = { version = "1.0.14", features = ["serde"] }
serde = { version = "1.0.147", features = ["derive"] }
tempdir = "0.3.7"
thiserror = "1.0.36"
tokio = "1.20.1"
tracing = "0.1.36"
fig_settings = { path = "../fig_settings" }
strum = "0.24.1"
fig_telemetry = { path = "../fig_telemetry" }

[target.'cfg(target_os = "macos")'.dependencies]
fig_ipc = { path = "../fig_ipc" }
libc = "0.2.137"
