[package]
name = "fig_install"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
cfg-if = "1.0.0"
fig_util = { path = "../fig_util" }
once_cell = "1.14.0"
reqwest = { version = "0.11.10", default-features = false, features = ["rustls-tls-webpki-roots"] }
semver = "1.0.13"
serde = { version = "1.0.143", features = ["derive"] }
thiserror = "1.0.35"
tokio = "1.20.1"
tracing = "0.1.36"
