[package]
name = "fig_install"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
cfg-if = "1.0.0"
fig_request = { path = "../fig_request" }
fig_util = { path = "../fig_util" }
once_cell = "1.15.0"
reqwest = { version = "0.11.12", default-features = false }
semver = "1.0.14"
serde = { version = "1.0.143", features = ["derive"] }
thiserror = "1.0.36"
tokio = "1.20.1"
tracing = "0.1.36"

[target.'cfg(target_os = "macos")'.dependencies]
fig_ipc = { path = "../fig_ipc" }
