[test]
root = "src"
coverage = true
coverageReporter = ["text", "lcov"]
coverageSkipTestFiles = true
coveragePathIgnorePatterns = ["**/dist/**", "**/node_modules/**", "**/twinki/**", "**/ink/**"]
preload = ["./e2e_tests/preload.ts"]
