[package]
name = "fig_request"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fig_auth = { version = "0.1.0", path = "../fig_auth" }
fig_settings = { version = "0.1.0", path = "../fig_settings" }
reqwest = "0.11.11"
serde = "1.0.137"
serde_json = "1.0.82"
thiserror = "1.0.31"
url = "2.2.2"
