[package]
name = "fig_request"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bytes = "1.1.0"
fig_auth = { version = "0.1.0", path = "../fig_auth" }
fig_settings = { version = "0.1.0", path = "../fig_settings" }
once_cell = { version = "1.13.0", features = ["parking_lot"] }
reqwest = { version = "0.11.10", default-features = false, features = ["json", "rustls-tls-webpki-roots", "socks", "gzip", "brotli"] }
serde = "1.0.139"
serde_json = "1.0.82"
thiserror = "1.0.31"
url = "2.2.2"

[dev-dependencies]
tokio = { version = "1.20.0", features = ["full"] }
