[package]
name = "fig_request"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bytes = "1.2.1"
fig_auth = { path = "../fig_auth" }
fig_settings = { path = "../fig_settings" }
once_cell = { version = "1.13.0", features = ["parking_lot"] }
reqwest = { version = "0.11.10", default-features = false, features = ["json", "rustls-tls-webpki-roots", "socks", "cookies"] }
serde = "1.0.142"
serde_json = "1.0.83"
thiserror = "1.0.32"
url = "2.2.2"

[dev-dependencies]
tokio = { version = "1.20.1", features = ["full"] }
