// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_kiro_enterprise_telemetry_event(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::types::KiroEnterpriseTelemetryEvent,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    {
        object.key("messageId").string(input.message_id.as_str());
    }
    {
        object.key("conversationId").string(input.conversation_id.as_str());
    }
    {
        object.key("origin").string(input.origin.as_str());
    }
    {
        object.key("userId").string(input.user_id.as_str());
    }
    {
        object.key("date").string(input.date.as_str());
    }
    if let Some(var_1) = &input.subscription_tier {
        object.key("subscriptionTier").string(var_1.as_str());
    }
    if let Some(var_2) = &input.overage_enabled {
        object.key("overageEnabled").boolean(*var_2);
    }
    if let Some(var_3) = &input.overage_cap {
        object.key("overageCap").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::NegInt((*var_3).into()),
        );
    }
    if let Some(var_4) = &input.profile_id {
        object.key("profileId").string(var_4.as_str());
    }
    if let Some(var_5) = &input.new_user {
        object.key("newUser").boolean(*var_5);
    }
    if let Some(var_6) = &input.chat_messages_vibe {
        object.key("chatMessagesVibe").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::NegInt((*var_6).into()),
        );
    }
    if let Some(var_7) = &input.chat_messages_spec {
        object.key("chatMessagesSpec").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::NegInt((*var_7).into()),
        );
    }
    if let Some(var_8) = &input.chat_messages_others {
        object.key("chatMessagesOthers").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::NegInt((*var_8).into()),
        );
    }
    if let Some(var_9) = &input.chat_messages {
        object.key("chatMessages").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::NegInt((*var_9).into()),
        );
    }
    if let Some(var_10) = &input.chat_message_duration {
        object.key("chatMessageDuration").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::Float((*var_10).into()),
        );
    }
    if let Some(var_11) = &input.chat_conversations_trusted {
        object.key("chatConversationsTrusted").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::NegInt((*var_11).into()),
        );
    }
    if let Some(var_12) = &input.code_blocks_generated {
        object.key("codeBlocksGenerated").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::NegInt((*var_12).into()),
        );
    }
    if let Some(var_13) = &input.code_blocks_inserted {
        object.key("codeBlocksInserted").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::NegInt((*var_13).into()),
        );
    }
    if let Some(var_14) = &input.context_files {
        object.key("contextFiles").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::NegInt((*var_14).into()),
        );
    }
    if let Some(var_15) = &input.model_id {
        object.key("modelId").string(var_15.as_str());
    }
    if let Some(var_16) = &input.specs_implemented {
        object.key("specsImplemented").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::NegInt((*var_16).into()),
        );
    }
    if let Some(var_17) = &input.credits_used {
        object.key("creditsUsed").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::Float((*var_17).into()),
        );
    }
    if let Some(var_18) = &input.overage_credits_used {
        object.key("overageCreditsUsed").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::Float((*var_18).into()),
        );
    }
    Ok(())
}
