// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_user_input_message(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::types::UserInputMessage,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    {
        object.key("content").string(input.content.as_str());
    }
    if let Some(var_1) = &input.user_input_message_context {
        #[allow(unused_mut)]
        let mut object_2 = object.key("userInputMessageContext").start_object();
        crate::protocol_serde::shape_user_input_message_context::ser_user_input_message_context(&mut object_2, var_1)?;
        object_2.finish();
    }
    if let Some(var_3) = &input.user_intent {
        object.key("userIntent").string(var_3.as_str());
    }
    if let Some(var_4) = &input.origin {
        object.key("origin").string(var_4.as_str());
    }
    if let Some(var_5) = &input.images {
        let mut array_6 = object.key("images").start_array();
        for item_7 in var_5 {
            {
                #[allow(unused_mut)]
                let mut object_8 = array_6.value().start_object();
                crate::protocol_serde::shape_image_block::ser_image_block(&mut object_8, item_7)?;
                object_8.finish();
            }
        }
        array_6.finish();
    }
    if let Some(var_9) = &input.documents {
        let mut array_10 = object.key("documents").start_array();
        for item_11 in var_9 {
            {
                #[allow(unused_mut)]
                let mut object_12 = array_10.value().start_object();
                crate::protocol_serde::shape_document_block::ser_document_block(&mut object_12, item_11)?;
                object_12.finish();
            }
        }
        array_10.finish();
    }
    if let Some(var_13) = &input.model_id {
        object.key("modelId").string(var_13.as_str());
    }
    if let Some(var_14) = &input.cache_point {
        #[allow(unused_mut)]
        let mut object_15 = object.key("cachePoint").start_object();
        crate::protocol_serde::shape_cache_point::ser_cache_point(&mut object_15, var_14)?;
        object_15.finish();
    }
    if let Some(var_16) = &input.client_cache_config {
        #[allow(unused_mut)]
        let mut object_17 = object.key("clientCacheConfig").start_object();
        crate::protocol_serde::shape_client_cache_config::ser_client_cache_config(&mut object_17, var_16)?;
        object_17.finish();
    }
    Ok(())
}
