// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_chat_interact_with_message_event(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::types::ChatInteractWithMessageEvent,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    {
        object.key("conversationId").string(input.conversation_id.as_str());
    }
    {
        object.key("messageId").string(input.message_id.as_str());
    }
    if let Some(var_1) = &input.customization_arn {
        object.key("customizationArn").string(var_1.as_str());
    }
    if let Some(var_2) = &input.programming_language {
        #[allow(unused_mut)]
        let mut object_3 = object.key("programmingLanguage").start_object();
        crate::protocol_serde::shape_programming_language::ser_programming_language(&mut object_3, var_2)?;
        object_3.finish();
    }
    if let Some(var_4) = &input.interaction_type {
        object.key("interactionType").string(var_4.as_str());
    }
    if let Some(var_5) = &input.interaction_target {
        object.key("interactionTarget").string(var_5.as_str());
    }
    if let Some(var_6) = &input.accepted_character_count {
        object.key("acceptedCharacterCount").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::NegInt((*var_6).into()),
        );
    }
    if let Some(var_7) = &input.accepted_line_count {
        object.key("acceptedLineCount").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::NegInt((*var_7).into()),
        );
    }
    if let Some(var_8) = &input.accepted_snippet_has_reference {
        object.key("acceptedSnippetHasReference").boolean(*var_8);
    }
    if let Some(var_9) = &input.has_project_level_context {
        object.key("hasProjectLevelContext").boolean(*var_9);
    }
    if let Some(var_10) = &input.user_intent {
        object.key("userIntent").string(var_10.as_str());
    }
    if let Some(var_11) = &input.added_ide_diagnostics {
        let mut array_12 = object.key("addedIdeDiagnostics").start_array();
        for item_13 in var_11 {
            {
                #[allow(unused_mut)]
                let mut object_14 = array_12.value().start_object();
                crate::protocol_serde::shape_ide_diagnostic::ser_ide_diagnostic(&mut object_14, item_13)?;
                object_14.finish();
            }
        }
        array_12.finish();
    }
    if let Some(var_15) = &input.removed_ide_diagnostics {
        let mut array_16 = object.key("removedIdeDiagnostics").start_array();
        for item_17 in var_15 {
            {
                #[allow(unused_mut)]
                let mut object_18 = array_16.value().start_object();
                crate::protocol_serde::shape_ide_diagnostic::ser_ide_diagnostic(&mut object_18, item_17)?;
                object_18.finish();
            }
        }
        array_16.finish();
    }
    Ok(())
}
