// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_kiro_chat_message_event(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::types::KiroChatMessageEvent,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    {
        object.key("messageId").string(input.message_id.as_str());
    }
    {
        object.key("conversationId").string(input.conversation_id.as_str());
    }
    {
        object.key("origin").string(input.origin.as_str());
    }
    {
        object.key("userId").string(input.user_id.as_str());
    }
    {
        object.key("date").string(input.date.as_str());
    }
    if let Some(var_1) = &input.subscription_tier {
        object.key("subscriptionTier").string(var_1.as_str());
    }
    if let Some(var_2) = &input.overage_enabled {
        object.key("overageEnabled").boolean(*var_2);
    }
    if let Some(var_3) = &input.overage_cap {
        object.key("overageCap").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::Float((*var_3).into()),
        );
    }
    if let Some(var_4) = &input.profile_id {
        object.key("profileId").string(var_4.as_str());
    }
    if let Some(var_5) = &input.new_user {
        object.key("newUser").boolean(*var_5);
    }
    if let Some(var_6) = &input.chat_agent_mode {
        object.key("chatAgentMode").string(var_6.as_str());
    }
    if let Some(var_7) = &input.chat_autonomy_mode {
        object.key("chatAutonomyMode").string(var_7.as_str());
    }
    if let Some(var_8) = &input.chat_message_duration {
        object.key("chatMessageDuration").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::Float((*var_8).into()),
        );
    }
    if let Some(var_9) = &input.model_id {
        object.key("modelId").string(var_9.as_str());
    }
    if let Some(var_10) = &input.credits_used {
        object.key("creditsUsed").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::Float((*var_10).into()),
        );
    }
    if let Some(var_11) = &input.overage_credits_used {
        object.key("overageCreditsUsed").number(
            #[allow(clippy::useless_conversion)]
            ::aws_smithy_types::Number::Float((*var_11).into()),
        );
    }
    Ok(())
}
