// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(clippy::unnecessary_wraps)]
pub fn de_invoke_mcp_stream_http_response(
    response: &mut ::aws_smithy_runtime_api::http::Response,
) -> std::result::Result<
    crate::operation::invoke_mcp_stream::InvokeMcpStreamOutput,
    crate::operation::invoke_mcp_stream::InvokeMCPStreamError,
> {
    let mut _response_body = ::aws_smithy_types::body::SdkBody::taken();
    std::mem::swap(&mut _response_body, response.body_mut());
    let _response_body = &mut _response_body;

    let _response_status = response.status().as_u16();
    let _response_headers = response.headers();
    Ok({
        #[allow(unused_mut)]
        let mut output = crate::operation::invoke_mcp_stream::builders::InvokeMcpStreamOutputBuilder::default();
        output = output.set_stream(Some(
            crate::protocol_serde::shape_invoke_mcp_stream_output::de_stream_payload(_response_body)?,
        ));
        output._set_request_id(::aws_types::request_id::RequestId::request_id(_response_headers).map(str::to_string));
        output
            .build()
            .map_err(crate::operation::invoke_mcp_stream::InvokeMCPStreamError::unhandled)?
    })
}

#[allow(clippy::unnecessary_wraps)]
pub fn de_invoke_mcp_stream_http_error(
    _response_status: u16,
    _response_headers: &::aws_smithy_runtime_api::http::Headers,
    _response_body: &[u8],
) -> std::result::Result<
    crate::operation::invoke_mcp_stream::InvokeMcpStreamOutput,
    crate::operation::invoke_mcp_stream::InvokeMCPStreamError,
> {
    #[allow(unused_mut)]
    let mut generic_builder =
        crate::protocol_serde::parse_http_error_metadata(_response_status, _response_headers, _response_body)
            .map_err(crate::operation::invoke_mcp_stream::InvokeMCPStreamError::unhandled)?;
    generic_builder = ::aws_types::request_id::apply_request_id(generic_builder, _response_headers);
    let generic = generic_builder.build();
    let error_code = match generic.code() {
        Some(code) => code,
        None => {
            return Err(crate::operation::invoke_mcp_stream::InvokeMCPStreamError::unhandled(
                generic,
            ));
        },
    };

    let _error_message = generic.message().map(|msg| msg.to_owned());
    Err(match error_code {
        "AccessDeniedError" => crate::operation::invoke_mcp_stream::InvokeMCPStreamError::AccessDeniedError({
            #[allow(unused_mut)]
            let mut tmp = {
                #[allow(unused_mut)]
                let mut output = crate::types::error::builders::AccessDeniedErrorBuilder::default();
                output = crate::protocol_serde::shape_access_denied_error::de_access_denied_error_json_err(
                    _response_body,
                    output,
                )
                .map_err(crate::operation::invoke_mcp_stream::InvokeMCPStreamError::unhandled)?;
                let output = output.meta(generic);
                crate::serde_util::access_denied_error_correct_errors(output)
                    .build()
                    .map_err(crate::operation::invoke_mcp_stream::InvokeMCPStreamError::unhandled)?
            };
            tmp
        }),
        "InternalServerError" => crate::operation::invoke_mcp_stream::InvokeMCPStreamError::InternalServerError({
            #[allow(unused_mut)]
            let mut tmp = {
                #[allow(unused_mut)]
                let mut output = crate::types::error::builders::InternalServerErrorBuilder::default();
                output = crate::protocol_serde::shape_internal_server_error::de_internal_server_error_json_err(
                    _response_body,
                    output,
                )
                .map_err(crate::operation::invoke_mcp_stream::InvokeMCPStreamError::unhandled)?;
                let output = output.meta(generic);
                crate::serde_util::internal_server_error_correct_errors(output)
                    .build()
                    .map_err(crate::operation::invoke_mcp_stream::InvokeMCPStreamError::unhandled)?
            };
            tmp
        }),
        "ThrottlingError" => crate::operation::invoke_mcp_stream::InvokeMCPStreamError::ThrottlingError({
            #[allow(unused_mut)]
            let mut tmp = {
                #[allow(unused_mut)]
                let mut output = crate::types::error::builders::ThrottlingErrorBuilder::default();
                output =
                    crate::protocol_serde::shape_throttling_error::de_throttling_error_json_err(_response_body, output)
                        .map_err(crate::operation::invoke_mcp_stream::InvokeMCPStreamError::unhandled)?;
                let output = output.meta(generic);
                crate::serde_util::throttling_error_correct_errors(output)
                    .build()
                    .map_err(crate::operation::invoke_mcp_stream::InvokeMCPStreamError::unhandled)?
            };
            tmp
        }),
        "ValidationError" => crate::operation::invoke_mcp_stream::InvokeMCPStreamError::ValidationError({
            #[allow(unused_mut)]
            let mut tmp = {
                #[allow(unused_mut)]
                let mut output = crate::types::error::builders::ValidationErrorBuilder::default();
                output =
                    crate::protocol_serde::shape_validation_error::de_validation_error_json_err(_response_body, output)
                        .map_err(crate::operation::invoke_mcp_stream::InvokeMCPStreamError::unhandled)?;
                let output = output.meta(generic);
                crate::serde_util::validation_error_correct_errors(output)
                    .build()
                    .map_err(crate::operation::invoke_mcp_stream::InvokeMCPStreamError::unhandled)?
            };
            tmp
        }),
        _ => crate::operation::invoke_mcp_stream::InvokeMCPStreamError::generic(generic),
    })
}

pub fn ser_invoke_mcp_stream_input(
    input: &crate::operation::invoke_mcp_stream::InvokeMcpStreamInput,
) -> ::std::result::Result<::aws_smithy_types::body::SdkBody, ::aws_smithy_types::error::operation::SerializationError>
{
    let mut out = String::new();
    let mut object = ::aws_smithy_json::serialize::JsonObjectWriter::new(&mut out);
    crate::protocol_serde::shape_invoke_mcp_stream_input::ser_invoke_mcp_stream_input_input(&mut object, input)?;
    object.finish();
    Ok(::aws_smithy_types::body::SdkBody::from(out))
}

pub(crate) fn de_invoke_mcp_stream(
    value: &[u8],
    mut builder: crate::operation::invoke_mcp_stream::builders::InvokeMcpStreamOutputBuilder,
) -> ::std::result::Result<
    crate::operation::invoke_mcp_stream::builders::InvokeMcpStreamOutputBuilder,
    ::aws_smithy_json::deserialize::error::DeserializeError,
> {
    let mut tokens_owned =
        ::aws_smithy_json::deserialize::json_token_iter(crate::protocol_serde::or_empty_doc(value)).peekable();
    let tokens = &mut tokens_owned;
    ::aws_smithy_json::deserialize::token::expect_start_object(tokens.next())?;
    loop {
        match tokens.next().transpose()? {
            Some(::aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
            Some(::aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => match key.to_unescaped()?.as_ref() {
                "contentType" => {
                    builder = builder.set_content_type(
                        ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?
                            .map(|s| s.to_unescaped().map(|u| u.into_owned()))
                            .transpose()?,
                    );
                },
                _ => ::aws_smithy_json::deserialize::token::skip_value(tokens)?,
            },
            other => {
                return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(
                    format!("expected object key or end object, found: {other:?}"),
                ));
            },
        }
    }
    if tokens.next().is_some() {
        return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(
            "found more JSON tokens after completing parsing",
        ));
    }
    Ok(builder)
}
