// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub(crate) fn de_json_rpc_stream_event_payload(
    input: &[u8],
) -> ::std::result::Result<crate::types::JsonRpcStreamEvent, ::aws_smithy_json::deserialize::error::DeserializeError> {
    let mut tokens_owned =
        ::aws_smithy_json::deserialize::json_token_iter(crate::protocol_serde::or_empty_doc(input)).peekable();
    let tokens = &mut tokens_owned;
    let result =
        crate::protocol_serde::shape_json_rpc_stream_event::de_json_rpc_stream_event(tokens)?.ok_or_else(|| {
            ::aws_smithy_json::deserialize::error::DeserializeError::custom("expected payload member value")
        });
    if tokens.next().is_some() {
        return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(
            "found more JSON tokens after completing parsing",
        ));
    }
    result
}

pub(crate) fn de_json_rpc_stream_event<'a, I>(
    tokens: &mut ::std::iter::Peekable<I>,
) -> ::std::result::Result<
    Option<crate::types::JsonRpcStreamEvent>,
    ::aws_smithy_json::deserialize::error::DeserializeError,
>
where
    I: Iterator<
        Item = Result<
            ::aws_smithy_json::deserialize::Token<'a>,
            ::aws_smithy_json::deserialize::error::DeserializeError,
        >,
    >,
{
    match tokens.next().transpose()? {
        Some(::aws_smithy_json::deserialize::Token::ValueNull { .. }) => Ok(None),
        Some(::aws_smithy_json::deserialize::Token::StartObject { .. }) => {
            #[allow(unused_mut)]
            let mut builder = crate::types::builders::JsonRpcStreamEventBuilder::default();
            loop {
                match tokens.next().transpose()? {
                    Some(::aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
                    Some(::aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => {
                        match key.to_unescaped()?.as_ref() {
                            "jsonrpc" => {
                                builder = builder.set_jsonrpc(
                                    ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?
                                        .map(|s| s.to_unescaped().map(|u| u.into_owned()))
                                        .transpose()?,
                                );
                            },
                            "method" => {
                                builder = builder.set_method(
                                    ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?
                                        .map(|s| s.to_unescaped().map(|u| u.into_owned()))
                                        .transpose()?,
                                );
                            },
                            "params" => {
                                builder = builder
                                    .set_params(Some(::aws_smithy_json::deserialize::token::expect_document(tokens)?));
                            },
                            "id" => {
                                builder = builder
                                    .set_id(Some(::aws_smithy_json::deserialize::token::expect_document(tokens)?));
                            },
                            "result" => {
                                builder = builder
                                    .set_result(Some(::aws_smithy_json::deserialize::token::expect_document(tokens)?));
                            },
                            "error" => {
                                builder = builder
                                    .set_error(crate::protocol_serde::shape_json_rpc_error::de_json_rpc_error(tokens)?);
                            },
                            _ => ::aws_smithy_json::deserialize::token::skip_value(tokens)?,
                        }
                    },
                    other => {
                        return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(
                            format!("expected object key or end object, found: {other:?}"),
                        ));
                    },
                }
            }
            Ok(Some(
                crate::serde_util::json_rpc_stream_event_correct_errors(builder)
                    .build()
                    .map_err(|err| {
                        ::aws_smithy_json::deserialize::error::DeserializeError::custom_source(
                            "Response was invalid",
                            err,
                        )
                    })?,
            ))
        },
        _ => Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(
            "expected start object or null",
        )),
    }
}
