// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_document_source(
    object_1: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::types::DocumentSource,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    match input {
        crate::types::DocumentSource::Bytes(inner) => {
            object_1
                .key("bytes")
                .string_unchecked(&::aws_smithy_types::base64::encode(inner));
        },
        crate::types::DocumentSource::Unknown => {
            return Err(::aws_smithy_types::error::operation::SerializationError::unknown_variant("DocumentSource"));
        },
    }
    Ok(())
}
