[package]
name = "fig-log"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
fig-directories = { path = "../fig-directories" }
once_cell = "1.10.0"
parking_lot = "0.12.0"
tracing = "0.1.32"
tracing-subscriber = "0.3.10"