// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ExternalIdentitySource {
    #[allow(missing_docs)] // documentation missing in model
    pub issuer_url: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub client_id: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub subscription_start_type: ::std::option::Option<crate::types::SubscriptionStartType>,
}
impl ExternalIdentitySource {
    #[allow(missing_docs)] // documentation missing in model
    pub fn issuer_url(&self) -> &str {
        use std::ops::Deref;
        self.issuer_url.deref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn client_id(&self) -> &str {
        use std::ops::Deref;
        self.client_id.deref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn subscription_start_type(&self) -> ::std::option::Option<&crate::types::SubscriptionStartType> {
        self.subscription_start_type.as_ref()
    }
}
impl ExternalIdentitySource {
    /// Creates a new builder-style object to manufacture
    /// [`ExternalIdentitySource`](crate::types::ExternalIdentitySource).
    pub fn builder() -> crate::types::builders::ExternalIdentitySourceBuilder {
        crate::types::builders::ExternalIdentitySourceBuilder::default()
    }
}

/// A builder for [`ExternalIdentitySource`](crate::types::ExternalIdentitySource).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ExternalIdentitySourceBuilder {
    pub(crate) issuer_url: ::std::option::Option<::std::string::String>,
    pub(crate) client_id: ::std::option::Option<::std::string::String>,
    pub(crate) subscription_start_type: ::std::option::Option<crate::types::SubscriptionStartType>,
}
impl ExternalIdentitySourceBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn issuer_url(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.issuer_url = ::std::option::Option::Some(input.into());
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_issuer_url(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.issuer_url = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_issuer_url(&self) -> &::std::option::Option<::std::string::String> {
        &self.issuer_url
    }

    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn client_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.client_id = ::std::option::Option::Some(input.into());
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_client_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.client_id = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_client_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.client_id
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn subscription_start_type(mut self, input: crate::types::SubscriptionStartType) -> Self {
        self.subscription_start_type = ::std::option::Option::Some(input);
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_subscription_start_type(
        mut self,
        input: ::std::option::Option<crate::types::SubscriptionStartType>,
    ) -> Self {
        self.subscription_start_type = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_subscription_start_type(&self) -> &::std::option::Option<crate::types::SubscriptionStartType> {
        &self.subscription_start_type
    }

    /// Consumes the builder and constructs a
    /// [`ExternalIdentitySource`](crate::types::ExternalIdentitySource). This method will fail
    /// if any of the following fields are not set:
    /// - [`issuer_url`](crate::types::builders::ExternalIdentitySourceBuilder::issuer_url)
    /// - [`client_id`](crate::types::builders::ExternalIdentitySourceBuilder::client_id)
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::types::ExternalIdentitySource, ::aws_smithy_types::error::operation::BuildError>
    {
        ::std::result::Result::Ok(crate::types::ExternalIdentitySource {
            issuer_url: self.issuer_url.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "issuer_url",
                    "issuer_url was not specified but it is required when building ExternalIdentitySource",
                )
            })?,
            client_id: self.client_id.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "client_id",
                    "client_id was not specified but it is required when building ExternalIdentitySource",
                )
            })?,
            subscription_start_type: self.subscription_start_type,
        })
    }
}
