// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub struct ExternalIdentityDetails {
    #[allow(missing_docs)] // documentation missing in model
    pub issuer_url: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub client_id: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub scim_endpoint: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub subscription_start_type: ::std::option::Option<crate::types::SubscriptionStartType>,
    #[allow(missing_docs)] // documentation missing in model
    pub jit_subscription_role_arn: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub oidc_claim_keys: ::std::option::Option<crate::types::OidcClaimKeys>,
}
impl ExternalIdentityDetails {
    #[allow(missing_docs)] // documentation missing in model
    pub fn issuer_url(&self) -> ::std::option::Option<&str> {
        self.issuer_url.as_deref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn client_id(&self) -> ::std::option::Option<&str> {
        self.client_id.as_deref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn scim_endpoint(&self) -> ::std::option::Option<&str> {
        self.scim_endpoint.as_deref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn subscription_start_type(&self) -> ::std::option::Option<&crate::types::SubscriptionStartType> {
        self.subscription_start_type.as_ref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn jit_subscription_role_arn(&self) -> ::std::option::Option<&str> {
        self.jit_subscription_role_arn.as_deref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn oidc_claim_keys(&self) -> ::std::option::Option<&crate::types::OidcClaimKeys> {
        self.oidc_claim_keys.as_ref()
    }
}
impl ::std::fmt::Debug for ExternalIdentityDetails {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("ExternalIdentityDetails");
        formatter.field("issuer_url", &"*** Sensitive Data Redacted ***");
        formatter.field("client_id", &"*** Sensitive Data Redacted ***");
        formatter.field("scim_endpoint", &self.scim_endpoint);
        formatter.field("subscription_start_type", &self.subscription_start_type);
        formatter.field("jit_subscription_role_arn", &self.jit_subscription_role_arn);
        formatter.field("oidc_claim_keys", &self.oidc_claim_keys);
        formatter.finish()
    }
}
impl ExternalIdentityDetails {
    /// Creates a new builder-style object to manufacture
    /// [`ExternalIdentityDetails`](crate::types::ExternalIdentityDetails).
    pub fn builder() -> crate::types::builders::ExternalIdentityDetailsBuilder {
        crate::types::builders::ExternalIdentityDetailsBuilder::default()
    }
}

/// A builder for [`ExternalIdentityDetails`](crate::types::ExternalIdentityDetails).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default)]
#[non_exhaustive]
pub struct ExternalIdentityDetailsBuilder {
    pub(crate) issuer_url: ::std::option::Option<::std::string::String>,
    pub(crate) client_id: ::std::option::Option<::std::string::String>,
    pub(crate) scim_endpoint: ::std::option::Option<::std::string::String>,
    pub(crate) subscription_start_type: ::std::option::Option<crate::types::SubscriptionStartType>,
    pub(crate) jit_subscription_role_arn: ::std::option::Option<::std::string::String>,
    pub(crate) oidc_claim_keys: ::std::option::Option<crate::types::OidcClaimKeys>,
}
impl ExternalIdentityDetailsBuilder {
    #[allow(missing_docs)] // documentation missing in model
    pub fn issuer_url(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.issuer_url = ::std::option::Option::Some(input.into());
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_issuer_url(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.issuer_url = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_issuer_url(&self) -> &::std::option::Option<::std::string::String> {
        &self.issuer_url
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn client_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.client_id = ::std::option::Option::Some(input.into());
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_client_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.client_id = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_client_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.client_id
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn scim_endpoint(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.scim_endpoint = ::std::option::Option::Some(input.into());
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_scim_endpoint(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.scim_endpoint = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_scim_endpoint(&self) -> &::std::option::Option<::std::string::String> {
        &self.scim_endpoint
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn subscription_start_type(mut self, input: crate::types::SubscriptionStartType) -> Self {
        self.subscription_start_type = ::std::option::Option::Some(input);
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_subscription_start_type(
        mut self,
        input: ::std::option::Option<crate::types::SubscriptionStartType>,
    ) -> Self {
        self.subscription_start_type = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_subscription_start_type(&self) -> &::std::option::Option<crate::types::SubscriptionStartType> {
        &self.subscription_start_type
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn jit_subscription_role_arn(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.jit_subscription_role_arn = ::std::option::Option::Some(input.into());
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_jit_subscription_role_arn(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.jit_subscription_role_arn = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_jit_subscription_role_arn(&self) -> &::std::option::Option<::std::string::String> {
        &self.jit_subscription_role_arn
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn oidc_claim_keys(mut self, input: crate::types::OidcClaimKeys) -> Self {
        self.oidc_claim_keys = ::std::option::Option::Some(input);
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_oidc_claim_keys(mut self, input: ::std::option::Option<crate::types::OidcClaimKeys>) -> Self {
        self.oidc_claim_keys = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_oidc_claim_keys(&self) -> &::std::option::Option<crate::types::OidcClaimKeys> {
        &self.oidc_claim_keys
    }

    /// Consumes the builder and constructs a
    /// [`ExternalIdentityDetails`](crate::types::ExternalIdentityDetails).
    pub fn build(self) -> crate::types::ExternalIdentityDetails {
        crate::types::ExternalIdentityDetails {
            issuer_url: self.issuer_url,
            client_id: self.client_id,
            scim_endpoint: self.scim_endpoint,
            subscription_start_type: self.subscription_start_type,
            jit_subscription_role_arn: self.jit_subscription_role_arn,
            oidc_claim_keys: self.oidc_claim_keys,
        }
    }
}
impl ::std::fmt::Debug for ExternalIdentityDetailsBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("ExternalIdentityDetailsBuilder");
        formatter.field("issuer_url", &"*** Sensitive Data Redacted ***");
        formatter.field("client_id", &"*** Sensitive Data Redacted ***");
        formatter.field("scim_endpoint", &self.scim_endpoint);
        formatter.field("subscription_start_type", &self.subscription_start_type);
        formatter.field("jit_subscription_role_arn", &self.jit_subscription_role_arn);
        formatter.field("oidc_claim_keys", &self.oidc_claim_keys);
        formatter.finish()
    }
}
