// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub struct OidcClaimKeys {
    #[allow(missing_docs)] // documentation missing in model
    pub token_id_claim_key: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub user_id_claim_key: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub app_claim_key: ::std::string::String,
}
impl OidcClaimKeys {
    #[allow(missing_docs)] // documentation missing in model
    pub fn token_id_claim_key(&self) -> &str {
        use std::ops::Deref;
        self.token_id_claim_key.deref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn user_id_claim_key(&self) -> &str {
        use std::ops::Deref;
        self.user_id_claim_key.deref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn app_claim_key(&self) -> &str {
        use std::ops::Deref;
        self.app_claim_key.deref()
    }
}
impl ::std::fmt::Debug for OidcClaimKeys {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("OidcClaimKeys");
        formatter.field("token_id_claim_key", &"*** Sensitive Data Redacted ***");
        formatter.field("user_id_claim_key", &"*** Sensitive Data Redacted ***");
        formatter.field("app_claim_key", &"*** Sensitive Data Redacted ***");
        formatter.finish()
    }
}
impl OidcClaimKeys {
    /// Creates a new builder-style object to manufacture
    /// [`OidcClaimKeys`](crate::types::OidcClaimKeys).
    pub fn builder() -> crate::types::builders::OidcClaimKeysBuilder {
        crate::types::builders::OidcClaimKeysBuilder::default()
    }
}

/// A builder for [`OidcClaimKeys`](crate::types::OidcClaimKeys).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default)]
#[non_exhaustive]
pub struct OidcClaimKeysBuilder {
    pub(crate) token_id_claim_key: ::std::option::Option<::std::string::String>,
    pub(crate) user_id_claim_key: ::std::option::Option<::std::string::String>,
    pub(crate) app_claim_key: ::std::option::Option<::std::string::String>,
}
impl OidcClaimKeysBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn token_id_claim_key(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.token_id_claim_key = ::std::option::Option::Some(input.into());
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_token_id_claim_key(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.token_id_claim_key = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_token_id_claim_key(&self) -> &::std::option::Option<::std::string::String> {
        &self.token_id_claim_key
    }

    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn user_id_claim_key(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.user_id_claim_key = ::std::option::Option::Some(input.into());
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_user_id_claim_key(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.user_id_claim_key = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_user_id_claim_key(&self) -> &::std::option::Option<::std::string::String> {
        &self.user_id_claim_key
    }

    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn app_claim_key(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.app_claim_key = ::std::option::Option::Some(input.into());
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_app_claim_key(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.app_claim_key = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_app_claim_key(&self) -> &::std::option::Option<::std::string::String> {
        &self.app_claim_key
    }

    /// Consumes the builder and constructs a [`OidcClaimKeys`](crate::types::OidcClaimKeys).
    /// This method will fail if any of the following fields are not set:
    /// - [`token_id_claim_key`](crate::types::builders::OidcClaimKeysBuilder::token_id_claim_key)
    /// - [`user_id_claim_key`](crate::types::builders::OidcClaimKeysBuilder::user_id_claim_key)
    /// - [`app_claim_key`](crate::types::builders::OidcClaimKeysBuilder::app_claim_key)
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::types::OidcClaimKeys, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::OidcClaimKeys {
            token_id_claim_key: self.token_id_claim_key.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "token_id_claim_key",
                    "token_id_claim_key was not specified but it is required when building OidcClaimKeys",
                )
            })?,
            user_id_claim_key: self.user_id_claim_key.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "user_id_claim_key",
                    "user_id_claim_key was not specified but it is required when building OidcClaimKeys",
                )
            })?,
            app_claim_key: self.app_claim_key.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "app_claim_key",
                    "app_claim_key was not specified but it is required when building OidcClaimKeys",
                )
            })?,
        })
    }
}
impl ::std::fmt::Debug for OidcClaimKeysBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("OidcClaimKeysBuilder");
        formatter.field("token_id_claim_key", &"*** Sensitive Data Redacted ***");
        formatter.field("user_id_claim_key", &"*** Sensitive Data Redacted ***");
        formatter.field("app_claim_key", &"*** Sensitive Data Redacted ***");
        formatter.finish()
    }
}
