[package]
name = "tui"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
newton = { path = "../newton" }
paste = "1.0.9"
