[package]
name = "fig_log"
version = "0.1.0"
authors = ["fig developers"]
edition = "2021"
homepage = "https://fig.io"
publish = false

[features]
default = []
console = ["console-subscriber"]

[dependencies]
console-subscriber = { version = "0.1.7", optional = true, features = ["parking_lot"] }
fig_util = { path = "../fig_util" }
once_cell = "1.13.1"
thiserror = "1.0.32"
tracing = "0.1.36"
tracing-appender = "0.2.2"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.15", features = ["env-filter", "parking_lot"] }
