[package]
name = "fig_log"
version = "0.1.0"
authors = ["fig developers"]
edition = "2021"
homepage = "https://fig.io"
publish = false

[dependencies]
anyhow = "1.0.56"
fig_directories = { path = "../fig_directories" }
once_cell = "1.12.0"
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.10", features = ["env-filter", "parking_lot"] }
tracing-appender = "0.2.2"
