[package]
name = "fig_cli"
version = "1.4.1"
authors = ["fig developers"]
edition = "2021"
description = "The CLI for Fig"
homepage = "https://fig.io"
publish = false

[features]
default = []
deno = ["dep:deno_core", "dep:deno_runtime"]

[dependencies]
anyhow = "1.0.58"
arboard = { version = "2.1.0", default-features = false }
async-trait = "0.1.56"
bitflags = "1.3.2"
cfg-if = "1.0.0"
clap = { version = "3.2.6", features = ["derive"] }
clap_complete = "3.2.2"
clap_complete_fig = "3.2.2"
crossterm = "0.23.1"
ctrlc = "3.2.1"
deno_core = { version = "0.139.0", optional = true }
deno_runtime = { version = "0.65.0", optional = true }
dialoguer = { version = "0.10.1", features = ["fuzzy-select"] }
fig_auth = { path = "../rust-lib/fig_auth" }
fig_directories = { path = "../rust-lib/fig_directories" }
fig_install = { path = "../rust-lib/fig_install" }
fig_integrations = { path = "../rust-lib/fig_integrations" }
fig_ipc = { path = "../rust-lib/fig_ipc" }
fig_proto = { path = "../rust-lib/fig_proto" }
fig_settings = { path = "../rust-lib/fig_settings" }
fig_telemetry = { path = "../rust-lib/fig_telemetry" }
fig_util = { path = "../rust-lib/fig_util" }
flume = "0.10.13"
futures = "0.3.21"
globset = "0.4.9"
humantime = "2.1.0"
notify = "4.0.17"
parking_lot = "0.12.1"
rand = "0.8.5"
regex = "1.5.6"
self_update = "0.30.0"
semver = "1.0.10"
sentry = { version = "0.27.0", features = ["anyhow"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
spinners = "4.1.0"
sysinfo = "0.24.5"
system_socket = { path = "../rust-lib/system_socket" }
tempfile = "3.3.0"
thiserror = "1.0.30"
time = { version = "=0.3.11", features = ["serde-human-readable", "local-offset", "formatting", "macros", "serde-well-known"] }
tokio = { version = "1.19.2", features = ["full"] }
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.9", features = ["fmt", "time", "parking_lot"] }
tui = { path = "../rust-lib/tui" }
validator = "0.15.0"
viu = { path = "../rust-lib/viu" }

[target.'cfg(not(target_os = "macos"))'.dependencies]
reqwest = { version = "0.11.10", features = ["json", "socks"] }
tokio-tungstenite = "0.17.1"

[target.'cfg(target_os = "macos")'.dependencies]
reqwest = { version = "0.11.10", features = ["json", "rustls-tls-webpki-roots", "socks"] }
tokio-tungstenite = { version = "0.17.1", features = ["rustls-tls-webpki-roots"] }

[target.'cfg(unix)'.dependencies]
nix = "0.24.1"
skim = "0.9.4"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.38.0", features = ["Win32_Foundation", "Win32_Security", "Win32_System_Threading"] }

