[package]
name = "fig_cli"
version = "1.4.7"
authors = ["fig developers"]
edition = "2021"
description = "The CLI for Fig"
homepage = "https://fig.io"
publish = false

[features]
default = []
managed = []
deno = ["dep:deno_core", "dep:deno_runtime"]

[dependencies]
anyhow = "1.0.58"
arboard = { version = "2.1.0", default-features = false }
async-trait = "0.1.56"
bitflags = "1.3.2"
cfg-if = "1.0.0"
clap = { version = "3.2.15", features = ["derive"] }
clap_complete = "3.2.2"
clap_complete_fig = "3.2.4"
crossterm = "0.24.0"
ctrlc = "3.2.1"
deno_core = { version = "0.144.0", optional = true }
deno_runtime = { version = "0.70.0", optional = true }
dialoguer = { version = "0.10.1", features = ["fuzzy-select"] }
fig_auth = { path = "../rust-lib/fig_auth" }
fig_directories = { path = "../rust-lib/fig_directories" }
fig_install = { path = "../rust-lib/fig_install" }
fig_integrations = { path = "../rust-lib/fig_integrations" }
fig_ipc = { path = "../rust-lib/fig_ipc" }
fig_log = { path = "../rust-lib/fig_log" }
fig_proto = { path = "../rust-lib/fig_proto" }
fig_request = { version = "0.1.0", path = "../rust-lib/fig_request" }
fig_settings = { path = "../rust-lib/fig_settings" }
fig_telemetry = { path = "../rust-lib/fig_telemetry" }
fig_util = { path = "../rust-lib/fig_util" }
flume = "0.10.14"
futures = "0.3.21"
globset = "0.4.9"
humantime = "2.1.0"
once_cell = "1.13.0"
parking_lot = "0.12.1"
rand = "0.8.5"
regex = "1.6.0"
self_update = { version = "0.30.0", default-features = false, features = [
    "rustls",
] }
semver = "1.0.12"
serde = { version = "1.0.140", features = ["derive"]}
serde_json = "1.0.82"
spinners = "4.1.0"
sysinfo = "0.24.7"
system_socket = { path = "../rust-lib/system_socket" }
tempfile = "3.3.0"
thiserror = "1.0.30"
time = { version = "=0.3.11", features = ["serde-human-readable", "local-offset", "formatting", "macros", "serde-well-known"] }
tokio = { version = "1.20.1", features = ["full"] }
tokio-tungstenite = { version = "=0.17.1", features = ["rustls-tls-webpki-roots"] }
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.15", features = [
    "fmt",
    "time",
    "parking_lot",
] }
tui = { path = "../rust-lib/tui" }
url = "2.2.2"
validator = "0.16.0"
yaque = "0.6.3"

[target.'cfg(unix)'.dependencies]
nix = "0.24.2"
skim = "0.9.4"

[target.'cfg(target_os = "macos")'.dependencies]
notify = "4.0.17"
