[package]
name = "fig_proto"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
arbitrary = { version = "1.1.6", optional = true, features = ["derive"] }
bytes = "1.2.1"
fig_util = { path = "../fig_util" }
hex = "0.4.3"
once_cell = "1.15.0"
prost = "0.11.0"
prost-reflect = { version = "0.9.2", features = ["serde", "derive"] }
prost-types = "0.11"
rmp-serde = "1.1.0"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.87"
thiserror = "1.0.36"

[target.'cfg(unix)'.dependencies]
nix = "0.25.0"

[build-dependencies]
prost-build = "0.11.1"
prost-reflect-build = "0.9.0"
