[package]
name = "fig_desktop"
version = "2.5.0"
authors = ["fig developers"]
edition = "2021"
rust-version = "1.57"
description = "Fig adds IDE-style autocomplete to your existing terminal"
homepage = "https://fig.io"
publish = false
default-run = "fig_desktop"

[package.metadata.bundle]
name = "Fig"
icon = [
    "./icons/128x128.png",
    "./icons/16x16.png",
    "./icons/22x22.png",
    "./icons/24x24.png",
    "./icons/256x256.png",
    "./icons/32x32.png",
    "./icons/48x48.png",
    "./icons/512x512.png",
    "./icons/64x64.png"
]
identifier = "io.fig.desktop"
resource = "./autocomplete-icons/*"

[features]
default = []
console = ["tokio/tracing", "fig_log/console"]
# Required for cargo-tauri CLI
custom-protocol = []

[dependencies]
anyhow = "1.0.65"
base64 = "0.13.0"
bytes = "1.2.1"
camino = { version = "1.0.9", features = ["serde1"] }
cfg-if = "1.0.0"
clap = "3.2.20"
dashmap = "5.3.4"
fig_api_client = { path = "../rust-lib/fig_api_client" }
fig_auth = { path = "../rust-lib/fig_auth" }
fig_install = { path = "../rust-lib/fig_install" }
fig_integrations = { path = "../rust-lib/fig_integrations" }
fig_ipc = { path = "../rust-lib/fig_ipc" }
fig_log = { path = "../rust-lib/fig_log" }
fig_proto = { path = "../rust-lib/fig_proto" }
fig_request = { path = "../rust-lib/fig_request" }
fig_settings = { path = "../rust-lib/fig_settings" }
fig_sync = { path = "../rust-lib/fig_sync" }
fig_telemetry = { path = "../rust-lib/fig_telemetry" }
fig_util = { path = "../rust-lib/fig_util" }
flume = "0.10.14"
fnv = "1.0.7"
hashbrown = "0.12.3"
image = "0.24.3"
imageproc = "0.23.0"
moka = "0.9.4"
notify = "5.0.0-pre.15"
once_cell = "1.14.0"
parking_lot = "0.12.1"
percent-encoding = "2.2.0"
regex = "1.6.0"
semver = "1.0.14"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.85"
shellexpand = "2.1.2"
sysinfo = "0.26.2"
time = { version = "=0.3.14" }
tokio = { version = "1", features = [ "full" ] }
tracing = "0.1.36"
url = "2.3.1"
which = "4.3.0"
whoami = "1.2.1"
wry = { version = "0.21.1", default-features = false, features = ["tray", "protocol", "devtools", "transparent"] }

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.40.0"
features = [
    "implement",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Networking_WinSock",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Com",
    "Win32_System_Console",
    "Win32_System_Ole",
    "Win32_System_Threading",
    "Win32_System_ProcessStatus",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Accessibility",
]

[target.'cfg(target_os = "linux")'.dependencies]
dbus = { path = "../rust-lib/dbus" }
freedesktop-icons = "0.2.1"
gtk = { version = "0.15", features = [ "v3_22" ] }
x11rb = "0.10.1"
zbus = "3.1.0"

[target.'cfg(target_os="macos")'.dependencies]
macos_accessibility_position = { path = "../rust-lib/macos_accessibility_position" }

[build-dependencies]
image = "0.24.3"
