[package]
name = "fig_desktop"
version = "2.2.7"
authors = ["fig developers"]
edition = "2021"
rust-version = "1.57"
description = "Fig adds IDE-style autocomplete to your existing terminal"
homepage = "https://fig.io"
publish = false
default-run = "fig_desktop"

[features]
default = []
console = ["tokio/tracing", "fig_log/console"]

[dependencies]
anyhow = "1.0.62"
base64 = "0.13.0"
bytes = "1.2.1"
camino = { version = "1.0.9", features = ["serde1"] }
cfg-if = "1.0.0"
clap = "3.2.16"
dashmap = "5.3.4"
fig_api_client = { version = "0.1.0", path = "../rust-lib/fig_api_client" }
fig_auth = { path = "../rust-lib/fig_auth" }
fig_install = { path = "../rust-lib/fig_install" }
fig_integrations = { path = "../rust-lib/fig_integrations" }
fig_ipc = { path = "../rust-lib/fig_ipc" }
fig_log = { path = "../rust-lib/fig_log" }
fig_proto = { path = "../rust-lib/fig_proto" }
fig_settings = { path = "../rust-lib/fig_settings" }
fig_telemetry = { path = "../rust-lib/fig_telemetry" }
fig_update = { version = "0.1.0", path = "../rust-lib/fig_update" }
fig_util = { path = "../rust-lib/fig_util" }
fnv = "1.0.7"
hashbrown = "0.12.3"
ibus = { path = "../rust-lib/ibus" }
image = "0.24.3"
moka = "0.9.3"
notify = "5.0.0-pre.15"
once_cell = "1.13.1"
parking_lot = "0.12.1"
percent-encoding = "2.1.0"
regex = "1.6.0"
semver = "1.0.13"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
shellexpand = "2.1.2"
sysinfo = "0.25.2"
system_socket = { path = "../rust-lib/system_socket" }
time = { version = "=0.3.13" }
tokio = { version = "1", features = [ "full" ] }
tracing = "0.1.36"
url = "2.2.2"
which = "4.2.5"
whoami = "1.2.1"
wry = { version = "0.20.1", default-features = false, features = ["tray", "protocol", "devtools", "transparent"] }

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.39.0"
features = [
    "implement",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Networking_WinSock",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Com",
    "Win32_System_Console",
    "Win32_System_Ole",
    "Win32_System_Threading",
    "Win32_System_ProcessStatus",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Accessibility",
]

[target.'cfg(target_os = "linux")'.dependencies]
freedesktop-icons = "0.2.1"
gtk = { version = "0.15", features = [ "v3_22" ] }
ibus = { path = "../rust-lib/ibus" }
x11rb = "0.10.1"
zbus = "2.3.2"

[build-dependencies]
image = "0.24.3"
