version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - sudo dnf update -y
      - sudo dnf install -y python cmake bash zsh unzip zstd xz git jq protobuf
      # Create fish config dir to prevent rustup from failing
      - mkdir -p /root/.config/fish/conf.d
      # Install cargo
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - . $HOME/.cargo/env
      # Install python/node via mise (https://mise.jdx.dev/continuous-integration.html)
      - curl --proto '=https' --tlsv1.2 -sSf https://mise.run | sh
      - export PATH="$HOME/.local/bin:$PATH"
      - mise install
      - eval "$(mise activate bash --shims)"
      # Enable corepack for pnpm
      - corepack enable
      # Disable tests that need fish/shellcheck
      - export CW_BUILD_SKIP_SHELL_TESTS=1
  build:
    commands:
      - python3.11 build-scripts/build.py

artifacts:
  discard-paths: "yes"
  base-directory: "build"
  files:
    - ./*.sha256
    - ./*.tar.gz
    - ./*.tar.xz
    - ./*.tar.zst
    - ./*.zip
