version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      # - . bin/set-up-ubuntu-signing-env.sh "$NSCC_PGP_KEY"
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - . $HOME/.cargo/env
      - sudo apt-get update
      - sudo apt-get install -y clang cmake curl git jq unzip libayatana-appindicator3-dev libgtk-3-dev libibus-1.0-dev libwebkit2gtk-4.1-dev libjavascriptcoregtk-4.1-dev valac protobuf-compiler
      # - n 20
      # - cargo install tauri-cli
      # - pnpm install
  build:
    commands:
      - . build-scripts/rust-init.sh
      - cargo test
      - cargo build --release

artifacts:
  files:
    - target/release/cw_cli
    - target/release/fig_desktop
    - target/release/figterm

  discard-paths: "yes"
