version: 0.2

env:
  shell: bash

run-as: codebuild-user

phases:
  install:
    run-as: root
    commands:
      - dnf update -y
      - dnf install -y python cmake bash zsh unzip zstd xz git jq protobuf
      - dnf swap gnupg2-minimal gnupg2-full
      - mkdir -p /home/codebuild-user
      - chown -R codebuild-user:codebuild-user /home/codebuild-user
      - chmod -R ug+rwx /home/codebuild-user
  pre_build:
    commands:
      - export HOME=/home/codebuild-user
      - export PATH="$HOME/.local/bin:$PATH"
      - mkdir -p "$HOME/.local/bin"
      # Create fish config dir to prevent rustup from failing
      - mkdir -p "$HOME/.config/fish/conf.d"
      # Install cargo
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - . "$HOME/.cargo/env"
      # Install python/node via mise (https://mise.jdx.dev/continuous-integration.html)
      - curl --proto '=https' --tlsv1.2 -sSf https://mise.run | sh
      - mise install
      - eval "$(mise activate bash --shims)"
      # Enable corepack for pnpm
      - corepack enable
  build:
    commands:
      # Disable tests that need fish/shellcheck
      - export CW_BUILD_SKIP_SHELL_TESTS=1
      - python3.11 build-scripts/build.py

artifacts:
  discard-paths: "yes"
  base-directory: "build"
  files:
    # Archives
    - ./*.tar.gz
    - ./*.tar.xz
    - ./*.tar.zst
    - ./*.zip
    # Hashes
    - ./*.sha256
    # Signatures
    - ./*.asc
    - ./*.sig
