version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - sudo apt-get update
      - sudo apt-get install -y clang cmake curl git jq unzip libayatana-appindicator3-dev libgtk-3-dev libibus-1.0-dev libwebkit2gtk-4.1-dev libjavascriptcoregtk-4.1-dev valac protobuf-compiler python3 shellcheck bash zsh fish
      # Create fish config dir to prevent rustup from failing
      - mkdir -p /root/.config/fish/conf.d
      # Install cargo
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - . $HOME/.cargo/env
      - rustup target add x86_64-unknown-linux-gnu
      - rustup target add aarch64-unknown-linux-gnu
      # Install node via rtx
      - curl https://rtx.pub/rtx-latest-linux-amd64 > /usr/bin/rtx
      - chmod +x /usr/bin/rtx
      - eval "$(rtx activate bash)"
      - rtx install
      - corepack enable
      # - cargo install tauri-cli
  build:
    commands:
      - python3 build-scripts/build.py

artifacts:
  files:
    - build/bin/cw-x86_64-unknown-linux-gnu
    - build/bin/cwterm-x86_64-unknown-linux-gnu
    - build/bin/cw-aarch64-unknown-linux-gnu
    - build/bin/cwterm-aarch64-unknown-linux-gnu
    - build/bin/*.sha256


  discard-paths: "yes"
