version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - sudo apt-get update
      - sudo apt-get install -y clang cmake curl git jq unzip libayatana-appindicator3-dev libgtk-3-dev libibus-1.0-dev libwebkit2gtk-4.1-dev libjavascriptcoregtk-4.1-dev valac protobuf-compiler python3 shellcheck bash zsh fish
      # Create fish config dir to prevent rustup from failing
      - mkdir -p /root/.config/fish/conf.d
      # Install cargo
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - . $HOME/.cargo/env
      # Install python/node via mise
      - curl --proto '=https' --tlsv1.2 -sSf https://mise.run | sh
      - export PATH="$HOME/.local/share/mise/shims:$HOME/.local/share/mise/bin:$PATH"
      - mise install
      - corepack enable
      # - cargo install tauri-cli
  build:
    commands:
      - python3.11 build-scripts/build.py

artifacts:
  discard-paths: "yes"
  base-directory: "build"
  files:
    - ./*.sha256
    - ./*.tar.gz
    - ./*.tar.xz
    - ./*.tar.zst
    - ./*.zip
