// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

pub(crate) mod chat_history_constrained {

    #[derive(Debug, Clone)]
    pub(crate) struct ChatHistoryConstrained(pub(crate) std::vec::Vec<crate::model::ChatMessage>);

    impl crate::constrained::Constrained for ChatHistoryConstrained {
        type Unconstrained = crate::unconstrained::chat_history_unconstrained::ChatHistoryUnconstrained;
    }
    impl ::std::convert::From<ChatHistoryConstrained> for ::std::vec::Vec<crate::model::ChatMessage> {
        fn from(v: ChatHistoryConstrained) -> Self {
            v.0
        }
    }
}
pub(crate) mod image_blocks_constrained {

    #[derive(Debug, Clone)]
    pub(crate) struct ImageBlocksConstrained(pub(crate) std::vec::Vec<crate::model::ImageBlock>);

    impl crate::constrained::Constrained for ImageBlocksConstrained {
        type Unconstrained = crate::unconstrained::image_blocks_unconstrained::ImageBlocksUnconstrained;
    }
    impl ::std::convert::From<ImageBlocksConstrained> for ::std::vec::Vec<crate::model::ImageBlock> {
        fn from(v: ImageBlocksConstrained) -> Self {
            v.0
        }
    }
}
pub(crate) mod document_blocks_constrained {

    #[derive(Debug, Clone)]
    pub(crate) struct DocumentBlocksConstrained(pub(crate) std::vec::Vec<crate::model::DocumentBlock>);

    impl crate::constrained::Constrained for DocumentBlocksConstrained {
        type Unconstrained = crate::unconstrained::document_blocks_unconstrained::DocumentBlocksUnconstrained;
    }
    impl ::std::convert::From<DocumentBlocksConstrained> for ::std::vec::Vec<crate::model::DocumentBlock> {
        fn from(v: DocumentBlocksConstrained) -> Self {
            v.0
        }
    }
}
pub(crate) mod tool_results_constrained {

    #[derive(Debug, Clone)]
    pub(crate) struct ToolResultsConstrained(pub(crate) std::vec::Vec<crate::model::ToolResult>);

    impl crate::constrained::Constrained for ToolResultsConstrained {
        type Unconstrained = crate::unconstrained::tool_results_unconstrained::ToolResultsUnconstrained;
    }
    impl ::std::convert::From<ToolResultsConstrained> for ::std::vec::Vec<crate::model::ToolResult> {
        fn from(v: ToolResultsConstrained) -> Self {
            v.0
        }
    }
}
pub(crate) mod relevant_document_list_constrained {

    #[derive(Debug, Clone)]
    pub(crate) struct RelevantDocumentListConstrained(pub(crate) std::vec::Vec<crate::model::RelevantTextDocument>);

    impl crate::constrained::Constrained for RelevantDocumentListConstrained {
        type Unconstrained =
            crate::unconstrained::relevant_document_list_unconstrained::RelevantDocumentListUnconstrained;
    }
    impl ::std::convert::From<RelevantDocumentListConstrained> for ::std::vec::Vec<crate::model::RelevantTextDocument> {
        fn from(v: RelevantDocumentListConstrained) -> Self {
            v.0
        }
    }
}
pub(crate) mod document_symbols_constrained {

    #[derive(Debug, Clone)]
    pub(crate) struct DocumentSymbolsConstrained(pub(crate) std::vec::Vec<crate::model::DocumentSymbol>);

    impl crate::constrained::Constrained for DocumentSymbolsConstrained {
        type Unconstrained = crate::unconstrained::document_symbols_unconstrained::DocumentSymbolsUnconstrained;
    }
    impl ::std::convert::From<DocumentSymbolsConstrained> for ::std::vec::Vec<crate::model::DocumentSymbol> {
        fn from(v: DocumentSymbolsConstrained) -> Self {
            v.0
        }
    }
}

// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

pub(crate) trait Constrained {
    type Unconstrained;
}

#[derive(Debug, Clone)]
#[allow(dead_code)]
pub(crate) enum MaybeConstrained<T: Constrained> {
    Constrained(T),
    Unconstrained(T::Unconstrained),
}
