// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
/// Error type for the `GenerateAssistantResponse` operation.
/// Each variant represents an error that can occur for the `GenerateAssistantResponse` operation.
#[derive(::std::fmt::Debug)]
pub enum GenerateAssistantResponseError {
    /// This exception is thrown when the user does not have sufficient access to perform this
    /// action.
    AccessDeniedException(crate::error::AccessDeniedException),
    /// This exception is thrown when an unexpected error occurred during the processing of a
    /// request.
    InternalServerException(crate::error::InternalServerException),
    /// This exception is thrown when a service quota is exceeded.
    ServiceQuotaExceededException(crate::error::ServiceQuotaExceededException),
    /// This exception is thrown when the service is temporarily unavailable.
    ServiceUnavailableException(crate::error::ServiceUnavailableException),
    /// This exception is thrown when request was denied due to request throttling.
    ThrottlingException(crate::error::ThrottlingException),
    /// This exception is thrown when the input fails to satisfy the constraints specified by the
    /// service.
    ValidationError(crate::error::ValidationError),
    #[allow(missing_docs)] // documentation missing in model
    ValidationException(crate::error::ValidationException),
}
impl ::std::fmt::Display for GenerateAssistantResponseError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match &self {
            GenerateAssistantResponseError::AccessDeniedException(_inner) => _inner.fmt(f),
            GenerateAssistantResponseError::InternalServerException(_inner) => _inner.fmt(f),
            GenerateAssistantResponseError::ServiceQuotaExceededException(_inner) => _inner.fmt(f),
            GenerateAssistantResponseError::ServiceUnavailableException(_inner) => _inner.fmt(f),
            GenerateAssistantResponseError::ThrottlingException(_inner) => _inner.fmt(f),
            GenerateAssistantResponseError::ValidationError(_inner) => _inner.fmt(f),
            GenerateAssistantResponseError::ValidationException(_inner) => _inner.fmt(f),
        }
    }
}
impl GenerateAssistantResponseError {
    /// Returns `true` if the error kind is `GenerateAssistantResponseError::AccessDeniedException`.
    pub fn is_access_denied_exception(&self) -> bool {
        matches!(&self, GenerateAssistantResponseError::AccessDeniedException(_))
    }

    /// Returns `true` if the error kind is
    /// `GenerateAssistantResponseError::InternalServerException`.
    pub fn is_internal_server_exception(&self) -> bool {
        matches!(&self, GenerateAssistantResponseError::InternalServerException(_))
    }

    /// Returns `true` if the error kind is
    /// `GenerateAssistantResponseError::ServiceQuotaExceededException`.
    pub fn is_service_quota_exceeded_exception(&self) -> bool {
        matches!(&self, GenerateAssistantResponseError::ServiceQuotaExceededException(_))
    }

    /// Returns `true` if the error kind is
    /// `GenerateAssistantResponseError::ServiceUnavailableException`.
    pub fn is_service_unavailable_exception(&self) -> bool {
        matches!(&self, GenerateAssistantResponseError::ServiceUnavailableException(_))
    }

    /// Returns `true` if the error kind is `GenerateAssistantResponseError::ThrottlingException`.
    pub fn is_throttling_exception(&self) -> bool {
        matches!(&self, GenerateAssistantResponseError::ThrottlingException(_))
    }

    /// Returns `true` if the error kind is `GenerateAssistantResponseError::ValidationError`.
    pub fn is_validation_error(&self) -> bool {
        matches!(&self, GenerateAssistantResponseError::ValidationError(_))
    }

    /// Returns `true` if the error kind is `GenerateAssistantResponseError::ValidationException`.
    pub fn is_validation_exception(&self) -> bool {
        matches!(&self, GenerateAssistantResponseError::ValidationException(_))
    }

    /// Returns the error name string by matching the correct variant.
    pub fn name(&self) -> &'static str {
        match &self {
            GenerateAssistantResponseError::AccessDeniedException(_inner) => _inner.name(),
            GenerateAssistantResponseError::InternalServerException(_inner) => _inner.name(),
            GenerateAssistantResponseError::ServiceQuotaExceededException(_inner) => _inner.name(),
            GenerateAssistantResponseError::ServiceUnavailableException(_inner) => _inner.name(),
            GenerateAssistantResponseError::ThrottlingException(_inner) => _inner.name(),
            GenerateAssistantResponseError::ValidationError(_inner) => _inner.name(),
            GenerateAssistantResponseError::ValidationException(_inner) => _inner.name(),
        }
    }
}
impl ::std::error::Error for GenerateAssistantResponseError {
    fn source(&self) -> std::option::Option<&(dyn ::std::error::Error + 'static)> {
        match &self {
            GenerateAssistantResponseError::AccessDeniedException(_inner) => Some(_inner),
            GenerateAssistantResponseError::InternalServerException(_inner) => Some(_inner),
            GenerateAssistantResponseError::ServiceQuotaExceededException(_inner) => Some(_inner),
            GenerateAssistantResponseError::ServiceUnavailableException(_inner) => Some(_inner),
            GenerateAssistantResponseError::ThrottlingException(_inner) => Some(_inner),
            GenerateAssistantResponseError::ValidationError(_inner) => Some(_inner),
            GenerateAssistantResponseError::ValidationException(_inner) => Some(_inner),
        }
    }
}
impl ::std::convert::From<crate::error::AccessDeniedException> for crate::error::GenerateAssistantResponseError {
    fn from(variant: crate::error::AccessDeniedException) -> crate::error::GenerateAssistantResponseError {
        Self::AccessDeniedException(variant)
    }
}
impl ::std::convert::From<crate::error::InternalServerException> for crate::error::GenerateAssistantResponseError {
    fn from(variant: crate::error::InternalServerException) -> crate::error::GenerateAssistantResponseError {
        Self::InternalServerException(variant)
    }
}
impl ::std::convert::From<crate::error::ServiceQuotaExceededException>
    for crate::error::GenerateAssistantResponseError
{
    fn from(variant: crate::error::ServiceQuotaExceededException) -> crate::error::GenerateAssistantResponseError {
        Self::ServiceQuotaExceededException(variant)
    }
}
impl ::std::convert::From<crate::error::ServiceUnavailableException> for crate::error::GenerateAssistantResponseError {
    fn from(variant: crate::error::ServiceUnavailableException) -> crate::error::GenerateAssistantResponseError {
        Self::ServiceUnavailableException(variant)
    }
}
impl ::std::convert::From<crate::error::ThrottlingException> for crate::error::GenerateAssistantResponseError {
    fn from(variant: crate::error::ThrottlingException) -> crate::error::GenerateAssistantResponseError {
        Self::ThrottlingException(variant)
    }
}
impl ::std::convert::From<crate::error::ValidationError> for crate::error::GenerateAssistantResponseError {
    fn from(variant: crate::error::ValidationError) -> crate::error::GenerateAssistantResponseError {
        Self::ValidationError(variant)
    }
}
impl ::std::convert::From<crate::error::ValidationException> for crate::error::GenerateAssistantResponseError {
    fn from(variant: crate::error::ValidationException) -> crate::error::GenerateAssistantResponseError {
        Self::ValidationException(variant)
    }
}

/// This exception is thrown when the user does not have sufficient access to perform this action.
#[derive(::std::clone::Clone, ::std::cmp::Eq, ::std::cmp::PartialEq, ::std::fmt::Debug, ::std::hash::Hash)]
pub struct AccessDeniedException {
    #[allow(missing_docs)] // documentation missing in model
    pub message: ::std::option::Option<::std::string::String>,
    /// Reason for AccessDeniedException
    pub reason: ::std::option::Option<crate::model::AccessDeniedExceptionReason>,
}
impl AccessDeniedException {
    /// Reason for AccessDeniedException
    pub fn reason(&self) -> ::std::option::Option<&crate::model::AccessDeniedExceptionReason> {
        self.reason.as_ref()
    }
}
impl AccessDeniedException {
    /// Returns the error message.
    pub fn message(&self) -> ::std::option::Option<&str> {
        self.message.as_deref()
    }

    #[doc(hidden)]
    /// Returns the error name.
    pub fn name(&self) -> &'static str {
        "AccessDeniedException"
    }
}
impl ::std::fmt::Display for AccessDeniedException {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        ::std::write!(f, "AccessDeniedException")?;
        if let ::std::option::Option::Some(inner_1) = &self.message {
            {
                ::std::write!(f, ": {inner_1}")?;
            }
        }
        Ok(())
    }
}
impl ::std::error::Error for AccessDeniedException {}
impl AccessDeniedException {
    /// Creates a new builder-style object to manufacture
    /// [`AccessDeniedException`](crate::error::AccessDeniedException).
    pub fn builder() -> crate::error::access_denied_exception::Builder {
        crate::error::access_denied_exception::Builder::default()
    }
}

/// This exception is thrown when an unexpected error occurred during the processing of a request.
#[derive(::std::clone::Clone, ::std::cmp::Eq, ::std::cmp::PartialEq, ::std::fmt::Debug, ::std::hash::Hash)]
pub struct InternalServerException {
    #[allow(missing_docs)] // documentation missing in model
    pub message: ::std::option::Option<::std::string::String>,
    /// Reason for InternalServerException
    pub reason: ::std::option::Option<crate::model::InternalServerExceptionReason>,
}
impl InternalServerException {
    /// Reason for InternalServerException
    pub fn reason(&self) -> ::std::option::Option<&crate::model::InternalServerExceptionReason> {
        self.reason.as_ref()
    }
}
impl InternalServerException {
    /// Returns `Some(ErrorKind)` if the error is retryable. Otherwise, returns `None`.
    pub fn retryable_error_kind(&self) -> ::aws_smithy_types::retry::ErrorKind {
        ::aws_smithy_types::retry::ErrorKind::ServerError
    }

    /// Returns the error message.
    pub fn message(&self) -> ::std::option::Option<&str> {
        self.message.as_deref()
    }

    #[doc(hidden)]
    /// Returns the error name.
    pub fn name(&self) -> &'static str {
        "InternalServerException"
    }
}
impl ::std::fmt::Display for InternalServerException {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        ::std::write!(f, "InternalServerException")?;
        if let ::std::option::Option::Some(inner_2) = &self.message {
            {
                ::std::write!(f, ": {inner_2}")?;
            }
        }
        Ok(())
    }
}
impl ::std::error::Error for InternalServerException {}
impl InternalServerException {
    /// Creates a new builder-style object to manufacture
    /// [`InternalServerException`](crate::error::InternalServerException).
    pub fn builder() -> crate::error::internal_server_exception::Builder {
        crate::error::internal_server_exception::Builder::default()
    }
}

/// This exception is thrown when a service quota is exceeded.
#[derive(::std::clone::Clone, ::std::cmp::Eq, ::std::cmp::PartialEq, ::std::fmt::Debug, ::std::hash::Hash)]
pub struct ServiceQuotaExceededException {
    #[allow(missing_docs)] // documentation missing in model
    pub message: ::std::option::Option<::std::string::String>,
    /// Reason for ServiceQuotaExceededException
    pub reason: ::std::option::Option<crate::model::ServiceQuotaExceededExceptionReason>,
}
impl ServiceQuotaExceededException {
    /// Reason for ServiceQuotaExceededException
    pub fn reason(&self) -> ::std::option::Option<&crate::model::ServiceQuotaExceededExceptionReason> {
        self.reason.as_ref()
    }
}
impl ServiceQuotaExceededException {
    /// Returns the error message.
    pub fn message(&self) -> ::std::option::Option<&str> {
        self.message.as_deref()
    }

    #[doc(hidden)]
    /// Returns the error name.
    pub fn name(&self) -> &'static str {
        "ServiceQuotaExceededException"
    }
}
impl ::std::fmt::Display for ServiceQuotaExceededException {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        ::std::write!(f, "ServiceQuotaExceededException")?;
        if let ::std::option::Option::Some(inner_3) = &self.message {
            {
                ::std::write!(f, ": {inner_3}")?;
            }
        }
        Ok(())
    }
}
impl ::std::error::Error for ServiceQuotaExceededException {}
impl ServiceQuotaExceededException {
    /// Creates a new builder-style object to manufacture
    /// [`ServiceQuotaExceededException`](crate::error::ServiceQuotaExceededException).
    pub fn builder() -> crate::error::service_quota_exceeded_exception::Builder {
        crate::error::service_quota_exceeded_exception::Builder::default()
    }
}

/// This exception is thrown when the service is temporarily unavailable.
#[derive(::std::clone::Clone, ::std::cmp::Eq, ::std::cmp::PartialEq, ::std::fmt::Debug, ::std::hash::Hash)]
pub struct ServiceUnavailableException {
    #[allow(missing_docs)] // documentation missing in model
    pub message: ::std::option::Option<::std::string::String>,
    /// Reason for ServiceUnavailableException
    pub reason: ::std::option::Option<crate::model::ServiceUnavailableExceptionReason>,
}
impl ServiceUnavailableException {
    /// Reason for ServiceUnavailableException
    pub fn reason(&self) -> ::std::option::Option<&crate::model::ServiceUnavailableExceptionReason> {
        self.reason.as_ref()
    }
}
impl ServiceUnavailableException {
    /// Returns `Some(ErrorKind)` if the error is retryable. Otherwise, returns `None`.
    pub fn retryable_error_kind(&self) -> ::aws_smithy_types::retry::ErrorKind {
        ::aws_smithy_types::retry::ErrorKind::ServerError
    }

    /// Returns the error message.
    pub fn message(&self) -> ::std::option::Option<&str> {
        self.message.as_deref()
    }

    #[doc(hidden)]
    /// Returns the error name.
    pub fn name(&self) -> &'static str {
        "ServiceUnavailableException"
    }
}
impl ::std::fmt::Display for ServiceUnavailableException {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        ::std::write!(f, "ServiceUnavailableException")?;
        if let ::std::option::Option::Some(inner_4) = &self.message {
            {
                ::std::write!(f, ": {inner_4}")?;
            }
        }
        Ok(())
    }
}
impl ::std::error::Error for ServiceUnavailableException {}
impl ServiceUnavailableException {
    /// Creates a new builder-style object to manufacture
    /// [`ServiceUnavailableException`](crate::error::ServiceUnavailableException).
    pub fn builder() -> crate::error::service_unavailable_exception::Builder {
        crate::error::service_unavailable_exception::Builder::default()
    }
}

/// This exception is thrown when request was denied due to request throttling.
#[derive(::std::clone::Clone, ::std::cmp::Eq, ::std::cmp::PartialEq, ::std::fmt::Debug, ::std::hash::Hash)]
pub struct ThrottlingException {
    #[allow(missing_docs)] // documentation missing in model
    pub message: ::std::option::Option<::std::string::String>,
    /// Reason for ThrottlingException
    pub reason: ::std::option::Option<crate::model::ThrottlingExceptionReason>,
    #[allow(missing_docs)] // documentation missing in model
    pub retry_after_milliseconds: ::std::option::Option<i32>,
}
impl ThrottlingException {
    /// Reason for ThrottlingException
    pub fn reason(&self) -> ::std::option::Option<&crate::model::ThrottlingExceptionReason> {
        self.reason.as_ref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn retry_after_milliseconds(&self) -> ::std::option::Option<i32> {
        self.retry_after_milliseconds
    }
}
impl ThrottlingException {
    /// Returns `Some(ErrorKind)` if the error is retryable. Otherwise, returns `None`.
    pub fn retryable_error_kind(&self) -> ::aws_smithy_types::retry::ErrorKind {
        ::aws_smithy_types::retry::ErrorKind::ThrottlingError
    }

    /// Returns the error message.
    pub fn message(&self) -> ::std::option::Option<&str> {
        self.message.as_deref()
    }

    #[doc(hidden)]
    /// Returns the error name.
    pub fn name(&self) -> &'static str {
        "ThrottlingException"
    }
}
impl ::std::fmt::Display for ThrottlingException {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        ::std::write!(f, "ThrottlingException")?;
        if let ::std::option::Option::Some(inner_5) = &self.message {
            {
                ::std::write!(f, ": {inner_5}")?;
            }
        }
        Ok(())
    }
}
impl ::std::error::Error for ThrottlingException {}
impl ThrottlingException {
    /// Creates a new builder-style object to manufacture
    /// [`ThrottlingException`](crate::error::ThrottlingException).
    pub fn builder() -> crate::error::throttling_exception::Builder {
        crate::error::throttling_exception::Builder::default()
    }
}

/// This exception is thrown when the input fails to satisfy the constraints specified by the
/// service.
#[derive(::std::clone::Clone, ::std::cmp::Eq, ::std::cmp::PartialEq, ::std::fmt::Debug, ::std::hash::Hash)]
pub struct ValidationError {
    #[allow(missing_docs)] // documentation missing in model
    pub message: ::std::option::Option<::std::string::String>,
    /// Reason for ValidationException
    pub reason: ::std::option::Option<crate::model::ValidationExceptionReason>,
}
impl ValidationError {
    /// Reason for ValidationException
    pub fn reason(&self) -> ::std::option::Option<&crate::model::ValidationExceptionReason> {
        self.reason.as_ref()
    }
}
impl ValidationError {
    /// Returns the error message.
    pub fn message(&self) -> ::std::option::Option<&str> {
        self.message.as_deref()
    }

    #[doc(hidden)]
    /// Returns the error name.
    pub fn name(&self) -> &'static str {
        "ValidationError"
    }
}
impl ::std::fmt::Display for ValidationError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        ::std::write!(f, "ValidationError")?;
        if let ::std::option::Option::Some(inner_6) = &self.message {
            {
                ::std::write!(f, ": {inner_6}")?;
            }
        }
        Ok(())
    }
}
impl ::std::error::Error for ValidationError {}
impl ValidationError {
    /// Creates a new builder-style object to manufacture
    /// [`ValidationError`](crate::error::ValidationError).
    pub fn builder() -> crate::error::validation_error::Builder {
        crate::error::validation_error::Builder::default()
    }
}

#[allow(missing_docs)] // documentation missing in model
#[derive(::std::clone::Clone, ::std::cmp::Eq, ::std::cmp::PartialEq, ::std::fmt::Debug, ::std::hash::Hash)]
pub struct ValidationException {
    #[allow(missing_docs)] // documentation missing in model
    pub message: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub field_list: ::std::option::Option<::std::vec::Vec<crate::model::ValidationExceptionField>>,
}
impl ValidationException {
    #[allow(missing_docs)] // documentation missing in model
    pub fn field_list(&self) -> ::std::option::Option<&[crate::model::ValidationExceptionField]> {
        self.field_list.as_deref()
    }
}
impl ValidationException {
    /// Returns the error message.
    pub fn message(&self) -> &str {
        &self.message
    }

    #[doc(hidden)]
    /// Returns the error name.
    pub fn name(&self) -> &'static str {
        "ValidationException"
    }
}
impl ::std::fmt::Display for ValidationException {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        ::std::write!(f, "ValidationException")?;
        {
            ::std::write!(f, ": {}", &self.message)?;
        }
        Ok(())
    }
}
impl ::std::error::Error for ValidationException {}
impl ValidationException {
    /// Creates a new builder-style object to manufacture
    /// [`ValidationException`](crate::error::ValidationException).
    pub fn builder() -> crate::error::validation_exception::Builder {
        crate::error::validation_exception::Builder::default()
    }
}

/// Error type for the `ChatResponseStream` operation.
/// Each variant represents an error that can occur for the `ChatResponseStream` operation.
#[derive(::std::fmt::Debug)]
pub enum ChatResponseStreamError {
    /// This exception is thrown when an unexpected error occurred during the processing of a
    /// request.
    InternalServerException(crate::error::InternalServerException),
    /// This exception is thrown when request was denied due to request throttling.
    ThrottlingException(crate::error::ThrottlingException),
    /// This exception is thrown when the input fails to satisfy the constraints specified by the
    /// service.
    ValidationError(crate::error::ValidationError),
    /// This exception is thrown when the service is temporarily unavailable.
    ServiceUnavailableException(crate::error::ServiceUnavailableException),
}
impl ::std::fmt::Display for ChatResponseStreamError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match &self {
            ChatResponseStreamError::InternalServerException(_inner) => _inner.fmt(f),
            ChatResponseStreamError::ThrottlingException(_inner) => _inner.fmt(f),
            ChatResponseStreamError::ValidationError(_inner) => _inner.fmt(f),
            ChatResponseStreamError::ServiceUnavailableException(_inner) => _inner.fmt(f),
        }
    }
}
impl ChatResponseStreamError {
    /// Returns `true` if the error kind is `ChatResponseStreamError::InternalServerException`.
    pub fn is_internal_server_exception(&self) -> bool {
        matches!(&self, ChatResponseStreamError::InternalServerException(_))
    }

    /// Returns `true` if the error kind is `ChatResponseStreamError::ThrottlingException`.
    pub fn is_throttling_exception(&self) -> bool {
        matches!(&self, ChatResponseStreamError::ThrottlingException(_))
    }

    /// Returns `true` if the error kind is `ChatResponseStreamError::ValidationError`.
    pub fn is_validation_error(&self) -> bool {
        matches!(&self, ChatResponseStreamError::ValidationError(_))
    }

    /// Returns `true` if the error kind is `ChatResponseStreamError::ServiceUnavailableException`.
    pub fn is_service_unavailable_exception(&self) -> bool {
        matches!(&self, ChatResponseStreamError::ServiceUnavailableException(_))
    }

    /// Returns the error name string by matching the correct variant.
    pub fn name(&self) -> &'static str {
        match &self {
            ChatResponseStreamError::InternalServerException(_inner) => _inner.name(),
            ChatResponseStreamError::ThrottlingException(_inner) => _inner.name(),
            ChatResponseStreamError::ValidationError(_inner) => _inner.name(),
            ChatResponseStreamError::ServiceUnavailableException(_inner) => _inner.name(),
        }
    }
}
impl ::std::error::Error for ChatResponseStreamError {
    fn source(&self) -> std::option::Option<&(dyn ::std::error::Error + 'static)> {
        match &self {
            ChatResponseStreamError::InternalServerException(_inner) => Some(_inner),
            ChatResponseStreamError::ThrottlingException(_inner) => Some(_inner),
            ChatResponseStreamError::ValidationError(_inner) => Some(_inner),
            ChatResponseStreamError::ServiceUnavailableException(_inner) => Some(_inner),
        }
    }
}
impl ::std::convert::From<crate::error::InternalServerException> for crate::error::ChatResponseStreamError {
    fn from(variant: crate::error::InternalServerException) -> crate::error::ChatResponseStreamError {
        Self::InternalServerException(variant)
    }
}
impl ::std::convert::From<crate::error::ThrottlingException> for crate::error::ChatResponseStreamError {
    fn from(variant: crate::error::ThrottlingException) -> crate::error::ChatResponseStreamError {
        Self::ThrottlingException(variant)
    }
}
impl ::std::convert::From<crate::error::ValidationError> for crate::error::ChatResponseStreamError {
    fn from(variant: crate::error::ValidationError) -> crate::error::ChatResponseStreamError {
        Self::ValidationError(variant)
    }
}
impl ::std::convert::From<crate::error::ServiceUnavailableException> for crate::error::ChatResponseStreamError {
    fn from(variant: crate::error::ServiceUnavailableException) -> crate::error::ChatResponseStreamError {
        Self::ServiceUnavailableException(variant)
    }
}
/// See [`AccessDeniedException`](crate::error::AccessDeniedException).
pub mod access_denied_exception {

    impl ::std::convert::From<Builder> for crate::error::AccessDeniedException {
        fn from(builder: Builder) -> Self {
            builder.build()
        }
    }
    /// A builder for [`AccessDeniedException`](crate::error::AccessDeniedException).
    #[derive(::std::clone::Clone, ::std::default::Default, ::std::fmt::Debug)]
    pub struct Builder {
        pub(crate) message: ::std::option::Option<::std::string::String>,
        pub(crate) reason: ::std::option::Option<crate::model::AccessDeniedExceptionReason>,
    }
    impl Builder {
        #[allow(missing_docs)] // documentation missing in model
        pub fn message(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
            self.message = input;
            self
        }

        /// Reason for AccessDeniedException
        pub fn reason(mut self, input: ::std::option::Option<crate::model::AccessDeniedExceptionReason>) -> Self {
            self.reason = input;
            self
        }

        /// Consumes the builder and constructs a
        /// [`AccessDeniedException`](crate::error::AccessDeniedException).
        pub fn build(self) -> crate::error::AccessDeniedException {
            self.build_enforcing_required_and_enum_traits()
        }

        fn build_enforcing_required_and_enum_traits(self) -> crate::error::AccessDeniedException {
            crate::error::AccessDeniedException {
                message: self.message,
                reason: self.reason,
            }
        }
    }
}
/// See [`InternalServerException`](crate::error::InternalServerException).
pub mod internal_server_exception {

    impl ::std::convert::From<Builder> for crate::error::InternalServerException {
        fn from(builder: Builder) -> Self {
            builder.build()
        }
    }
    /// A builder for [`InternalServerException`](crate::error::InternalServerException).
    #[derive(::std::clone::Clone, ::std::default::Default, ::std::fmt::Debug)]
    pub struct Builder {
        pub(crate) message: ::std::option::Option<::std::string::String>,
        pub(crate) reason: ::std::option::Option<crate::model::InternalServerExceptionReason>,
    }
    impl Builder {
        #[allow(missing_docs)] // documentation missing in model
        pub fn message(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
            self.message = input;
            self
        }

        /// Reason for InternalServerException
        pub fn reason(mut self, input: ::std::option::Option<crate::model::InternalServerExceptionReason>) -> Self {
            self.reason = input;
            self
        }

        /// Consumes the builder and constructs a
        /// [`InternalServerException`](crate::error::InternalServerException).
        pub fn build(self) -> crate::error::InternalServerException {
            self.build_enforcing_required_and_enum_traits()
        }

        fn build_enforcing_required_and_enum_traits(self) -> crate::error::InternalServerException {
            crate::error::InternalServerException {
                message: self.message,
                reason: self.reason,
            }
        }
    }
}
/// See [`ServiceQuotaExceededException`](crate::error::ServiceQuotaExceededException).
pub mod service_quota_exceeded_exception {

    impl ::std::convert::From<Builder> for crate::error::ServiceQuotaExceededException {
        fn from(builder: Builder) -> Self {
            builder.build()
        }
    }
    /// A builder for
    /// [`ServiceQuotaExceededException`](crate::error::ServiceQuotaExceededException).
    #[derive(::std::clone::Clone, ::std::default::Default, ::std::fmt::Debug)]
    pub struct Builder {
        pub(crate) message: ::std::option::Option<::std::string::String>,
        pub(crate) reason: ::std::option::Option<crate::model::ServiceQuotaExceededExceptionReason>,
    }
    impl Builder {
        #[allow(missing_docs)] // documentation missing in model
        pub fn message(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
            self.message = input;
            self
        }

        /// Reason for ServiceQuotaExceededException
        pub fn reason(
            mut self,
            input: ::std::option::Option<crate::model::ServiceQuotaExceededExceptionReason>,
        ) -> Self {
            self.reason = input;
            self
        }

        /// Consumes the builder and constructs a
        /// [`ServiceQuotaExceededException`](crate::error::ServiceQuotaExceededException).
        pub fn build(self) -> crate::error::ServiceQuotaExceededException {
            self.build_enforcing_required_and_enum_traits()
        }

        fn build_enforcing_required_and_enum_traits(self) -> crate::error::ServiceQuotaExceededException {
            crate::error::ServiceQuotaExceededException {
                message: self.message,
                reason: self.reason,
            }
        }
    }
}
/// See [`ServiceUnavailableException`](crate::error::ServiceUnavailableException).
pub mod service_unavailable_exception {

    impl ::std::convert::From<Builder> for crate::error::ServiceUnavailableException {
        fn from(builder: Builder) -> Self {
            builder.build()
        }
    }
    /// A builder for [`ServiceUnavailableException`](crate::error::ServiceUnavailableException).
    #[derive(::std::clone::Clone, ::std::default::Default, ::std::fmt::Debug)]
    pub struct Builder {
        pub(crate) message: ::std::option::Option<::std::string::String>,
        pub(crate) reason: ::std::option::Option<crate::model::ServiceUnavailableExceptionReason>,
    }
    impl Builder {
        #[allow(missing_docs)] // documentation missing in model
        pub fn message(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
            self.message = input;
            self
        }

        /// Reason for ServiceUnavailableException
        pub fn reason(mut self, input: ::std::option::Option<crate::model::ServiceUnavailableExceptionReason>) -> Self {
            self.reason = input;
            self
        }

        /// Consumes the builder and constructs a
        /// [`ServiceUnavailableException`](crate::error::ServiceUnavailableException).
        pub fn build(self) -> crate::error::ServiceUnavailableException {
            self.build_enforcing_required_and_enum_traits()
        }

        fn build_enforcing_required_and_enum_traits(self) -> crate::error::ServiceUnavailableException {
            crate::error::ServiceUnavailableException {
                message: self.message,
                reason: self.reason,
            }
        }
    }
}
/// See [`ThrottlingException`](crate::error::ThrottlingException).
pub mod throttling_exception {

    impl ::std::convert::From<Builder> for crate::error::ThrottlingException {
        fn from(builder: Builder) -> Self {
            builder.build()
        }
    }
    /// A builder for [`ThrottlingException`](crate::error::ThrottlingException).
    #[derive(::std::clone::Clone, ::std::default::Default, ::std::fmt::Debug)]
    pub struct Builder {
        pub(crate) message: ::std::option::Option<::std::string::String>,
        pub(crate) reason: ::std::option::Option<crate::model::ThrottlingExceptionReason>,
        pub(crate) retry_after_milliseconds: ::std::option::Option<i32>,
    }
    impl Builder {
        #[allow(missing_docs)] // documentation missing in model
        pub fn message(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
            self.message = input;
            self
        }

        /// Reason for ThrottlingException
        pub fn reason(mut self, input: ::std::option::Option<crate::model::ThrottlingExceptionReason>) -> Self {
            self.reason = input;
            self
        }

        #[allow(missing_docs)] // documentation missing in model
        pub fn retry_after_milliseconds(mut self, input: ::std::option::Option<i32>) -> Self {
            self.retry_after_milliseconds = input;
            self
        }

        /// Consumes the builder and constructs a
        /// [`ThrottlingException`](crate::error::ThrottlingException).
        pub fn build(self) -> crate::error::ThrottlingException {
            self.build_enforcing_required_and_enum_traits()
        }

        fn build_enforcing_required_and_enum_traits(self) -> crate::error::ThrottlingException {
            crate::error::ThrottlingException {
                message: self.message,
                reason: self.reason,
                retry_after_milliseconds: self.retry_after_milliseconds,
            }
        }
    }
}
/// See [`ValidationError`](crate::error::ValidationError).
pub mod validation_error {

    impl ::std::convert::From<Builder> for crate::error::ValidationError {
        fn from(builder: Builder) -> Self {
            builder.build()
        }
    }
    /// A builder for [`ValidationError`](crate::error::ValidationError).
    #[derive(::std::clone::Clone, ::std::default::Default, ::std::fmt::Debug)]
    pub struct Builder {
        pub(crate) message: ::std::option::Option<::std::string::String>,
        pub(crate) reason: ::std::option::Option<crate::model::ValidationExceptionReason>,
    }
    impl Builder {
        #[allow(missing_docs)] // documentation missing in model
        pub fn message(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
            self.message = input;
            self
        }

        /// Reason for ValidationException
        pub fn reason(mut self, input: ::std::option::Option<crate::model::ValidationExceptionReason>) -> Self {
            self.reason = input;
            self
        }

        /// Consumes the builder and constructs a
        /// [`ValidationError`](crate::error::ValidationError).
        pub fn build(self) -> crate::error::ValidationError {
            self.build_enforcing_required_and_enum_traits()
        }

        fn build_enforcing_required_and_enum_traits(self) -> crate::error::ValidationError {
            crate::error::ValidationError {
                message: self.message,
                reason: self.reason,
            }
        }
    }
}
/// See [`ValidationException`](crate::error::ValidationException).
pub mod validation_exception {

    #[derive(::std::cmp::PartialEq, ::std::fmt::Debug)]
    /// Holds one variant for each of the ways the builder can fail.
    #[allow(clippy::enum_variant_names)]
    pub enum ConstraintViolation {
        /// `message` was not provided but it is required when building `ValidationException`.
        MissingMessage,
    }
    impl ::std::fmt::Display for ConstraintViolation {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            match self {
                ConstraintViolation::MissingMessage => write!(
                    f,
                    "`message` was not provided but it is required when building `ValidationException`"
                ),
            }
        }
    }
    impl ::std::error::Error for ConstraintViolation {}
    impl ::std::convert::TryFrom<Builder> for crate::error::ValidationException {
        type Error = ConstraintViolation;

        fn try_from(builder: Builder) -> ::std::result::Result<Self, Self::Error> {
            builder.build()
        }
    }
    /// A builder for [`ValidationException`](crate::error::ValidationException).
    #[derive(::std::clone::Clone, ::std::default::Default, ::std::fmt::Debug)]
    pub struct Builder {
        pub(crate) message: ::std::option::Option<::std::string::String>,
        pub(crate) field_list: ::std::option::Option<::std::vec::Vec<crate::model::ValidationExceptionField>>,
    }
    impl Builder {
        #[allow(missing_docs)] // documentation missing in model
        pub fn message(mut self, input: ::std::string::String) -> Self {
            self.message = Some(input);
            self
        }

        #[allow(missing_docs)] // documentation missing in model
        pub fn field_list(
            mut self,
            input: ::std::option::Option<::std::vec::Vec<crate::model::ValidationExceptionField>>,
        ) -> Self {
            self.field_list = input;
            self
        }

        /// Consumes the builder and constructs a
        /// [`ValidationException`](crate::error::ValidationException).
        ///
        /// The builder fails to construct a
        /// [`ValidationException`](crate::error::ValidationException) if you do not provide a value
        /// for all non-`Option`al members.
        pub fn build(self) -> Result<crate::error::ValidationException, ConstraintViolation> {
            self.build_enforcing_required_and_enum_traits()
        }

        fn build_enforcing_required_and_enum_traits(
            self,
        ) -> Result<crate::error::ValidationException, ConstraintViolation> {
            Ok(crate::error::ValidationException {
                message: self.message.ok_or(ConstraintViolation::MissingMessage)?,
                field_list: self.field_list,
            })
        }
    }
}
