// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[non_exhaustive]
#[derive(Debug)]
pub struct ChatResponseStreamErrorMarshaller;

impl ChatResponseStreamErrorMarshaller {
    pub fn new() -> Self {
        ChatResponseStreamErrorMarshaller
    }
}
impl ::aws_smithy_eventstream::frame::MarshallMessage for ChatResponseStreamErrorMarshaller {
    type Input = crate::error::ChatResponseStreamError;

    fn marshall(
        &self,
        _input: Self::Input,
    ) -> std::result::Result<::aws_smithy_types::event_stream::Message, ::aws_smithy_eventstream::error::Error> {
        let mut headers = Vec::new();
        headers.push(::aws_smithy_types::event_stream::Header::new(
            ":message-type",
            ::aws_smithy_types::event_stream::HeaderValue::String("exception".into()),
        ));
        let payload = match _input {
            crate::error::ChatResponseStreamError::InternalServerException(inner) => {
                headers.push(::aws_smithy_types::event_stream::Header::new(
                    ":exception-type",
                    ::aws_smithy_types::event_stream::HeaderValue::String("error".into()),
                ));
                headers.push(::aws_smithy_types::event_stream::Header::new(
                    ":content-type",
                    ::aws_smithy_types::event_stream::HeaderValue::String("application/json".into()),
                ));
                crate::protocol_serde::shape_internal_server_exception::ser_internal_server_exception_error(&inner)
                    .map_err(|err| ::aws_smithy_eventstream::error::Error::marshalling(format!("{err}")))?
            },
            crate::error::ChatResponseStreamError::ThrottlingException(inner) => {
                headers.push(::aws_smithy_types::event_stream::Header::new(
                    ":exception-type",
                    ::aws_smithy_types::event_stream::HeaderValue::String("throttlingError".into()),
                ));
                headers.push(::aws_smithy_types::event_stream::Header::new(
                    ":content-type",
                    ::aws_smithy_types::event_stream::HeaderValue::String("application/json".into()),
                ));
                crate::protocol_serde::shape_throttling_exception::ser_throttling_exception_error(&inner)
                    .map_err(|err| ::aws_smithy_eventstream::error::Error::marshalling(format!("{err}")))?
            },
            crate::error::ChatResponseStreamError::ValidationError(inner) => {
                headers.push(::aws_smithy_types::event_stream::Header::new(
                    ":exception-type",
                    ::aws_smithy_types::event_stream::HeaderValue::String("validationError".into()),
                ));
                headers.push(::aws_smithy_types::event_stream::Header::new(
                    ":content-type",
                    ::aws_smithy_types::event_stream::HeaderValue::String("application/json".into()),
                ));
                crate::protocol_serde::shape_validation_error::ser_validation_error_error(&inner)
                    .map_err(|err| ::aws_smithy_eventstream::error::Error::marshalling(format!("{err}")))?
            },
            crate::error::ChatResponseStreamError::ServiceUnavailableException(inner) => {
                headers.push(::aws_smithy_types::event_stream::Header::new(
                    ":exception-type",
                    ::aws_smithy_types::event_stream::HeaderValue::String("serviceUnavailableError".into()),
                ));
                headers.push(::aws_smithy_types::event_stream::Header::new(
                    ":content-type",
                    ::aws_smithy_types::event_stream::HeaderValue::String("application/json".into()),
                ));
                crate::protocol_serde::shape_service_unavailable_exception::ser_service_unavailable_exception_error(
                    &inner,
                )
                .map_err(|err| ::aws_smithy_eventstream::error::Error::marshalling(format!("{err}")))?
            },
        };
        Ok(::aws_smithy_types::event_stream::Message::new_from_parts(
            headers, payload,
        ))
    }
}

#[non_exhaustive]
#[derive(Debug)]
pub struct ChatResponseStreamMarshaller;

impl ChatResponseStreamMarshaller {
    pub fn new() -> Self {
        ChatResponseStreamMarshaller
    }
}
impl ::aws_smithy_eventstream::frame::MarshallMessage for ChatResponseStreamMarshaller {
    type Input = crate::model::ChatResponseStream;

    fn marshall(
        &self,
        input: Self::Input,
    ) -> std::result::Result<::aws_smithy_types::event_stream::Message, ::aws_smithy_eventstream::error::Error> {
        let mut headers = Vec::new();
        headers.push(::aws_smithy_types::event_stream::Header::new(
            ":message-type",
            ::aws_smithy_types::event_stream::HeaderValue::String("event".into()),
        ));
        let payload = match input {
            Self::Input::AssistantResponseEvent(inner) => {
                headers.push(::aws_smithy_types::event_stream::Header::new(
                    ":event-type",
                    ::aws_smithy_types::event_stream::HeaderValue::String("assistantResponseEvent".into()),
                ));
                headers.push(::aws_smithy_types::event_stream::Header::new(
                    ":content-type",
                    ::aws_smithy_types::event_stream::HeaderValue::String("application/json".into()),
                ));
                crate::protocol_serde::shape_chat_response_stream::ser_assistant_response_event_payload(&inner)
                    .map_err(|err| ::aws_smithy_eventstream::error::Error::marshalling(format!("{err}")))?
            },
            Self::Input::ReasoningContentEvent(inner) => {
                headers.push(::aws_smithy_types::event_stream::Header::new(
                    ":event-type",
                    ::aws_smithy_types::event_stream::HeaderValue::String("reasoningContentEvent".into()),
                ));
                headers.push(::aws_smithy_types::event_stream::Header::new(
                    ":content-type",
                    ::aws_smithy_types::event_stream::HeaderValue::String("application/json".into()),
                ));
                crate::protocol_serde::shape_chat_response_stream::ser_reasoning_content_event_payload(&inner)
                    .map_err(|err| ::aws_smithy_eventstream::error::Error::marshalling(format!("{err}")))?
            },
            Self::Input::CodeReferenceEvent(inner) => {
                headers.push(::aws_smithy_types::event_stream::Header::new(
                    ":event-type",
                    ::aws_smithy_types::event_stream::HeaderValue::String("codeReferenceEvent".into()),
                ));
                headers.push(::aws_smithy_types::event_stream::Header::new(
                    ":content-type",
                    ::aws_smithy_types::event_stream::HeaderValue::String("application/json".into()),
                ));
                crate::protocol_serde::shape_chat_response_stream::ser_code_reference_event_payload(&inner)
                    .map_err(|err| ::aws_smithy_eventstream::error::Error::marshalling(format!("{err}")))?
            },
            Self::Input::ToolUseEvent(inner) => {
                headers.push(::aws_smithy_types::event_stream::Header::new(
                    ":event-type",
                    ::aws_smithy_types::event_stream::HeaderValue::String("toolUseEvent".into()),
                ));
                headers.push(::aws_smithy_types::event_stream::Header::new(
                    ":content-type",
                    ::aws_smithy_types::event_stream::HeaderValue::String("application/json".into()),
                ));
                crate::protocol_serde::shape_chat_response_stream::ser_tool_use_event_payload(&inner)
                    .map_err(|err| ::aws_smithy_eventstream::error::Error::marshalling(format!("{err}")))?
            },
            Self::Input::ToolResultEvent(inner) => {
                headers.push(::aws_smithy_types::event_stream::Header::new(
                    ":event-type",
                    ::aws_smithy_types::event_stream::HeaderValue::String("toolResultEvent".into()),
                ));
                headers.push(::aws_smithy_types::event_stream::Header::new(
                    ":content-type",
                    ::aws_smithy_types::event_stream::HeaderValue::String("application/json".into()),
                ));
                crate::protocol_serde::shape_chat_response_stream::ser_tool_result_event_payload(&inner)
                    .map_err(|err| ::aws_smithy_eventstream::error::Error::marshalling(format!("{err}")))?
            },
            Self::Input::MetadataEvent(inner) => {
                headers.push(::aws_smithy_types::event_stream::Header::new(
                    ":event-type",
                    ::aws_smithy_types::event_stream::HeaderValue::String("metadataEvent".into()),
                ));
                headers.push(::aws_smithy_types::event_stream::Header::new(
                    ":content-type",
                    ::aws_smithy_types::event_stream::HeaderValue::String("application/json".into()),
                ));
                crate::protocol_serde::shape_chat_response_stream::ser_metadata_event_payload(&inner)
                    .map_err(|err| ::aws_smithy_eventstream::error::Error::marshalling(format!("{err}")))?
            },
            Self::Input::MeteringEvent(inner) => {
                headers.push(::aws_smithy_types::event_stream::Header::new(
                    ":event-type",
                    ::aws_smithy_types::event_stream::HeaderValue::String("meteringEvent".into()),
                ));
                headers.push(::aws_smithy_types::event_stream::Header::new(
                    ":content-type",
                    ::aws_smithy_types::event_stream::HeaderValue::String("application/json".into()),
                ));
                crate::protocol_serde::shape_chat_response_stream::ser_metering_event_payload(&inner)
                    .map_err(|err| ::aws_smithy_eventstream::error::Error::marshalling(format!("{err}")))?
            },
            Self::Input::ContextUsageEvent(inner) => {
                headers.push(::aws_smithy_types::event_stream::Header::new(
                    ":event-type",
                    ::aws_smithy_types::event_stream::HeaderValue::String("contextUsageEvent".into()),
                ));
                headers.push(::aws_smithy_types::event_stream::Header::new(
                    ":content-type",
                    ::aws_smithy_types::event_stream::HeaderValue::String("application/json".into()),
                ));
                crate::protocol_serde::shape_chat_response_stream::ser_context_usage_event_payload(&inner)
                    .map_err(|err| ::aws_smithy_eventstream::error::Error::marshalling(format!("{err}")))?
            },
            Self::Input::DocumentCitationEvent(inner) => {
                headers.push(::aws_smithy_types::event_stream::Header::new(
                    ":event-type",
                    ::aws_smithy_types::event_stream::HeaderValue::String("documentCitationEvent".into()),
                ));
                headers.push(::aws_smithy_types::event_stream::Header::new(
                    ":content-type",
                    ::aws_smithy_types::event_stream::HeaderValue::String("application/json".into()),
                ));
                crate::protocol_serde::shape_chat_response_stream::ser_document_citation_event_payload(&inner)
                    .map_err(|err| ::aws_smithy_eventstream::error::Error::marshalling(format!("{err}")))?
            },
        };
        Ok(::aws_smithy_types::event_stream::Message::new_from_parts(
            headers, payload,
        ))
    }
}
