// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Structure to represent a new generate assistant response request.
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub struct GenerateAssistantResponseInput {
    /// Structure to represent the current state of a chat conversation.
    pub conversation_state: ::std::option::Option<crate::model::ConversationState>,
    #[allow(missing_docs)] // documentation missing in model
    pub profile_arn: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub agent_mode: ::std::option::Option<::std::string::String>,
    /// Additional model request fields (e.g. thinking, effort) to pass to the model provider.
    /// Validated against the model's schema before merging with server defaults; throws
    /// ValidationException if invalid.
    pub additional_model_request_fields: ::std::option::Option<::aws_smithy_types::Document>,
    /// Optional system prompt from the client. Appended to the server-side system prompt.
    pub system_prompt: ::std::option::Option<::std::string::String>,
}
impl GenerateAssistantResponseInput {
    /// Structure to represent the current state of a chat conversation.
    pub fn conversation_state(&self) -> ::std::option::Option<&crate::model::ConversationState> {
        self.conversation_state.as_ref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn profile_arn(&self) -> ::std::option::Option<&str> {
        self.profile_arn.as_deref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn agent_mode(&self) -> ::std::option::Option<&str> {
        self.agent_mode.as_deref()
    }

    /// Additional model request fields (e.g. thinking, effort) to pass to the model provider.
    /// Validated against the model's schema before merging with server defaults; throws
    /// ValidationException if invalid.
    pub fn additional_model_request_fields(&self) -> ::std::option::Option<&::aws_smithy_types::Document> {
        self.additional_model_request_fields.as_ref()
    }

    /// Optional system prompt from the client. Appended to the server-side system prompt.
    pub fn system_prompt(&self) -> ::std::option::Option<&str> {
        self.system_prompt.as_deref()
    }
}
impl ::std::fmt::Debug for GenerateAssistantResponseInput {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("GenerateAssistantResponseInput");
        formatter.field("conversation_state", &self.conversation_state);
        formatter.field("profile_arn", &self.profile_arn);
        formatter.field("agent_mode", &self.agent_mode);
        formatter.field("additional_model_request_fields", &self.additional_model_request_fields);
        formatter.field("system_prompt", &"*** Sensitive Data Redacted ***");
        formatter.finish()
    }
}
impl crate::constrained::Constrained for crate::input::GenerateAssistantResponseInput {
    type Unconstrained = crate::input::generate_assistant_response_input_internal::Builder;
}
impl GenerateAssistantResponseInput {
    /// Creates a new builder-style object to manufacture
    /// [`GenerateAssistantResponseInput`](crate::input::GenerateAssistantResponseInput).
    pub fn builder() -> crate::input::generate_assistant_response_input::Builder {
        crate::input::generate_assistant_response_input::Builder::default()
    }
}
/// See [`GenerateAssistantResponseInput`](crate::input::GenerateAssistantResponseInput).
pub(crate) mod generate_assistant_response_input_internal {

    #[derive(::std::cmp::PartialEq, ::std::fmt::Debug)]
    /// Holds one variant for each of the ways the builder can fail.
    #[non_exhaustive]
    #[allow(clippy::enum_variant_names)]
    pub(crate) enum ConstraintViolation {
        /// Constraint violation occurred building member `conversation_state` when building
        /// `GenerateAssistantResponseInput`.
        #[doc(hidden)]
        ConversationState(crate::model::conversation_state_internal::ConstraintViolation),
    }
    impl ::std::fmt::Display for ConstraintViolation {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            match self {
                ConstraintViolation::ConversationState(_) => write!(
                    f,
                    "constraint violation occurred building member `conversation_state` when building `GenerateAssistantResponseInput`"
                ),
            }
        }
    }
    impl ::std::error::Error for ConstraintViolation {}
    impl ConstraintViolation {
        pub(crate) fn as_validation_exception_field(
            self,
            path: ::std::string::String,
        ) -> crate::model::ValidationExceptionField {
            match self {
                ConstraintViolation::ConversationState(inner) => {
                    inner.as_validation_exception_field(path + "/conversationState")
                },
            }
        }
    }
    impl ::std::convert::From<ConstraintViolation>
        for ::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection
    {
        fn from(constraint_violation: ConstraintViolation) -> Self {
            let first_validation_exception_field = constraint_violation.as_validation_exception_field("".to_owned());
            let validation_exception = crate::error::ValidationException {
                message: format!(
                    "1 validation error detected. {}",
                    &first_validation_exception_field.message
                ),
                field_list: Some(vec![first_validation_exception_field]),
            };
            Self::ConstraintViolation(
                                crate::protocol_serde::shape_validation_exception::ser_validation_exception_error(&validation_exception)
                                    .expect("validation exceptions should never fail to serialize; please file a bug report under https://github.com/smithy-lang/smithy-rs/issues")
                            )
        }
    }
    impl ::std::convert::From<Builder>
        for crate::constrained::MaybeConstrained<crate::input::GenerateAssistantResponseInput>
    {
        fn from(builder: Builder) -> Self {
            Self::Unconstrained(builder)
        }
    }
    impl ::std::convert::TryFrom<Builder> for crate::input::GenerateAssistantResponseInput {
        type Error = ConstraintViolation;

        fn try_from(builder: Builder) -> ::std::result::Result<Self, Self::Error> {
            builder.build()
        }
    }
    /// A builder for
    /// [`GenerateAssistantResponseInput`](crate::input::GenerateAssistantResponseInput).
    #[derive(::std::clone::Clone, ::std::default::Default)]
    pub(crate) struct Builder {
        pub(crate) conversation_state:
            ::std::option::Option<crate::constrained::MaybeConstrained<crate::model::ConversationState>>,
        pub(crate) profile_arn: ::std::option::Option<::std::string::String>,
        pub(crate) agent_mode: ::std::option::Option<::std::string::String>,
        pub(crate) additional_model_request_fields: ::std::option::Option<::aws_smithy_types::Document>,
        pub(crate) system_prompt: ::std::option::Option<::std::string::String>,
    }
    impl Builder {
        /// Structure to represent the current state of a chat conversation.
        pub(crate) fn set_conversation_state(
            mut self,
            input: Option<
                impl ::std::convert::Into<crate::constrained::MaybeConstrained<crate::model::ConversationState>>,
            >,
        ) -> Self {
            self.conversation_state = input.map(|v| v.into());
            self
        }

        #[allow(missing_docs)] // documentation missing in model
        pub(crate) fn set_profile_arn(
            mut self,
            input: Option<impl ::std::convert::Into<::std::string::String>>,
        ) -> Self {
            self.profile_arn = input.map(|v| v.into());
            self
        }

        #[allow(missing_docs)] // documentation missing in model
        pub(crate) fn set_agent_mode(
            mut self,
            input: Option<impl ::std::convert::Into<::std::string::String>>,
        ) -> Self {
            self.agent_mode = input.map(|v| v.into());
            self
        }

        /// Additional model request fields (e.g. thinking, effort) to pass to the model provider.
        /// Validated against the model's schema before merging with server defaults; throws
        /// ValidationException if invalid.
        pub(crate) fn set_additional_model_request_fields(
            mut self,
            input: Option<impl ::std::convert::Into<::aws_smithy_types::Document>>,
        ) -> Self {
            self.additional_model_request_fields = input.map(|v| v.into());
            self
        }

        /// Optional system prompt from the client. Appended to the server-side system prompt.
        pub(crate) fn set_system_prompt(
            mut self,
            input: Option<impl ::std::convert::Into<::std::string::String>>,
        ) -> Self {
            self.system_prompt = input.map(|v| v.into());
            self
        }

        /// Consumes the builder and constructs a
        /// [`GenerateAssistantResponseInput`](crate::input::GenerateAssistantResponseInput).
        ///
        /// The builder fails to construct a
        /// [`GenerateAssistantResponseInput`](crate::input::GenerateAssistantResponseInput) if a
        /// [`ConstraintViolation`] occurs.
        pub fn build(self) -> Result<crate::input::GenerateAssistantResponseInput, ConstraintViolation> {
            self.build_enforcing_all_constraints()
        }

        fn build_enforcing_all_constraints(
            self,
        ) -> Result<crate::input::GenerateAssistantResponseInput, ConstraintViolation> {
            Ok(crate::input::GenerateAssistantResponseInput {
                conversation_state: self
                    .conversation_state
                    .map(|v| match v {
                        crate::constrained::MaybeConstrained::Constrained(x) => Ok(x),
                        crate::constrained::MaybeConstrained::Unconstrained(x) => x.try_into(),
                    })
                    .map(|res| res.map_err(ConstraintViolation::ConversationState))
                    .transpose()?,
                profile_arn: self.profile_arn,
                agent_mode: self.agent_mode,
                additional_model_request_fields: self.additional_model_request_fields,
                system_prompt: self.system_prompt,
            })
        }
    }
    impl ::std::fmt::Debug for Builder {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            let mut formatter = f.debug_struct("Builder");
            formatter.field("conversation_state", &self.conversation_state);
            formatter.field("profile_arn", &self.profile_arn);
            formatter.field("agent_mode", &self.agent_mode);
            formatter.field("additional_model_request_fields", &self.additional_model_request_fields);
            formatter.field("system_prompt", &"*** Sensitive Data Redacted ***");
            formatter.finish()
        }
    }
}
/// See [`GenerateAssistantResponseInput`](crate::input::GenerateAssistantResponseInput).
pub mod generate_assistant_response_input {

    impl ::std::convert::From<Builder> for crate::input::GenerateAssistantResponseInput {
        fn from(builder: Builder) -> Self {
            builder.build()
        }
    }
    /// A builder for
    /// [`GenerateAssistantResponseInput`](crate::input::GenerateAssistantResponseInput).
    #[derive(::std::clone::Clone, ::std::default::Default)]
    pub struct Builder {
        pub(crate) conversation_state: ::std::option::Option<crate::model::ConversationState>,
        pub(crate) profile_arn: ::std::option::Option<::std::string::String>,
        pub(crate) agent_mode: ::std::option::Option<::std::string::String>,
        pub(crate) additional_model_request_fields: ::std::option::Option<::aws_smithy_types::Document>,
        pub(crate) system_prompt: ::std::option::Option<::std::string::String>,
    }
    impl Builder {
        /// Structure to represent the current state of a chat conversation.
        pub fn conversation_state(mut self, input: ::std::option::Option<crate::model::ConversationState>) -> Self {
            self.conversation_state = input;
            self
        }

        #[allow(missing_docs)] // documentation missing in model
        pub fn profile_arn(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
            self.profile_arn = input;
            self
        }

        #[allow(missing_docs)] // documentation missing in model
        pub fn agent_mode(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
            self.agent_mode = input;
            self
        }

        /// Additional model request fields (e.g. thinking, effort) to pass to the model provider.
        /// Validated against the model's schema before merging with server defaults; throws
        /// ValidationException if invalid.
        pub fn additional_model_request_fields(
            mut self,
            input: ::std::option::Option<::aws_smithy_types::Document>,
        ) -> Self {
            self.additional_model_request_fields = input;
            self
        }

        /// Optional system prompt from the client. Appended to the server-side system prompt.
        pub fn system_prompt(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
            self.system_prompt = input;
            self
        }

        /// Consumes the builder and constructs a
        /// [`GenerateAssistantResponseInput`](crate::input::GenerateAssistantResponseInput).
        pub fn build(self) -> crate::input::GenerateAssistantResponseInput {
            self.build_enforcing_required_and_enum_traits()
        }

        fn build_enforcing_required_and_enum_traits(self) -> crate::input::GenerateAssistantResponseInput {
            crate::input::GenerateAssistantResponseInput {
                conversation_state: self.conversation_state,
                profile_arn: self.profile_arn,
                agent_mode: self.agent_mode,
                additional_model_request_fields: self.additional_model_request_fields,
                system_prompt: self.system_prompt,
            }
        }
    }
}
