// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// API to generate assistant response.
pub struct GenerateAssistantResponse;

impl ::aws_smithy_http_server::operation::OperationShape for GenerateAssistantResponse {
    type Error = crate::error::GenerateAssistantResponseError;
    type Input = crate::input::GenerateAssistantResponseInput;
    type Output = crate::output::GenerateAssistantResponseOutput;

    const ID: ::aws_smithy_http_server::shape_id::ShapeId = ::aws_smithy_http_server::shape_id::ShapeId::new(
        "com.amazon.kiro.runtimeservice#GenerateAssistantResponse",
        "com.amazon.kiro.runtimeservice",
        "GenerateAssistantResponse",
    );
}

impl ::aws_smithy_http_server::instrumentation::sensitivity::Sensitivity for GenerateAssistantResponse {
    type RequestFmt = ::aws_smithy_http_server::instrumentation::sensitivity::DefaultRequestFmt;
    type ResponseFmt = ::aws_smithy_http_server::instrumentation::sensitivity::DefaultResponseFmt;

    fn request_fmt() -> Self::RequestFmt {
        ::aws_smithy_http_server::instrumentation::sensitivity::RequestFmt::new()
    }

    fn response_fmt() -> Self::ResponseFmt {
        ::aws_smithy_http_server::instrumentation::sensitivity::ResponseFmt::new()
    }
}
