// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
::pin_project_lite::pin_project! {
    /// A [`Future`](std::future::Future) aggregating the body bytes of a [`Request`] and constructing the
    /// [`GenerateAssistantResponseInput`](crate::input::GenerateAssistantResponseInput) using modelled bindings.
    pub struct GenerateAssistantResponseInputFuture {
        inner: std::pin::Pin<Box<dyn std::future::Future<Output = Result<crate::input::GenerateAssistantResponseInput, ::aws_smithy_http_server::protocol::aws_json::runtime_error::RuntimeError>> + Send>>
    }
}

impl std::future::Future for GenerateAssistantResponseInputFuture {
    type Output = Result<
        crate::input::GenerateAssistantResponseInput,
        ::aws_smithy_http_server::protocol::aws_json::runtime_error::RuntimeError,
    >;

    fn poll(self: std::pin::Pin<&mut Self>, cx: &mut std::task::Context<'_>) -> std::task::Poll<Self::Output> {
        let this = self.project();
        this.inner.as_mut().poll(cx)
    }
}

impl<B> ::aws_smithy_http_server::request::FromRequest<::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0, B>
    for crate::input::GenerateAssistantResponseInput
where
    B: ::aws_smithy_http_server::body::HttpBody + Send,
    B: 'static,
    B::Data: Send,
    ::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection:
        From<<B as ::aws_smithy_http_server::body::HttpBody>::Error>,
{
    type Future = GenerateAssistantResponseInputFuture;
    type Rejection = ::aws_smithy_http_server::protocol::aws_json::runtime_error::RuntimeError;

    fn from_request(request: ::http_1x::Request<B>) -> Self::Future {
        let fut = async move {
            if !::aws_smithy_http_server::protocol::accept_header_classifier(
                request.headers(),
                &crate::mimes::CONTENT_TYPE_APPLICATION_X_AMZ_JSON_1_0,
            ) {
                return Err(::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection::NotAcceptable);
            }
            crate::protocol_serde::shape_generate_assistant_response::de_generate_assistant_response_http_request(
                request,
            )
            .await
        };
        use ::futures_util::future::TryFutureExt;
        let fut = fut.map_err(
            |e: ::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection| {
                ::tracing::debug!(error = %e, "failed to deserialize request");
                ::aws_smithy_http_server::protocol::aws_json::runtime_error::RuntimeError::from(e)
            },
        );
        GenerateAssistantResponseInputFuture { inner: Box::pin(fut) }
    }
}
impl ::aws_smithy_http_server::response::IntoResponse<::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0>
    for crate::output::GenerateAssistantResponseOutput
{
    fn into_response(self) -> ::aws_smithy_http_server::response::Response {
        match crate::protocol_serde::shape_generate_assistant_response::ser_generate_assistant_response_http_response(
            self,
        ) {
            Ok(response) => response,
            Err(e) => {
                ::tracing::error!(error = %e, "failed to serialize response");
                ::aws_smithy_http_server::response::IntoResponse::<
                    ::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0,
                >::into_response(
                    ::aws_smithy_http_server::protocol::aws_json::runtime_error::RuntimeError::from(e)
                )
            },
        }
    }
}
impl ::aws_smithy_http_server::response::IntoResponse<::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0>
    for crate::error::GenerateAssistantResponseError
{
    fn into_response(self) -> ::aws_smithy_http_server::response::Response {
        match crate::protocol_serde::shape_generate_assistant_response::ser_generate_assistant_response_http_error(
            &self,
        ) {
            Ok(mut response) => {
                response
                    .extensions_mut()
                    .insert(::aws_smithy_http_server::extension::ModeledErrorExtension::new(
                        self.name(),
                    ));
                response
            },
            Err(e) => {
                ::tracing::error!(error = %e, "failed to serialize response");
                ::aws_smithy_http_server::response::IntoResponse::<
                    ::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0,
                >::into_response(
                    ::aws_smithy_http_server::protocol::aws_json::runtime_error::RuntimeError::from(e)
                )
            },
        }
    }
}
