// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Structure to represent generate assistant response response.
#[derive(::std::fmt::Debug)]
pub struct GenerateAssistantResponseOutput {
    /// Streaming events from UniDirectional Streaming Conversational APIs.
    pub generate_assistant_response_response: ::aws_smithy_http::event_stream::EventStreamSender<
        crate::model::ChatResponseStream,
        crate::error::ChatResponseStreamError,
    >,
}
impl GenerateAssistantResponseOutput {
    /// Streaming events from UniDirectional Streaming Conversational APIs.
    pub fn generate_assistant_response_response(
        &self,
    ) -> &::aws_smithy_http::event_stream::EventStreamSender<
        crate::model::ChatResponseStream,
        crate::error::ChatResponseStreamError,
    > {
        &self.generate_assistant_response_response
    }
}
impl GenerateAssistantResponseOutput {
    /// Creates a new builder-style object to manufacture
    /// [`GenerateAssistantResponseOutput`](crate::output::GenerateAssistantResponseOutput).
    pub fn builder() -> crate::output::generate_assistant_response_output::Builder {
        crate::output::generate_assistant_response_output::Builder::default()
    }
}
/// See [`GenerateAssistantResponseOutput`](crate::output::GenerateAssistantResponseOutput).
pub mod generate_assistant_response_output {

    #[derive(::std::cmp::PartialEq, ::std::fmt::Debug)]
    /// Holds one variant for each of the ways the builder can fail.
    #[allow(clippy::enum_variant_names)]
    pub enum ConstraintViolation {
        /// `generate_assistant_response_response` was not provided but it is required when building
        /// `GenerateAssistantResponseOutput`.
        MissingGenerateAssistantResponseResponse,
    }
    impl ::std::fmt::Display for ConstraintViolation {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            match self {
                ConstraintViolation::MissingGenerateAssistantResponseResponse => write!(
                    f,
                    "`generate_assistant_response_response` was not provided but it is required when building `GenerateAssistantResponseOutput`"
                ),
            }
        }
    }
    impl ::std::error::Error for ConstraintViolation {}
    impl ::std::convert::TryFrom<Builder> for crate::output::GenerateAssistantResponseOutput {
        type Error = ConstraintViolation;

        fn try_from(builder: Builder) -> ::std::result::Result<Self, Self::Error> {
            builder.build()
        }
    }
    /// A builder for
    /// [`GenerateAssistantResponseOutput`](crate::output::GenerateAssistantResponseOutput).
    #[derive(::std::default::Default, ::std::fmt::Debug)]
    pub struct Builder {
        pub(crate) generate_assistant_response_response: ::std::option::Option<
            ::aws_smithy_http::event_stream::EventStreamSender<
                crate::model::ChatResponseStream,
                crate::error::ChatResponseStreamError,
            >,
        >,
    }
    impl Builder {
        /// Streaming events from UniDirectional Streaming Conversational APIs.
        pub fn generate_assistant_response_response(
            mut self,
            input: ::aws_smithy_http::event_stream::EventStreamSender<
                crate::model::ChatResponseStream,
                crate::error::ChatResponseStreamError,
            >,
        ) -> Self {
            self.generate_assistant_response_response = Some(input);
            self
        }

        /// Consumes the builder and constructs a
        /// [`GenerateAssistantResponseOutput`](crate::output::GenerateAssistantResponseOutput).
        ///
        /// The builder fails to construct a
        /// [`GenerateAssistantResponseOutput`](crate::output::GenerateAssistantResponseOutput) if
        /// you do not provide a value for all non-`Option`al members.
        pub fn build(self) -> Result<crate::output::GenerateAssistantResponseOutput, ConstraintViolation> {
            self.build_enforcing_required_and_enum_traits()
        }

        fn build_enforcing_required_and_enum_traits(
            self,
        ) -> Result<crate::output::GenerateAssistantResponseOutput, ConstraintViolation> {
            Ok(crate::output::GenerateAssistantResponseOutput {
                generate_assistant_response_response: self
                    .generate_assistant_response_response
                    .ok_or(ConstraintViolation::MissingGenerateAssistantResponseResponse)?,
            })
        }
    }
}
