// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub(crate) mod shape_generate_assistant_response;

pub(crate) mod shape_access_denied_exception;

pub(crate) fn or_empty_doc(data: &[u8]) -> &[u8] {
    if data.is_empty() { b"{}" } else { data }
}

pub(crate) mod shape_internal_server_exception;

pub(crate) mod shape_service_quota_exceeded_exception;

pub(crate) mod shape_service_unavailable_exception;

pub(crate) mod shape_throttling_exception;

pub(crate) mod shape_validation_error;

pub(crate) mod shape_validation_exception;

pub(crate) mod shape_chat_response_stream;

pub(crate) mod shape_conversation_state;

pub(crate) mod shape_assistant_response_event;

pub(crate) mod shape_chat_history;

pub(crate) mod shape_chat_message;

pub(crate) mod shape_code_reference_event;

pub(crate) mod shape_context_usage_event;

pub(crate) mod shape_document_citation_event;

pub(crate) mod shape_metadata_event;

pub(crate) mod shape_metering_event;

pub(crate) mod shape_reasoning_content_event;

pub(crate) mod shape_tool_result_event;

pub(crate) mod shape_tool_use_event;

pub(crate) mod shape_validation_exception_field;

pub(crate) mod shape_assistant_response_message;

pub(crate) mod shape_document_citation_location;

pub(crate) mod shape_document_citation_source_content;

pub(crate) mod shape_reference;

pub(crate) mod shape_stop_details;

pub(crate) mod shape_token_usage;

pub(crate) mod shape_tool_result;

pub(crate) mod shape_user_input_message;

pub(crate) mod shape_document_blocks;

pub(crate) mod shape_document_citation_search_result_span;

pub(crate) mod shape_document_citation_span;

pub(crate) mod shape_document_citation_web_location;

pub(crate) mod shape_image_blocks;

pub(crate) mod shape_reasoning_content;

pub(crate) mod shape_refusal_details;

pub(crate) mod shape_span;

pub(crate) mod shape_tool_result_content_block;

pub(crate) mod shape_tool_uses;

pub(crate) mod shape_user_input_message_context;

pub(crate) mod shape_additional_content_list;

pub(crate) mod shape_document_block;

pub(crate) mod shape_editor_state;

pub(crate) mod shape_env_state;

pub(crate) mod shape_image_block;

pub(crate) mod shape_reasoning_text;

pub(crate) mod shape_tool_results;

pub(crate) mod shape_tool_use;

pub(crate) mod shape_tools;

pub(crate) mod shape_additional_content_entry;

pub(crate) mod shape_cursor_state;

pub(crate) mod shape_document_source;

pub(crate) mod shape_environment_variables;

pub(crate) mod shape_image_source;

pub(crate) mod shape_relevant_document_list;

pub(crate) mod shape_text_document;

pub(crate) mod shape_tool;

pub(crate) mod shape_workspace_folder_list;

pub(crate) mod shape_document_symbols;

pub(crate) mod shape_environment_variable;

pub(crate) mod shape_position;

pub(crate) mod shape_programming_language;

pub(crate) mod shape_range;

pub(crate) mod shape_relevant_text_document;

pub(crate) mod shape_tool_result_content;

pub(crate) mod shape_tool_specification;

pub(crate) mod shape_document_symbol;

pub(crate) mod shape_tool_input_schema;
