// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

impl crate::constrained::Constrained for crate::model::ChatMessage {
    type Unconstrained = crate::unconstrained::chat_message_unconstrained::ChatMessageUnconstrained;
}

impl From<crate::unconstrained::chat_message_unconstrained::ChatMessageUnconstrained>
    for crate::constrained::MaybeConstrained<crate::model::ChatMessage>
{
    fn from(value: crate::unconstrained::chat_message_unconstrained::ChatMessageUnconstrained) -> Self {
        Self::Unconstrained(value)
    }
}

pub(crate) mod chat_history_unconstrained {

    #[derive(Debug, Clone)]
    pub(crate) struct ChatHistoryUnconstrained(
        pub(crate) std::vec::Vec<crate::unconstrained::chat_message_unconstrained::ChatMessageUnconstrained>,
    );

    impl From<ChatHistoryUnconstrained>
        for crate::constrained::MaybeConstrained<crate::constrained::chat_history_constrained::ChatHistoryConstrained>
    {
        fn from(value: ChatHistoryUnconstrained) -> Self {
            Self::Unconstrained(value)
        }
    }
    impl std::convert::TryFrom<ChatHistoryUnconstrained>
        for crate::constrained::chat_history_constrained::ChatHistoryConstrained
    {
        type Error = crate::model::chat_history_internal::ConstraintViolation;

        fn try_from(value: ChatHistoryUnconstrained) -> std::result::Result<Self, Self::Error> {
            let res: ::std::result::Result<
                ::std::vec::Vec<crate::model::ChatMessage>,
                (usize, crate::model::chat_message_internal::ConstraintViolation),
            > = value
                .0
                .into_iter()
                .enumerate()
                .map(|(idx, inner)| inner.try_into().map_err(|inner_violation| (idx, inner_violation)))
                .collect();
            let inner = res.map_err(|(idx, inner_violation)| Self::Error::Member(idx, inner_violation))?;
            Ok(Self(inner))
        }
    }
}
pub(crate) mod chat_message_unconstrained {

    #[allow(clippy::enum_variant_names)]
    #[derive(Debug, Clone)]
    pub(crate) enum ChatMessageUnconstrained {
        AssistantResponseMessage(crate::model::AssistantResponseMessage),
        UserInputMessage(crate::model::user_input_message_internal::Builder),
    }
    impl ::std::convert::TryFrom<ChatMessageUnconstrained> for crate::model::ChatMessage {
        type Error = crate::model::chat_message_internal::ConstraintViolation;

        fn try_from(value: ChatMessageUnconstrained) -> ::std::result::Result<Self, Self::Error> {
            Ok(
        match value {
            crate::unconstrained::chat_message_unconstrained::ChatMessageUnconstrained::AssistantResponseMessage(unconstrained) => Self::AssistantResponseMessage(
                unconstrained
            ),
            crate::unconstrained::chat_message_unconstrained::ChatMessageUnconstrained::UserInputMessage(unconstrained) => Self::UserInputMessage(
                unconstrained
                                        .try_into()


                                        .map_err(Self::Error::UserInputMessage)?
            ),
        }
    )
        }
    }
}
pub(crate) mod image_blocks_unconstrained {

    #[derive(Debug, Clone)]
    pub(crate) struct ImageBlocksUnconstrained(pub(crate) std::vec::Vec<crate::model::image_block_internal::Builder>);

    impl From<ImageBlocksUnconstrained>
        for crate::constrained::MaybeConstrained<crate::constrained::image_blocks_constrained::ImageBlocksConstrained>
    {
        fn from(value: ImageBlocksUnconstrained) -> Self {
            Self::Unconstrained(value)
        }
    }
    impl std::convert::TryFrom<ImageBlocksUnconstrained>
        for crate::constrained::image_blocks_constrained::ImageBlocksConstrained
    {
        type Error = crate::model::image_blocks_internal::ConstraintViolation;

        fn try_from(value: ImageBlocksUnconstrained) -> std::result::Result<Self, Self::Error> {
            let res: ::std::result::Result<
                ::std::vec::Vec<crate::model::ImageBlock>,
                (usize, crate::model::image_block_internal::ConstraintViolation),
            > = value
                .0
                .into_iter()
                .enumerate()
                .map(|(idx, inner)| inner.try_into().map_err(|inner_violation| (idx, inner_violation)))
                .collect();
            let inner = res.map_err(|(idx, inner_violation)| Self::Error::Member(idx, inner_violation))?;
            Ok(Self(inner))
        }
    }
}
pub(crate) mod document_blocks_unconstrained {

    #[derive(Debug, Clone)]
    pub(crate) struct DocumentBlocksUnconstrained(
        pub(crate) std::vec::Vec<crate::model::document_block_internal::Builder>,
    );

    impl From<DocumentBlocksUnconstrained>
        for crate::constrained::MaybeConstrained<
            crate::constrained::document_blocks_constrained::DocumentBlocksConstrained,
        >
    {
        fn from(value: DocumentBlocksUnconstrained) -> Self {
            Self::Unconstrained(value)
        }
    }
    impl std::convert::TryFrom<DocumentBlocksUnconstrained>
        for crate::constrained::document_blocks_constrained::DocumentBlocksConstrained
    {
        type Error = crate::model::document_blocks_internal::ConstraintViolation;

        fn try_from(value: DocumentBlocksUnconstrained) -> std::result::Result<Self, Self::Error> {
            let res: ::std::result::Result<
                ::std::vec::Vec<crate::model::DocumentBlock>,
                (usize, crate::model::document_block_internal::ConstraintViolation),
            > = value
                .0
                .into_iter()
                .enumerate()
                .map(|(idx, inner)| inner.try_into().map_err(|inner_violation| (idx, inner_violation)))
                .collect();
            let inner = res.map_err(|(idx, inner_violation)| Self::Error::Member(idx, inner_violation))?;
            Ok(Self(inner))
        }
    }
}
pub(crate) mod tool_results_unconstrained {

    #[derive(Debug, Clone)]
    pub(crate) struct ToolResultsUnconstrained(pub(crate) std::vec::Vec<crate::model::tool_result_internal::Builder>);

    impl From<ToolResultsUnconstrained>
        for crate::constrained::MaybeConstrained<crate::constrained::tool_results_constrained::ToolResultsConstrained>
    {
        fn from(value: ToolResultsUnconstrained) -> Self {
            Self::Unconstrained(value)
        }
    }
    impl std::convert::TryFrom<ToolResultsUnconstrained>
        for crate::constrained::tool_results_constrained::ToolResultsConstrained
    {
        type Error = crate::model::tool_results_internal::ConstraintViolation;

        fn try_from(value: ToolResultsUnconstrained) -> std::result::Result<Self, Self::Error> {
            let res: ::std::result::Result<
                ::std::vec::Vec<crate::model::ToolResult>,
                (usize, crate::model::tool_result_internal::ConstraintViolation),
            > = value
                .0
                .into_iter()
                .enumerate()
                .map(|(idx, inner)| inner.try_into().map_err(|inner_violation| (idx, inner_violation)))
                .collect();
            let inner = res.map_err(|(idx, inner_violation)| Self::Error::Member(idx, inner_violation))?;
            Ok(Self(inner))
        }
    }
}
pub(crate) mod relevant_document_list_unconstrained {

    #[derive(Debug, Clone)]
    pub(crate) struct RelevantDocumentListUnconstrained(
        pub(crate) std::vec::Vec<crate::model::relevant_text_document_internal::Builder>,
    );

    impl From<RelevantDocumentListUnconstrained>
        for crate::constrained::MaybeConstrained<
            crate::constrained::relevant_document_list_constrained::RelevantDocumentListConstrained,
        >
    {
        fn from(value: RelevantDocumentListUnconstrained) -> Self {
            Self::Unconstrained(value)
        }
    }
    impl std::convert::TryFrom<RelevantDocumentListUnconstrained>
        for crate::constrained::relevant_document_list_constrained::RelevantDocumentListConstrained
    {
        type Error = crate::model::relevant_document_list_internal::ConstraintViolation;

        fn try_from(value: RelevantDocumentListUnconstrained) -> std::result::Result<Self, Self::Error> {
            let res: ::std::result::Result<
                ::std::vec::Vec<crate::model::RelevantTextDocument>,
                (
                    usize,
                    crate::model::relevant_text_document_internal::ConstraintViolation,
                ),
            > = value
                .0
                .into_iter()
                .enumerate()
                .map(|(idx, inner)| inner.try_into().map_err(|inner_violation| (idx, inner_violation)))
                .collect();
            let inner = res.map_err(|(idx, inner_violation)| Self::Error::Member(idx, inner_violation))?;
            Ok(Self(inner))
        }
    }
}
pub(crate) mod document_symbols_unconstrained {

    #[derive(Debug, Clone)]
    pub(crate) struct DocumentSymbolsUnconstrained(
        pub(crate) std::vec::Vec<crate::model::document_symbol_internal::Builder>,
    );

    impl From<DocumentSymbolsUnconstrained>
        for crate::constrained::MaybeConstrained<
            crate::constrained::document_symbols_constrained::DocumentSymbolsConstrained,
        >
    {
        fn from(value: DocumentSymbolsUnconstrained) -> Self {
            Self::Unconstrained(value)
        }
    }
    impl std::convert::TryFrom<DocumentSymbolsUnconstrained>
        for crate::constrained::document_symbols_constrained::DocumentSymbolsConstrained
    {
        type Error = crate::model::document_symbols_internal::ConstraintViolation;

        fn try_from(value: DocumentSymbolsUnconstrained) -> std::result::Result<Self, Self::Error> {
            let res: ::std::result::Result<
                ::std::vec::Vec<crate::model::DocumentSymbol>,
                (usize, crate::model::document_symbol_internal::ConstraintViolation),
            > = value
                .0
                .into_iter()
                .enumerate()
                .map(|(idx, inner)| inner.try_into().map_err(|inner_violation| (idx, inner_violation)))
                .collect();
            let inner = res.map_err(|(idx, inner_violation)| Self::Error::Member(idx, inner_violation))?;
            Ok(Self(inner))
        }
    }
}
