[package]
name = "fig-ipc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
bytes = "1.1.0"
fig-proto = { path = "../fig-proto" }
prost = "0.9.0"
tokio = { version = "1.17.0", features = ["fs", "time", "io-util", "net"] }
tracing = "0.1.31"
thiserror = "1.0.30"

[target.'cfg(unix)'.dependencies]
nix = "0.23.1"