[package]
name = "fig-ipc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
bytes = "1.1.0"
fig-proto = { path = "../fig-proto" }
prost = "0.9.0"
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["fs", "time", "io-util", "net"] }
tracing = "0.1.31"
whoami = "1.2.1"