[package]
name = "fig-settings"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.55"
directories = "4.0.1"
futures = { version = "0.3.21", features = ["executor"] } 
fig-auth = { path = "../fig-auth" }
reqwest = { version = "0.11.9", features = ["json"] }
serde = "1.0.136"
serde_json = "1.0.79"
tokio = { version = "1.16.1", features = ["full"] }
