[package]
name = "viu"
version = "1.4.0"
authors = ["Atanas Yankov <atanas.yankov98@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/atanunq/viu"
description = "View images right from the terminal."
categories = ["command-line-utilities"]
keywords = ["terminal", "image", "gif"]
exclude = ["/img", "/.github"]

[dependencies]
anes = "0.1.6"
crossterm = "0.23"
ctrlc = { version = "3.1", features = ["termination"] }
image = "0.24"
viuer = "0.6"

[features]
default = []
sixel = ["viuer/sixel"]
