[package]
name = "fig_util"
version = "0.1.0"
authors = ["fig developers"]
edition = "2021"
description = "A layer between the terminal and shell."
homepage = "https://fig.io"
publish = false

[dependencies]
cfg-if = "1.0.0"
clap = { version = "3.2.16", features = ["derive"] }
dirs = "4.0.0"
once_cell = "1.13.0"
serde = { version = "1.0.141", features = ["derive"] }
sha2 = "0.10.2"
thiserror = "1.0.32"
tokio = { version = "1", features = ["process"] }
whoami = "1.2.1"

[target.'cfg(target_os = "linux")'.dependencies]
wsl = "0.1.0"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.38.0", features = [
    "Win32_Foundation",
    "Win32_System_Kernel",
    "Win32_System_ProcessStatus",
    "Win32_System_Threading",
] }
winreg = "0.10.1"

[target.'cfg(unix)'.dependencies]
nix = "0.24.2"
