[package]
name = "fig_util"
version = "0.1.0"
authors = ["fig developers"]
edition = "2021"
description = "A layer between the terminal and shell."
homepage = "https://fig.io"
publish = false

[dependencies]
clap = "3.1.8"
fig_directories = { path = "../fig_directories" }
fig_settings = { path = "../fig_settings" }
serde = "1.0.136"
sha2 = "0.10.2"
sysinfo = "0.23.9"
thiserror = "1.0.30"

[target.'cfg(windows)'.dependencies]
winreg = "0.10.1"
