[package]
name = "fig_util"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
bstr = "1.0.1"
camino = "1.1.1"
cfg-if = "1.0.0"
clap = { version = "4.0.11", features = ["derive", "deprecated"] }
dirs = "4.0.0"
hex = "0.4.3"
once_cell = "1.15.0"
paste = "1.0.9"
rand = "0.8.5"
regex = "1.6.0"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.85"
sha2 = "0.10.6"
thiserror = "1.0.36"
time = { version = "0.3.14", features = ["macros", "formatting"] }
tokio = { version = "1.20.1", features = ["process"] }
tracing = "0.1.36"
whoami = "1.2.1"

[target.'cfg(target_os = "linux")'.dependencies]
sysinfo = "0.26.4"

[target.'cfg(target_os = "macos")'.dependencies]
regex = "1.6.0"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.42.0", features = [
    "Win32_Foundation",
    "Win32_System_Kernel",
    "Win32_System_ProcessStatus",
    "Win32_System_Threading",
] }
winreg = "0.10.1"

[target.'cfg(unix)'.dependencies]
nix = "0.25.0"

[dev-dependencies]
fig_test = { path = "../fig_test" }
insta = "1.21.0"
