/*
 Generated by typeshare 1.13.4
*/

/** Stub for EventLog which is not generated by typeshare */
export type EventLog = unknown;

/** Arguments for /agent command */
export interface AgentArgs {
	/**
	 * Agent name to switch to. If None, lists available agents.
	 * Accepts either `agentName` or `value` (for generic selection UI)
	 */
	agentName?: string;
}

/**
 * Unique identifier of an agent instance within a session.
 * 
 * Formatted as: `parent_id/name#rand`
 */
export interface AgentId {
	/**
	 * Name of the agent
	 * 
	 * This is the same as the agent name in the agent's config
	 */
	name: string;
	/**
	 * String-formatted id of the agent's parent, if available.
	 * 
	 * If available, this would be the result of [AgentId::to_string].
	 */
	parent_id?: string;
	/** Random suffix */
	rand?: string;
}

/** Settings to modify the runtime behavior of the agent. */
export interface AgentSettings {
	/** Timeout waiting for MCP servers to initialize during agent initialization. */
	mcp_init_timeout: { secs: number, nanos: number };
	/** Disable automatic compaction when context window overflows. */
	disable_auto_compact?: boolean;
}

/** State associated with a history of messages. */
export interface ConversationState {
	id: string;
	event_log?: EventLog;
}

/**
 * A point-in-time snapshot of an agent's state.
 * 
 * This includes all serializable state associated with an executing agent, for example:
 * 
 * * The agent config
 * * Conversation history
 * * State of execution (ie, is the agent idle, executing hooks, receiving a response from the
 * model, etc.)
 * * Agent settings
 * 
 * and so on.
 */
export interface AgentSnapshot {
	/** Agent id */
	id: AgentId;
	/** Agent conversation state */
	conversation_state: ConversationState;
	/** State associated with the model implementation used by the agent */
	model_state?: unknown;
	/** Agent settings */
	settings: AgentSettings;
}

/** Arguments for /clear command */
export interface ClearArgs {
}

/** Option displayed in autocomplete/dropdown UI */
export interface CommandOption {
	value: string;
	label: string;
	description?: string;
	group?: string;
}

/** Response from options request */
export interface CommandOptionsResponse {
	options: CommandOption[];
	hasMore?: boolean;
}

/** Result of command execution */
export interface CommandResult {
	success: boolean;
	message: string;
	data?: unknown;
}

/** Arguments for /compact command */
export interface CompactArgs {
	/** Target token count after compaction */
	targetTokens?: number;
}

export type ContentBlockDelta = 
	| { kind: "text", data: string }
	| { kind: "toolUse", data: ToolUseBlockDelta }
	| { kind: "reasoning", data?: undefined }
	| { kind: "document", data?: undefined };

export interface ContentBlockDeltaEvent {
	delta: ContentBlockDelta;
	/**
	 * Index of the content block within the message. This is optional to accommodate different
	 * model providers.
	 */
	contentBlockIndex?: number;
}

export type ContentBlockStart = 
	| { kind: "toolUse", data: ToolUseBlockStart };

export interface ContentBlockStartEvent {
	contentBlockStart?: ContentBlockStart;
	/**
	 * Index of the content block within the message. This is optional to accommodate different
	 * model providers.
	 */
	contentBlockIndex?: number;
}

export interface ContentBlockStopEvent {
	/**
	 * Index of the content block within the message. This is optional to accommodate different
	 * model providers.
	 */
	contentBlockIndex?: number;
}

/** Arguments for /context command */
export interface ContextArgs {
	/** Show a detailed breakdown */
	verbose?: boolean;
}

/** Arguments for /help command */
export interface HelpArgs {
}

export enum ImageFormat {
	Gif = "gif",
	Jpeg = "jpeg",
	Png = "png",
	Webp = "webp",
}

export type ImageSource = 
	| { kind: "bytes", data: number[] };

export interface ImageBlock {
	format: ImageFormat;
	source: ImageSource;
}

export enum Role {
	User = "user",
	Assistant = "assistant",
}

export type ContentBlock = 
	| { kind: "text", data: string }
	| { kind: "toolUse", data: ToolUseBlock }
	| { kind: "toolResult", data: ToolResultBlock }
	| { kind: "image", data: ImageBlock };

export interface Message {
	id?: string;
	role: Role;
	content: ContentBlock[];
	timestamp?: string;
}

export interface MessageStartEvent {
	role: Role;
}

export enum StopReason {
	ToolUse = "toolUse",
	EndTurn = "endTurn",
	MaxTokens = "maxTokens",
}

export interface MessageStopEvent {
	stopReason: StopReason;
}

export interface MetadataMetrics {
	requestStartTime: string;
	requestEndTime: string;
	timeToFirstChunk?: { secs: number, nanos: number };
	timeBetweenChunks?: { secs: number, nanos: number }[];
	responseStreamLen: number;
}

export interface MetadataUsage {
	inputTokens?: number;
	outputTokens?: number;
	cacheReadInputTokens?: number;
	cacheWriteInputTokens?: number;
	contextUsagePercentage?: number;
}

export interface MetadataService {
	requestId?: string;
	statusCode?: number;
}

export interface MetadataEvent {
	metrics?: MetadataMetrics;
	usage?: MetadataUsage;
	service?: MetadataService;
}

/** Arguments for /model command */
export interface ModelArgs {
	/**
	 * Model ID to switch to. If None, lists available models.
	 * Accepts either `modelName` or `value` (for generic selection UI)
	 */
	modelName?: string;
}

/** Model information for /model command */
export interface ModelInfo {
	id: string;
	displayName: string;
	provider?: string;
	contextWindow?: number;
}

/** Arguments for /quit command */
export interface QuitArgs {
}

export type StreamErrorKind = 
	/**
	 * The request failed due to the context window overflowing.
	 * 
	 * Q CLI by default will attempt to auto-summarize the conversation, and then retry the
	 * request.
	 */
	| { kind: "contextWindowOverflow", data?: undefined }
	/**
	 * The service failed for some reason.
	 * 
	 * Should be returned for 5xx errors.
	 */
	| { kind: "serviceFailure", data?: undefined }
	/** The request failed due to the client being throttled. */
	| { kind: "throttling", data?: undefined }
	/**
	 * The request was invalid.
	 * 
	 * Not retryable - indicative of a bug with the client.
	 */
	| { kind: "validation", data: {
	/** Custom error message, if available */
	message?: string;
}}
	/**
	 * The stream timed out after some relatively long period of time.
	 * 
	 * Q CLI currently retries these errors using some conversation fakery:
	 * 1. Add a new assistant message: `"Response timed out - message took too long to generate"`
	 * 2. Retry with a follow-up user message: `"You took too long to respond - try to split up the
	 * work into smaller steps."`
	 */
	| { kind: "streamTimeout", data: {
	duration: { secs: number, nanos: number };
}}
	/** The stream was closed to due being interrupted (for example, on ctrl+c). */
	| { kind: "interrupted", data?: undefined }
	/** Catch-all for errors not modeled in [StreamErrorKind]. */
	| { kind: "other", data: string };

export interface StreamError {
	/** The request id returned by the model provider, if available */
	original_request_id?: string;
	/** The HTTP status code returned by model provider, if available */
	original_status_code?: number;
	/** Exact error message returned by the model provider, if available */
	original_message?: string;
	kind: StreamErrorKind;
}

export type ToolResultContentBlock = 
	| { kind: "text", data: string }
	| { kind: "json", data: unknown }
	| { kind: "image", data: ImageBlock };

export enum ToolResultStatus {
	Error = "error",
	Success = "success",
}

export interface ToolResultBlock {
	toolUseId: string;
	content: ToolResultContentBlock[];
	status: ToolResultStatus;
}

export interface ToolUseBlock {
	/** Identifier for the tool use */
	toolUseId: string;
	/** Name of the tool */
	name: string;
	/** The input to pass to the tool */
	input: unknown;
}

export interface ToolUseBlockDelta {
	input: string;
}

export interface ToolUseBlockStart {
	/** Identifier for the tool use */
	toolUseId: string;
	/** Name of the tool */
	name: string;
}

export type StreamEvent = 
	| { kind: "messageStart", data: MessageStartEvent }
	| { kind: "messageStop", data: MessageStopEvent }
	| { kind: "contentBlockStart", data: ContentBlockStartEvent }
	| { kind: "contentBlockDelta", data: ContentBlockDeltaEvent }
	| { kind: "contentBlockStop", data: ContentBlockStopEvent }
	| { kind: "metadata", data: MetadataEvent };

export type StreamResult = 
	| { result: "ok", data: StreamEvent }
	| { result: "error", data: StreamError };

/** Tool name aliases as they appear on the wire (snake_case format). */
export enum ToolNameAlias {
	FsWrite = "fs_write",
	Write = "write",
	FsRead = "fs_read",
	Read = "read",
	ExecuteBash = "execute_bash",
	ExecuteCmd = "execute_cmd",
	Shell = "shell",
	ImageRead = "image_read",
	Ls = "ls",
	Summary = "summary",
	UseSubagent = "use_subagent",
	Subagent = "subagent",
}

/**
 * Slash command enum - each variant represents a command with its arguments.
 * 
 * Executed via `_kiro.dev/commands/execute` extension method, NOT as prompts.
 * This is distinct from ACP "slash commands" which are prompt-based workflows.
 */
export type TuiCommand = 
	/** Show help with all available commands */
	| { command: "help", args: HelpArgs }
	/** List available models or switch to a specific model */
	| { command: "model", args: ModelArgs }
	/** List available agents or switch to a specific agent */
	| { command: "agent", args: AgentArgs }
	/** Show context/token usage for the current conversation */
	| { command: "context", args: ContextArgs }
	/** Compact the conversation history */
	| { command: "compact", args: CompactArgs }
	/** Clear the conversation history */
	| { command: "clear", args: ClearArgs }
	/** Quit the application */
	| { command: "quit", args: QuitArgs };

