/*
 Generated by typeshare 1.13.4
*/

/**
 * Why a session was created. Combined with `parent_session_id`, this
 * distinguishes session origins. The default is [`Subagent`] for backward
 * compatibility: pre-`/rewind` sessions were saved without this field, and
 * when present they were always subagent flows.
 */
export enum SessionCreatedReason {
	/**
	 * Session is part of a subagent (use_subagent / agent_crew) flow.
	 * Default for backward compatibility with sessions saved before this field existed.
	 */
	Subagent = "subagent",
	/** Session was forked from an earlier turn of another session via `/rewind`. */
	Rewind = "rewind",
}

/**
 * Lightweight view of session metadata for listing.
 * 
 * Skips [`SessionData::session_state`]. Somewhat of a micro-optimization, but saves time scanning
 * large session directories with large [`SessionState`] included.
 */
export interface SessionDataView {
	session_id: string;
	cwd: string;
	created_at: string;
	updated_at: string;
	title?: string;
	/** `Some` only for subagent sessions; holds the parent session's ID. */
	parent_session_id?: string;
	/** Why this session was created. See [`SessionCreatedReason`]. */
	session_created_reason?: SessionCreatedReason;
	message_count?: number;
}

export type ChatResponseStream = 
	| { kind: "AssistantResponseEvent", data: {
	content: string;
}}
	/** Streaming response event for generated code text. */
	| { kind: "CodeEvent", data: {
	content: string;
}}
	| { kind: "CodeReferenceEvent", data: {
}}
	| { kind: "FollowupPromptEvent", data: {
}}
	| { kind: "IntentsEvent", data: {
}}
	| { kind: "InvalidStateEvent", data: {
	reason: string;
	message: string;
}}
	| { kind: "MessageMetadataEvent", data: {
	conversation_id?: string;
	utterance_id?: string;
}}
	| { kind: "ContextUsageEvent", data: {
	context_usage_percentage: number;
}}
	| { kind: "MetadataEvent", data: {
	total_tokens?: number;
	uncached_input_tokens?: number;
	output_tokens?: number;
	cache_read_input_tokens?: number;
	cache_write_input_tokens?: number;
}}
	| { kind: "MeteringEvent", data: {
	usage?: number;
	unit?: string;
	unit_plural?: string;
}}
	| { kind: "SupplementaryWebLinksEvent", data: {
}}
	| { kind: "ToolUseEvent", data: {
	tool_use_id: string;
	name: string;
	input?: string;
	stop?: boolean;
}}
	/** Reasoning/thinking content from extended thinking models. */
	| { kind: "ReasoningEvent", data: {
	text?: string;
	signature?: string;
	redacted_content?: number[];
}}
	| { kind: "Unknown", data: {
}};

/**
 * A mock stream item for testing. Supports 3 scenarios:
 * - `Event`: Normal streaming event, yielded from `recv()` as `Ok(Some(event))`
 * - `StreamError`: Mid-stream error, yielded from `recv()` as `Err(error)`
 * - `SendError`: Initial error, causes `send_message()` to return `Err` immediately
 */
export type MockStreamItem = 
	| { kind: "event", data: ChatResponseStream };

