/*
 Generated by typeshare 1.13.4
*/

/** Stub for ConverseStreamError which is not generated by typeshare */
export type ConverseStreamError = unknown;

export type ChatResponseStream = 
	| { kind: "AssistantResponseEvent", data: {
	content: string;
}}
	/** Streaming response event for generated code text. */
	| { kind: "CodeEvent", data: {
	content: string;
}}
	| { kind: "CodeReferenceEvent", data: {
}}
	| { kind: "FollowupPromptEvent", data: {
}}
	| { kind: "IntentsEvent", data: {
}}
	| { kind: "InvalidStateEvent", data: {
	reason: string;
	message: string;
}}
	| { kind: "MessageMetadataEvent", data: {
	conversation_id?: string;
	utterance_id?: string;
}}
	| { kind: "ContextUsageEvent", data: {
	context_usage_percentage: number;
}}
	| { kind: "MetadataEvent", data: {
	total_tokens?: number;
	uncached_input_tokens?: number;
	output_tokens?: number;
	cache_read_input_tokens?: number;
	cache_write_input_tokens?: number;
}}
	| { kind: "MeteringEvent", data: {
	usage?: number;
	unit?: string;
	unit_plural?: string;
}}
	| { kind: "SupplementaryWebLinksEvent", data: {
}}
	| { kind: "ToolUseEvent", data: {
	tool_use_id: string;
	name: string;
	input?: string;
	stop?: boolean;
}}
	| { kind: "Unknown", data: {
}};

/**
 * A mock stream item for testing. Supports 3 scenarios:
 * - `Event`: Normal streaming event, yielded from `recv()` as `Ok(Some(event))`
 * - `StreamError`: Mid-stream error, yielded from `recv()` as `Err(error)`
 * - `SendError`: Initial error, causes `send_message()` to return `Err` immediately
 */
export type MockStreamItem = 
	| { kind: "event", data: ChatResponseStream }
	| { kind: "streamError", data: ConverseStreamError }
	| { kind: "sendError", data: ConverseStreamError };

