[package]
name = "fig_ipc"
version = "0.1.0"
authors = ["fig developers"]
edition = "2021"
homepage = "https://fig.io"
publish = false

[dependencies]
async-trait = "0.1.57"
bytes = "1.2.1"
cfg-if = "1.0.0"
fig_proto = { path = "../fig_proto" }
fig_util = { path = "../fig_util" }
pin-project-lite = "0.2.9"
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["fs", "time", "io-util", "net"] }
tracing = "0.1.36"
whoami = "1.2.1"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.36.1", features = ["Win32_Networking_WinSock"] }
