// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// JSON-RPC 2.0 request structure for MCP operations
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub struct InvokeMcpInput {
    /// JSON-RPC protocol version
    pub jsonrpc: ::std::option::Option<::std::string::String>,
    /// Request identifier for response correlation
    pub id: ::std::option::Option<::std::string::String>,
    /// MCP method name
    pub method: ::std::option::Option<crate::types::McpMethod>,
    /// Method-specific parameters
    pub params: ::std::option::Option<::aws_smithy_types::Document>,
}
impl InvokeMcpInput {
    /// JSON-RPC protocol version
    pub fn jsonrpc(&self) -> ::std::option::Option<&str> {
        self.jsonrpc.as_deref()
    }

    /// Request identifier for response correlation
    pub fn id(&self) -> ::std::option::Option<&str> {
        self.id.as_deref()
    }

    /// MCP method name
    pub fn method(&self) -> ::std::option::Option<&crate::types::McpMethod> {
        self.method.as_ref()
    }

    /// Method-specific parameters
    pub fn params(&self) -> ::std::option::Option<&::aws_smithy_types::Document> {
        self.params.as_ref()
    }
}
impl ::std::fmt::Debug for InvokeMcpInput {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("InvokeMcpInput");
        formatter.field("jsonrpc", &self.jsonrpc);
        formatter.field("id", &self.id);
        formatter.field("method", &self.method);
        formatter.field("params", &"*** Sensitive Data Redacted ***");
        formatter.finish()
    }
}
impl InvokeMcpInput {
    /// Creates a new builder-style object to manufacture
    /// [`InvokeMcpInput`](crate::operation::invoke_mcp::InvokeMcpInput).
    pub fn builder() -> crate::operation::invoke_mcp::builders::InvokeMcpInputBuilder {
        crate::operation::invoke_mcp::builders::InvokeMcpInputBuilder::default()
    }
}

/// A builder for [`InvokeMcpInput`](crate::operation::invoke_mcp::InvokeMcpInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default)]
#[non_exhaustive]
pub struct InvokeMcpInputBuilder {
    pub(crate) jsonrpc: ::std::option::Option<::std::string::String>,
    pub(crate) id: ::std::option::Option<::std::string::String>,
    pub(crate) method: ::std::option::Option<crate::types::McpMethod>,
    pub(crate) params: ::std::option::Option<::aws_smithy_types::Document>,
}
impl InvokeMcpInputBuilder {
    /// JSON-RPC protocol version
    pub fn jsonrpc(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.jsonrpc = ::std::option::Option::Some(input.into());
        self
    }

    /// JSON-RPC protocol version
    pub fn set_jsonrpc(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.jsonrpc = input;
        self
    }

    /// JSON-RPC protocol version
    pub fn get_jsonrpc(&self) -> &::std::option::Option<::std::string::String> {
        &self.jsonrpc
    }

    /// Request identifier for response correlation
    pub fn id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.id = ::std::option::Option::Some(input.into());
        self
    }

    /// Request identifier for response correlation
    pub fn set_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.id = input;
        self
    }

    /// Request identifier for response correlation
    pub fn get_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.id
    }

    /// MCP method name
    /// This field is required.
    pub fn method(mut self, input: crate::types::McpMethod) -> Self {
        self.method = ::std::option::Option::Some(input);
        self
    }

    /// MCP method name
    pub fn set_method(mut self, input: ::std::option::Option<crate::types::McpMethod>) -> Self {
        self.method = input;
        self
    }

    /// MCP method name
    pub fn get_method(&self) -> &::std::option::Option<crate::types::McpMethod> {
        &self.method
    }

    /// Method-specific parameters
    pub fn params(mut self, input: ::aws_smithy_types::Document) -> Self {
        self.params = ::std::option::Option::Some(input);
        self
    }

    /// Method-specific parameters
    pub fn set_params(mut self, input: ::std::option::Option<::aws_smithy_types::Document>) -> Self {
        self.params = input;
        self
    }

    /// Method-specific parameters
    pub fn get_params(&self) -> &::std::option::Option<::aws_smithy_types::Document> {
        &self.params
    }

    /// Consumes the builder and constructs a
    /// [`InvokeMcpInput`](crate::operation::invoke_mcp::InvokeMcpInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::invoke_mcp::InvokeMcpInput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(crate::operation::invoke_mcp::InvokeMcpInput {
            jsonrpc: self.jsonrpc,
            id: self.id,
            method: self.method,
            params: self.params,
        })
    }
}
impl ::std::fmt::Debug for InvokeMcpInputBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("InvokeMcpInputBuilder");
        formatter.field("jsonrpc", &self.jsonrpc);
        formatter.field("id", &self.id);
        formatter.field("method", &self.method);
        formatter.field("params", &"*** Sensitive Data Redacted ***");
        formatter.finish()
    }
}
