// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// JSON-RPC 2.0 response structure for MCP operations
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub struct InvokeMcpOutput {
    /// JSON-RPC protocol version
    pub jsonrpc: ::std::option::Option<::std::string::String>,
    /// Request identifier for response correlation (string or number per MCP spec)
    pub id: ::aws_smithy_types::Document,
    /// Success result (mutually exclusive with error)
    pub result: ::std::option::Option<::aws_smithy_types::Document>,
    /// Error information (mutually exclusive with result)
    pub error: ::std::option::Option<crate::types::JsonRpcError>,
    _request_id: Option<String>,
}
impl InvokeMcpOutput {
    /// JSON-RPC protocol version
    pub fn jsonrpc(&self) -> ::std::option::Option<&str> {
        self.jsonrpc.as_deref()
    }

    /// Request identifier for response correlation (string or number per MCP spec)
    pub fn id(&self) -> &::aws_smithy_types::Document {
        &self.id
    }

    /// Success result (mutually exclusive with error)
    pub fn result(&self) -> ::std::option::Option<&::aws_smithy_types::Document> {
        self.result.as_ref()
    }

    /// Error information (mutually exclusive with result)
    pub fn error(&self) -> ::std::option::Option<&crate::types::JsonRpcError> {
        self.error.as_ref()
    }
}
impl ::std::fmt::Debug for InvokeMcpOutput {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("InvokeMcpOutput");
        formatter.field("jsonrpc", &self.jsonrpc);
        formatter.field("id", &self.id);
        formatter.field("result", &"*** Sensitive Data Redacted ***");
        formatter.field("error", &self.error);
        formatter.field("_request_id", &self._request_id);
        formatter.finish()
    }
}
impl ::aws_types::request_id::RequestId for InvokeMcpOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
impl InvokeMcpOutput {
    /// Creates a new builder-style object to manufacture
    /// [`InvokeMcpOutput`](crate::operation::invoke_mcp::InvokeMcpOutput).
    pub fn builder() -> crate::operation::invoke_mcp::builders::InvokeMcpOutputBuilder {
        crate::operation::invoke_mcp::builders::InvokeMcpOutputBuilder::default()
    }
}

/// A builder for [`InvokeMcpOutput`](crate::operation::invoke_mcp::InvokeMcpOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default)]
#[non_exhaustive]
pub struct InvokeMcpOutputBuilder {
    pub(crate) jsonrpc: ::std::option::Option<::std::string::String>,
    pub(crate) id: ::std::option::Option<::aws_smithy_types::Document>,
    pub(crate) result: ::std::option::Option<::aws_smithy_types::Document>,
    pub(crate) error: ::std::option::Option<crate::types::JsonRpcError>,
    _request_id: Option<String>,
}
impl InvokeMcpOutputBuilder {
    /// JSON-RPC protocol version
    pub fn jsonrpc(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.jsonrpc = ::std::option::Option::Some(input.into());
        self
    }

    /// JSON-RPC protocol version
    pub fn set_jsonrpc(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.jsonrpc = input;
        self
    }

    /// JSON-RPC protocol version
    pub fn get_jsonrpc(&self) -> &::std::option::Option<::std::string::String> {
        &self.jsonrpc
    }

    /// Request identifier for response correlation (string or number per MCP spec)
    /// This field is required.
    pub fn id(mut self, input: ::aws_smithy_types::Document) -> Self {
        self.id = ::std::option::Option::Some(input);
        self
    }

    /// Request identifier for response correlation (string or number per MCP spec)
    pub fn set_id(mut self, input: ::std::option::Option<::aws_smithy_types::Document>) -> Self {
        self.id = input;
        self
    }

    /// Request identifier for response correlation (string or number per MCP spec)
    pub fn get_id(&self) -> &::std::option::Option<::aws_smithy_types::Document> {
        &self.id
    }

    /// Success result (mutually exclusive with error)
    pub fn result(mut self, input: ::aws_smithy_types::Document) -> Self {
        self.result = ::std::option::Option::Some(input);
        self
    }

    /// Success result (mutually exclusive with error)
    pub fn set_result(mut self, input: ::std::option::Option<::aws_smithy_types::Document>) -> Self {
        self.result = input;
        self
    }

    /// Success result (mutually exclusive with error)
    pub fn get_result(&self) -> &::std::option::Option<::aws_smithy_types::Document> {
        &self.result
    }

    /// Error information (mutually exclusive with result)
    pub fn error(mut self, input: crate::types::JsonRpcError) -> Self {
        self.error = ::std::option::Option::Some(input);
        self
    }

    /// Error information (mutually exclusive with result)
    pub fn set_error(mut self, input: ::std::option::Option<crate::types::JsonRpcError>) -> Self {
        self.error = input;
        self
    }

    /// Error information (mutually exclusive with result)
    pub fn get_error(&self) -> &::std::option::Option<crate::types::JsonRpcError> {
        &self.error
    }

    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }

    /// Consumes the builder and constructs a
    /// [`InvokeMcpOutput`](crate::operation::invoke_mcp::InvokeMcpOutput). This method will
    /// fail if any of the following fields are not set:
    /// - [`id`](crate::operation::invoke_mcp::builders::InvokeMcpOutputBuilder::id)
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::invoke_mcp::InvokeMcpOutput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(crate::operation::invoke_mcp::InvokeMcpOutput {
            jsonrpc: self.jsonrpc,
            id: self.id.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "id",
                    "id was not specified but it is required when building InvokeMcpOutput",
                )
            })?,
            result: self.result,
            error: self.error,
            _request_id: self._request_id,
        })
    }
}
impl ::std::fmt::Debug for InvokeMcpOutputBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("InvokeMcpOutputBuilder");
        formatter.field("jsonrpc", &self.jsonrpc);
        formatter.field("id", &self.id);
        formatter.field("result", &"*** Sensitive Data Redacted ***");
        formatter.field("error", &self.error);
        formatter.field("_request_id", &self._request_id);
        formatter.finish()
    }
}
