// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub use crate::operation::invoke_mcp::_invoke_mcp_input::InvokeMcpInputBuilder;
pub use crate::operation::invoke_mcp::_invoke_mcp_output::InvokeMcpOutputBuilder;

impl crate::operation::invoke_mcp::builders::InvokeMcpInputBuilder {
    /// Sends a request with this input using the given client.
    pub async fn send_with(
        self,
        client: &crate::Client,
    ) -> ::std::result::Result<
        crate::operation::invoke_mcp::InvokeMcpOutput,
        ::aws_smithy_runtime_api::client::result::SdkError<
            crate::operation::invoke_mcp::InvokeMCPError,
            ::aws_smithy_runtime_api::client::orchestrator::HttpResponse,
        >,
    > {
        let mut fluent_builder = client.invoke_mcp();
        fluent_builder.inner = self;
        fluent_builder.send().await
    }
}
/// Fluent builder constructing a request to `InvokeMCP`.
///
/// MCP over HTTP operation supporting both request-response (Accept: application/json) and SSE
/// (Accept: text/event-stream)
#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct InvokeMCPFluentBuilder {
    handle: ::std::sync::Arc<crate::client::Handle>,
    inner: crate::operation::invoke_mcp::builders::InvokeMcpInputBuilder,
    config_override: ::std::option::Option<crate::config::Builder>,
}
impl
    crate::client::customize::internal::CustomizableSend<
        crate::operation::invoke_mcp::InvokeMcpOutput,
        crate::operation::invoke_mcp::InvokeMCPError,
    > for InvokeMCPFluentBuilder
{
    fn send(
        self,
        config_override: crate::config::Builder,
    ) -> crate::client::customize::internal::BoxFuture<
        crate::client::customize::internal::SendResult<
            crate::operation::invoke_mcp::InvokeMcpOutput,
            crate::operation::invoke_mcp::InvokeMCPError,
        >,
    > {
        ::std::boxed::Box::pin(async move { self.config_override(config_override).send().await })
    }
}
impl InvokeMCPFluentBuilder {
    /// Creates a new `InvokeMCPFluentBuilder`.
    pub(crate) fn new(handle: ::std::sync::Arc<crate::client::Handle>) -> Self {
        Self {
            handle,
            inner: ::std::default::Default::default(),
            config_override: ::std::option::Option::None,
        }
    }

    /// Access the InvokeMCP as a reference.
    pub fn as_input(&self) -> &crate::operation::invoke_mcp::builders::InvokeMcpInputBuilder {
        &self.inner
    }

    /// Sends the request and returns the response.
    ///
    /// If an error occurs, an `SdkError` will be returned with additional details that
    /// can be matched against.
    ///
    /// By default, any retryable failures will be retried twice. Retry behavior
    /// is configurable with the [RetryConfig](aws_smithy_types::retry::RetryConfig), which can be
    /// set when configuring the client.
    pub async fn send(
        self,
    ) -> ::std::result::Result<
        crate::operation::invoke_mcp::InvokeMcpOutput,
        ::aws_smithy_runtime_api::client::result::SdkError<
            crate::operation::invoke_mcp::InvokeMCPError,
            ::aws_smithy_runtime_api::client::orchestrator::HttpResponse,
        >,
    > {
        let input = self
            .inner
            .build()
            .map_err(::aws_smithy_runtime_api::client::result::SdkError::construction_failure)?;
        let runtime_plugins = crate::operation::invoke_mcp::InvokeMCP::operation_runtime_plugins(
            self.handle.runtime_plugins.clone(),
            &self.handle.conf,
            self.config_override,
        );
        crate::operation::invoke_mcp::InvokeMCP::orchestrate(&runtime_plugins, input).await
    }

    /// Consumes this builder, creating a customizable operation that can be modified before being
    /// sent.
    pub fn customize(
        self,
    ) -> crate::client::customize::CustomizableOperation<
        crate::operation::invoke_mcp::InvokeMcpOutput,
        crate::operation::invoke_mcp::InvokeMCPError,
        Self,
    > {
        crate::client::customize::CustomizableOperation::new(self)
    }

    pub(crate) fn config_override(
        mut self,
        config_override: impl ::std::convert::Into<crate::config::Builder>,
    ) -> Self {
        self.set_config_override(::std::option::Option::Some(config_override.into()));
        self
    }

    pub(crate) fn set_config_override(
        &mut self,
        config_override: ::std::option::Option<crate::config::Builder>,
    ) -> &mut Self {
        self.config_override = config_override;
        self
    }

    /// JSON-RPC protocol version
    pub fn jsonrpc(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.inner = self.inner.jsonrpc(input.into());
        self
    }

    /// JSON-RPC protocol version
    pub fn set_jsonrpc(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.inner = self.inner.set_jsonrpc(input);
        self
    }

    /// JSON-RPC protocol version
    pub fn get_jsonrpc(&self) -> &::std::option::Option<::std::string::String> {
        self.inner.get_jsonrpc()
    }

    /// Request identifier for response correlation (string or number per MCP spec)
    pub fn id(mut self, input: ::aws_smithy_types::Document) -> Self {
        self.inner = self.inner.id(input);
        self
    }

    /// Request identifier for response correlation (string or number per MCP spec)
    pub fn set_id(mut self, input: ::std::option::Option<::aws_smithy_types::Document>) -> Self {
        self.inner = self.inner.set_id(input);
        self
    }

    /// Request identifier for response correlation (string or number per MCP spec)
    pub fn get_id(&self) -> &::std::option::Option<::aws_smithy_types::Document> {
        self.inner.get_id()
    }

    /// MCP method name
    pub fn method(mut self, input: crate::types::McpMethod) -> Self {
        self.inner = self.inner.method(input);
        self
    }

    /// MCP method name
    pub fn set_method(mut self, input: ::std::option::Option<crate::types::McpMethod>) -> Self {
        self.inner = self.inner.set_method(input);
        self
    }

    /// MCP method name
    pub fn get_method(&self) -> &::std::option::Option<crate::types::McpMethod> {
        self.inner.get_method()
    }

    /// Method-specific parameters
    pub fn params(mut self, input: ::aws_smithy_types::Document) -> Self {
        self.inner = self.inner.params(input);
        self
    }

    /// Method-specific parameters
    pub fn set_params(mut self, input: ::std::option::Option<::aws_smithy_types::Document>) -> Self {
        self.inner = self.inner.set_params(input);
        self
    }

    /// Method-specific parameters
    pub fn get_params(&self) -> &::std::option::Option<::aws_smithy_types::Document> {
        self.inner.get_params()
    }
}
