// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the
    /// [`InvokeMCPStream`](crate::operation::invoke_mcp_stream::builders::InvokeMCPStreamFluentBuilder)
    /// operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`jsonrpc(impl Into<String>)`](crate::operation::invoke_mcp_stream::builders::InvokeMCPStreamFluentBuilder::jsonrpc) / [`set_jsonrpc(Option<String>)`](crate::operation::invoke_mcp_stream::builders::InvokeMCPStreamFluentBuilder::set_jsonrpc):<br>required: **false**<br>JSON-RPC protocol version<br>
    ///   - [`id(Document)`](crate::operation::invoke_mcp_stream::builders::InvokeMCPStreamFluentBuilder::id) / [`set_id(Option<Document>)`](crate::operation::invoke_mcp_stream::builders::InvokeMCPStreamFluentBuilder::set_id):<br>required: **false**<br>Request identifier for response correlation. Absent for notifications per JSON-RPC spec.<br>
    ///   - [`method(McpMethod)`](crate::operation::invoke_mcp_stream::builders::InvokeMCPStreamFluentBuilder::method) / [`set_method(Option<McpMethod>)`](crate::operation::invoke_mcp_stream::builders::InvokeMCPStreamFluentBuilder::set_method):<br>required: **true**<br>MCP method name<br>
    ///   - [`params(Document)`](crate::operation::invoke_mcp_stream::builders::InvokeMCPStreamFluentBuilder::params) / [`set_params(Option<Document>)`](crate::operation::invoke_mcp_stream::builders::InvokeMCPStreamFluentBuilder::set_params):<br>required: **false**<br>Method-specific parameters<br>
    /// - On success, responds with
    ///   [`InvokeMcpStreamOutput`](crate::operation::invoke_mcp_stream::InvokeMcpStreamOutput) with
    ///   field(s):
    ///   - [`content_type(Option<String>)`](crate::operation::invoke_mcp_stream::InvokeMcpStreamOutput::content_type): Content type header (application/json for sync, text/event-stream for streaming)
    ///   - [`stream(EventReceiver<McpStreamOutput,
    ///     McpStreamOutputError>)`](crate::operation::invoke_mcp_stream::InvokeMcpStreamOutput::stream):
    ///     Stream of JSON-RPC response events
    /// - On failure, responds with
    ///   [`SdkError<InvokeMCPStreamError>`](crate::operation::invoke_mcp_stream::InvokeMCPStreamError)
    pub fn invoke_mcp_stream(&self) -> crate::operation::invoke_mcp_stream::builders::InvokeMCPStreamFluentBuilder {
        crate::operation::invoke_mcp_stream::builders::InvokeMCPStreamFluentBuilder::new(self.handle.clone())
    }
}
