// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the
    /// [`InvokeMCP`](crate::operation::invoke_mcp::builders::InvokeMCPFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`jsonrpc(impl
    ///     Into<String>)`](crate::operation::invoke_mcp::builders::InvokeMCPFluentBuilder::jsonrpc)
    ///     / [`set_jsonrpc(Option<String>)`](crate::operation::invoke_mcp::builders::InvokeMCPFluentBuilder::set_jsonrpc):
    ///     <br>required: **false**<br>JSON-RPC protocol version<br>
    ///   - [`id(impl Into<String>)`](crate::operation::invoke_mcp::builders::InvokeMCPFluentBuilder::id) / [`set_id(Option<String>)`](crate::operation::invoke_mcp::builders::InvokeMCPFluentBuilder::set_id):<br>required: **false**<br>Request identifier for response correlation<br>
    ///   - [`method(McpMethod)`](crate::operation::invoke_mcp::builders::InvokeMCPFluentBuilder::method) / [`set_method(Option<McpMethod>)`](crate::operation::invoke_mcp::builders::InvokeMCPFluentBuilder::set_method):<br>required: **true**<br>MCP method name<br>
    ///   - [`params(Document)`](crate::operation::invoke_mcp::builders::InvokeMCPFluentBuilder::params) / [`set_params(Option<Document>)`](crate::operation::invoke_mcp::builders::InvokeMCPFluentBuilder::set_params):<br>required: **false**<br>Method-specific parameters<br>
    /// - On success, responds with
    ///   [`InvokeMcpOutput`](crate::operation::invoke_mcp::InvokeMcpOutput) with field(s):
    ///   - [`jsonrpc(Option<String>)`](crate::operation::invoke_mcp::InvokeMcpOutput::jsonrpc):
    ///     JSON-RPC protocol version
    ///   - [`id(Option<String>)`](crate::operation::invoke_mcp::InvokeMcpOutput::id): Request
    ///     identifier for response correlation
    ///   - [`result(Option<Document>)`](crate::operation::invoke_mcp::InvokeMcpOutput::result):
    ///     Success result (mutually exclusive with error)
    ///   - [`error(Option<JsonRpcError>)`](crate::operation::invoke_mcp::InvokeMcpOutput::error):
    ///     Error information (mutually exclusive with result)
    /// - On failure, responds with
    ///   [`SdkError<InvokeMCPError>`](crate::operation::invoke_mcp::InvokeMCPError)
    pub fn invoke_mcp(&self) -> crate::operation::invoke_mcp::builders::InvokeMCPFluentBuilder {
        crate::operation::invoke_mcp::builders::InvokeMCPFluentBuilder::new(self.handle.clone())
    }
}
