[package]
name = "fig-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
aws-sdk-cognitoidentityprovider = "0.6.0"
rand = "0.8.4"
uuid = { version = "0.8.2", features = ["v4"] }
thiserror = "1.0.30"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
directories = "4.0.0"
time = { version = "0.3.6", features = ["serde-human-readable", "local-offset"] }
