[package]
name = "fig-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
aws-sdk-cognitoidentityprovider = "0.8.0"
aws-smithy-async = "0.38.0"
aws-smithy-client = { version = "0.38.0", features = ["client-hyper"] }
base64 = "0.13.0"
fig-directories = { path = "../fig-directories" }
hyper-rustls = { version = "0.23.0", features = ["webpki-tokio"] }
rand = "0.8.4"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
thiserror = "1.0.30"
time = { version = "0.3.6", features = ["serde-human-readable", "local-offset"] }
uuid = { version = "0.8.2", features = ["v4"] }

