[package]
name = "fig_telemetry"
version = "0.2.0"
authors = ["fig developers"]
edition = "2021"
homepage = "https://fig.io"
publish = false

[dependencies]
anyhow = "1.0.60"
fig_auth = { path = "../fig_auth" }
fig_ipc = { path = "../fig_ipc" }
fig_proto = { path = "../fig_proto" }
fig_settings = { path = "../fig_settings" }
fig_util = { path = "../fig_util" }
once_cell = { version = "1.13.0", features = ["parking_lot"] }
parking_lot = "0.12.1"
reqwest = { version = "0.11.10", default-features = false, features = ["json", "rustls-tls-webpki-roots"] }
sentry = { version = "0.27.0", default-features = false, features = ["backtrace", "contexts", "panic", "anyhow", "reqwest", "rustls"] }
serde = "1.0.141"
serde_json = "1.0.82"
thiserror = "1.0.32"
tracing = "0.1.36"
uuid = "1.1.2"

