[package]
name = "fig_telemetry"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
anyhow = "1.0.66"
fig_ipc = { path = "../fig_ipc" }
fig_proto = { path = "../fig_proto" }
fig_request = { path = "../fig_request" }
fig_settings = { path = "../fig_settings" }
fig_util = { path = "../fig_util" }
once_cell = { version = "1.15.0", features = ["parking_lot"] }
parking_lot = "0.12.1"
sentry = { version = "0.27.0", default-features = false, features = ["backtrace", "contexts", "panic", "anyhow", "reqwest", "rustls"] }
serde = "1.0.147"
serde_json = "1.0.87"
thiserror = "1.0.36"
tracing = "0.1.36"
uuid = "1.2.1"
