[package]
name = "kiro-telemetry"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
publish.workspace = true
version.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
test-support = ["dep:opentelemetry-proto", "dep:prost"]

[dependencies]
indexmap.workspace = true
kiro-telemetry-schema = { path = "../kiro-telemetry-schema" }
libc.workspace = true
opentelemetry.workspace = true
opentelemetry-http.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry_sdk.workspace = true
opentelemetry-proto = { workspace = true, features = ["gen-tonic-messages", "metrics", "logs"], optional = true }
prost = { version = "0.14.3", optional = true }
regex.workspace = true
reqwest = { workspace = true, features = ["blocking"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
async-trait.workspace = true

[dev-dependencies]
futures.workspace = true
opentelemetry-proto = { workspace = true, features = ["gen-tonic-messages", "metrics", "logs"] }
prost = "0.14.3"
tempfile.workspace = true

[[example]]
name = "catalog_smoke"
required-features = ["test-support"]
