// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ListProfilesOutput {
    #[allow(missing_docs)] // documentation missing in model
    pub profiles: ::std::vec::Vec<crate::types::Profile>,
    #[allow(missing_docs)] // documentation missing in model
    pub next_token: ::std::option::Option<::std::string::String>,
    /// List of all models available for admins to select from for model governance.
    pub available_models: ::std::option::Option<::std::vec::Vec<crate::types::Model>>,
    _request_id: Option<String>,
}
impl ListProfilesOutput {
    #[allow(missing_docs)] // documentation missing in model
    pub fn profiles(&self) -> &[crate::types::Profile] {
        use std::ops::Deref;
        self.profiles.deref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn next_token(&self) -> ::std::option::Option<&str> {
        self.next_token.as_deref()
    }

    /// List of all models available for admins to select from for model governance.
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no
    /// value was sent, use `.available_models.is_none()`.
    pub fn available_models(&self) -> &[crate::types::Model] {
        self.available_models.as_deref().unwrap_or_default()
    }
}
impl ::aws_types::request_id::RequestId for ListProfilesOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
impl ListProfilesOutput {
    /// Creates a new builder-style object to manufacture
    /// [`ListProfilesOutput`](crate::operation::list_profiles::ListProfilesOutput).
    pub fn builder() -> crate::operation::list_profiles::builders::ListProfilesOutputBuilder {
        crate::operation::list_profiles::builders::ListProfilesOutputBuilder::default()
    }
}

/// A builder for [`ListProfilesOutput`](crate::operation::list_profiles::ListProfilesOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ListProfilesOutputBuilder {
    pub(crate) profiles: ::std::option::Option<::std::vec::Vec<crate::types::Profile>>,
    pub(crate) next_token: ::std::option::Option<::std::string::String>,
    pub(crate) available_models: ::std::option::Option<::std::vec::Vec<crate::types::Model>>,
    _request_id: Option<String>,
}
impl ListProfilesOutputBuilder {
    /// Appends an item to `profiles`.
    ///
    /// To override the contents of this collection use [`set_profiles`](Self::set_profiles).
    pub fn profiles(mut self, input: crate::types::Profile) -> Self {
        let mut v = self.profiles.unwrap_or_default();
        v.push(input);
        self.profiles = ::std::option::Option::Some(v);
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_profiles(mut self, input: ::std::option::Option<::std::vec::Vec<crate::types::Profile>>) -> Self {
        self.profiles = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_profiles(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::Profile>> {
        &self.profiles
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn next_token(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.next_token = ::std::option::Option::Some(input.into());
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_next_token(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.next_token = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_next_token(&self) -> &::std::option::Option<::std::string::String> {
        &self.next_token
    }

    /// Appends an item to `available_models`.
    ///
    /// To override the contents of this collection use
    /// [`set_available_models`](Self::set_available_models).
    ///
    /// List of all models available for admins to select from for model governance.
    pub fn available_models(mut self, input: crate::types::Model) -> Self {
        let mut v = self.available_models.unwrap_or_default();
        v.push(input);
        self.available_models = ::std::option::Option::Some(v);
        self
    }

    /// List of all models available for admins to select from for model governance.
    pub fn set_available_models(mut self, input: ::std::option::Option<::std::vec::Vec<crate::types::Model>>) -> Self {
        self.available_models = input;
        self
    }

    /// List of all models available for admins to select from for model governance.
    pub fn get_available_models(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::Model>> {
        &self.available_models
    }

    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }

    /// Consumes the builder and constructs a
    /// [`ListProfilesOutput`](crate::operation::list_profiles::ListProfilesOutput). This method
    /// will fail if any of the following fields are not set:
    /// - [`profiles`](crate::operation::list_profiles::builders::ListProfilesOutputBuilder::profiles)
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::list_profiles::ListProfilesOutput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(crate::operation::list_profiles::ListProfilesOutput {
            profiles: self.profiles.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "profiles",
                    "profiles was not specified but it is required when building ListProfilesOutput",
                )
            })?,
            next_token: self.next_token,
            available_models: self.available_models,
            _request_id: self._request_id,
        })
    }
}
