[package]
name = "ibus"
version = "1.0.0"

[dependencies]
libc = "0.2"
bitflags = "1.3"

[dependencies.ffi]
package = "ibus-sys"
path = "./ibus-sys"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"
