[package]
name = "ibus"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
tokio = { version = "1", features = ["process"] }
zbus = { version = "2", default-features = false, features = ["tokio"] }

