[package]
name = "ibus"
version = "1.0.0"
edition = "2021"

[dependencies]
libc = "0.2"
bitflags = "1.3"

[dependencies.ffi]
package = "ibus-sys"
path = "./ibus-sys"

[dependencies.gio]
git = "https://github.com/gtk-rs/gtk-rs-core"

[dependencies.glib]
git = "https://github.com/gtk-rs/gtk-rs-core"
