[options]
library = "IBus"
version = "1.0"
target_path = "."
min_cfg_version = "1.5"
work_mode = "normal"
girs_directories = ["gir-files"]
generate_safety_asserts = true
deprecate_by_min_version = true
single_version_file = true
generate_builder = true

generate = [
    "IBus.Engine"
]
