[package]
name = "macos_accessibility_position"
version = "0.1.0"
edition = "2021"
publish = false

[target.'cfg(target_os = "macos")'.dependencies]
lazy_static = "1.4"
core-graphics = "0.22"
core-foundation = "0.9"
cocoa = "0.24"
accessibility-sys = { path = "./accessibility-master/accessibility-sys", version = "0.1.3" }
accessibility = { path = "./accessibility-master/accessibility", version = "0.1.6" }
appkit-nsworkspace-bindings = { path = "./appkit-nsworkspace-bindings", version = "0.1.0" }
tracing = "0.1.36"
