[package]
name = "macos_accessibility_position"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
publish.workspace = true
version.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
lazy_static = "1.4"
block = "0.1.6"
core-graphics = "0.22"
core-foundation = "0.9"
cocoa = "0.24"
objc = "0.2"
dashmap = "5.3.4"
flume = "0.10.14"
fnv = "1.0.7"
accessibility-sys = { path = "./accessibility-master/accessibility-sys", version = "0.1.3" }
once_cell = "1.16.0"
slab = "0.4"
parking_lot = "0.12.1"
accessibility = { path = "./accessibility-master/accessibility", version = "0.1.6" }
appkit-nsworkspace-bindings = { path = "./appkit-nsworkspace-bindings", version = "0.1.0" }
tracing = "0.1.36"
tokio = { version = "1.20.1", features = ["full"] }
