[package]
name = "fig_sync"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
cfg-if = "1.0.0"
crossterm = "0.25.0"
fig_api_client = { path = "../fig_api_client" }
fig_request = { path = "../fig_request" }
fig_settings = { path = "../fig_settings" }
fig_util = { path = "../fig_util" }
flume = "0.10.14"
futures = "0.3.23"
git2 = { version = "0.15.0", features = ["vendored-openssl", "vendored-libgit2"] }
once_cell = { version = "1.15.0", features = ["parking_lot"] }
parking_lot = "0.12.1"
regex = "1.6.0"
reqwest = { version = "0.11.12", default-features = false, features = ["json", "rustls-tls-webpki-roots"] }
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.86"
tempfile = "3.3.0"
thiserror = "1.0.36"
time = { version = "=0.3.14", features = ["serde-human-readable"] }
tokio = "1.20.1"
tracing = "0.1.36"
url = { version = "2.3.1", features = ["serde"] }
