[package]
name = "system_socket"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.17.0", features = ["fs", "time", "io-util", "net"] }

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"
