// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Structure representing an option in a clarification step.
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub struct ClarificationAnswerOption {
    /// Display label for the option.
    pub label: ::std::string::String,
    /// Value associated with the option.
    pub value: ::std::string::String,
}
impl ClarificationAnswerOption {
    /// Display label for the option.
    pub fn label(&self) -> &str {
        use std::ops::Deref;
        self.label.deref()
    }

    /// Value associated with the option.
    pub fn value(&self) -> &str {
        use std::ops::Deref;
        self.value.deref()
    }
}
impl ::std::fmt::Debug for ClarificationAnswerOption {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("ClarificationAnswerOption");
        formatter.field("label", &"*** Sensitive Data Redacted ***");
        formatter.field("value", &"*** Sensitive Data Redacted ***");
        formatter.finish()
    }
}
impl ClarificationAnswerOption {
    /// Creates a new builder-style object to manufacture
    /// [`ClarificationAnswerOption`](crate::types::ClarificationAnswerOption).
    pub fn builder() -> crate::types::builders::ClarificationAnswerOptionBuilder {
        crate::types::builders::ClarificationAnswerOptionBuilder::default()
    }
}

/// A builder for [`ClarificationAnswerOption`](crate::types::ClarificationAnswerOption).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default)]
#[non_exhaustive]
pub struct ClarificationAnswerOptionBuilder {
    pub(crate) label: ::std::option::Option<::std::string::String>,
    pub(crate) value: ::std::option::Option<::std::string::String>,
}
impl ClarificationAnswerOptionBuilder {
    /// Display label for the option.
    /// This field is required.
    pub fn label(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.label = ::std::option::Option::Some(input.into());
        self
    }

    /// Display label for the option.
    pub fn set_label(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.label = input;
        self
    }

    /// Display label for the option.
    pub fn get_label(&self) -> &::std::option::Option<::std::string::String> {
        &self.label
    }

    /// Value associated with the option.
    /// This field is required.
    pub fn value(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.value = ::std::option::Option::Some(input.into());
        self
    }

    /// Value associated with the option.
    pub fn set_value(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.value = input;
        self
    }

    /// Value associated with the option.
    pub fn get_value(&self) -> &::std::option::Option<::std::string::String> {
        &self.value
    }

    /// Consumes the builder and constructs a
    /// [`ClarificationAnswerOption`](crate::types::ClarificationAnswerOption). This method will
    /// fail if any of the following fields are not set:
    /// - [`label`](crate::types::builders::ClarificationAnswerOptionBuilder::label)
    /// - [`value`](crate::types::builders::ClarificationAnswerOptionBuilder::value)
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::types::ClarificationAnswerOption, ::aws_smithy_types::error::operation::BuildError>
    {
        ::std::result::Result::Ok(crate::types::ClarificationAnswerOption {
            label: self.label.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "label",
                    "label was not specified but it is required when building ClarificationAnswerOption",
                )
            })?,
            value: self.value.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "value",
                    "value was not specified but it is required when building ClarificationAnswerOption",
                )
            })?,
        })
    }
}
impl ::std::fmt::Debug for ClarificationAnswerOptionBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("ClarificationAnswerOptionBuilder");
        formatter.field("label", &"*** Sensitive Data Redacted ***");
        formatter.field("value", &"*** Sensitive Data Redacted ***");
        formatter.finish()
    }
}
