// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ContextUsageEvent {
    /// Percentage of model context window used (0-100). Calculated as (totalTokens /
    /// maxContextWindowTokens) * 100
    pub context_usage_percentage: ::std::option::Option<f32>,
}
impl ContextUsageEvent {
    /// Percentage of model context window used (0-100). Calculated as (totalTokens /
    /// maxContextWindowTokens) * 100
    pub fn context_usage_percentage(&self) -> ::std::option::Option<f32> {
        self.context_usage_percentage
    }
}
impl ContextUsageEvent {
    /// Creates a new builder-style object to manufacture
    /// [`ContextUsageEvent`](crate::types::ContextUsageEvent).
    pub fn builder() -> crate::types::builders::ContextUsageEventBuilder {
        crate::types::builders::ContextUsageEventBuilder::default()
    }
}

/// A builder for [`ContextUsageEvent`](crate::types::ContextUsageEvent).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ContextUsageEventBuilder {
    pub(crate) context_usage_percentage: ::std::option::Option<f32>,
}
impl ContextUsageEventBuilder {
    /// Percentage of model context window used (0-100). Calculated as (totalTokens /
    /// maxContextWindowTokens) * 100
    pub fn context_usage_percentage(mut self, input: f32) -> Self {
        self.context_usage_percentage = ::std::option::Option::Some(input);
        self
    }

    /// Percentage of model context window used (0-100). Calculated as (totalTokens /
    /// maxContextWindowTokens) * 100
    pub fn set_context_usage_percentage(mut self, input: ::std::option::Option<f32>) -> Self {
        self.context_usage_percentage = input;
        self
    }

    /// Percentage of model context window used (0-100). Calculated as (totalTokens /
    /// maxContextWindowTokens) * 100
    pub fn get_context_usage_percentage(&self) -> &::std::option::Option<f32> {
        &self.context_usage_percentage
    }

    /// Consumes the builder and constructs a
    /// [`ContextUsageEvent`](crate::types::ContextUsageEvent).
    pub fn build(self) -> crate::types::ContextUsageEvent {
        crate::types::ContextUsageEvent {
            context_usage_percentage: self.context_usage_percentage,
        }
    }
}
