// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub struct DocumentCitationSourceContent {
    #[allow(missing_docs)] // documentation missing in model
    pub text: ::std::option::Option<::std::string::String>,
}
impl DocumentCitationSourceContent {
    #[allow(missing_docs)] // documentation missing in model
    pub fn text(&self) -> ::std::option::Option<&str> {
        self.text.as_deref()
    }
}
impl ::std::fmt::Debug for DocumentCitationSourceContent {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("DocumentCitationSourceContent");
        formatter.field("text", &"*** Sensitive Data Redacted ***");
        formatter.finish()
    }
}
impl DocumentCitationSourceContent {
    /// Creates a new builder-style object to manufacture
    /// [`DocumentCitationSourceContent`](crate::types::DocumentCitationSourceContent).
    pub fn builder() -> crate::types::builders::DocumentCitationSourceContentBuilder {
        crate::types::builders::DocumentCitationSourceContentBuilder::default()
    }
}

/// A builder for [`DocumentCitationSourceContent`](crate::types::DocumentCitationSourceContent).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default)]
#[non_exhaustive]
pub struct DocumentCitationSourceContentBuilder {
    pub(crate) text: ::std::option::Option<::std::string::String>,
}
impl DocumentCitationSourceContentBuilder {
    #[allow(missing_docs)] // documentation missing in model
    pub fn text(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.text = ::std::option::Option::Some(input.into());
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_text(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.text = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_text(&self) -> &::std::option::Option<::std::string::String> {
        &self.text
    }

    /// Consumes the builder and constructs a
    /// [`DocumentCitationSourceContent`](crate::types::DocumentCitationSourceContent).
    pub fn build(self) -> crate::types::DocumentCitationSourceContent {
        crate::types::DocumentCitationSourceContent { text: self.text }
    }
}
impl ::std::fmt::Debug for DocumentCitationSourceContentBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("DocumentCitationSourceContentBuilder");
        formatter.field("text", &"*** Sensitive Data Redacted ***");
        formatter.finish()
    }
}
