// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Streaming response event for document citations from Bedrock
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub struct DocumentCitationEvent {
    #[allow(missing_docs)] // documentation missing in model
    pub source: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub title: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub location: ::std::option::Option<crate::types::DocumentCitationLocation>,
    #[allow(missing_docs)] // documentation missing in model
    pub source_content: ::std::option::Option<::std::vec::Vec<crate::types::DocumentCitationSourceContent>>,
}
impl DocumentCitationEvent {
    #[allow(missing_docs)] // documentation missing in model
    pub fn source(&self) -> ::std::option::Option<&str> {
        self.source.as_deref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn title(&self) -> ::std::option::Option<&str> {
        self.title.as_deref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn location(&self) -> ::std::option::Option<&crate::types::DocumentCitationLocation> {
        self.location.as_ref()
    }

    #[allow(missing_docs)] // documentation missing in model
    /// If no value was sent for this field, a default will be set. If you want to determine if no
    /// value was sent, use `.source_content.is_none()`.
    pub fn source_content(&self) -> &[crate::types::DocumentCitationSourceContent] {
        self.source_content.as_deref().unwrap_or_default()
    }
}
impl ::std::fmt::Debug for DocumentCitationEvent {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("DocumentCitationEvent");
        formatter.field("source", &"*** Sensitive Data Redacted ***");
        formatter.field("title", &"*** Sensitive Data Redacted ***");
        formatter.field("location", &self.location);
        formatter.field("source_content", &self.source_content);
        formatter.finish()
    }
}
impl DocumentCitationEvent {
    /// Creates a new builder-style object to manufacture
    /// [`DocumentCitationEvent`](crate::types::DocumentCitationEvent).
    pub fn builder() -> crate::types::builders::DocumentCitationEventBuilder {
        crate::types::builders::DocumentCitationEventBuilder::default()
    }
}

/// A builder for [`DocumentCitationEvent`](crate::types::DocumentCitationEvent).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default)]
#[non_exhaustive]
pub struct DocumentCitationEventBuilder {
    pub(crate) source: ::std::option::Option<::std::string::String>,
    pub(crate) title: ::std::option::Option<::std::string::String>,
    pub(crate) location: ::std::option::Option<crate::types::DocumentCitationLocation>,
    pub(crate) source_content: ::std::option::Option<::std::vec::Vec<crate::types::DocumentCitationSourceContent>>,
}
impl DocumentCitationEventBuilder {
    #[allow(missing_docs)] // documentation missing in model
    pub fn source(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.source = ::std::option::Option::Some(input.into());
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_source(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.source = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_source(&self) -> &::std::option::Option<::std::string::String> {
        &self.source
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn title(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.title = ::std::option::Option::Some(input.into());
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_title(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.title = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_title(&self) -> &::std::option::Option<::std::string::String> {
        &self.title
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn location(mut self, input: crate::types::DocumentCitationLocation) -> Self {
        self.location = ::std::option::Option::Some(input);
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_location(mut self, input: ::std::option::Option<crate::types::DocumentCitationLocation>) -> Self {
        self.location = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_location(&self) -> &::std::option::Option<crate::types::DocumentCitationLocation> {
        &self.location
    }

    /// Appends an item to `source_content`.
    ///
    /// To override the contents of this collection use
    /// [`set_source_content`](Self::set_source_content).
    pub fn source_content(mut self, input: crate::types::DocumentCitationSourceContent) -> Self {
        let mut v = self.source_content.unwrap_or_default();
        v.push(input);
        self.source_content = ::std::option::Option::Some(v);
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_source_content(
        mut self,
        input: ::std::option::Option<::std::vec::Vec<crate::types::DocumentCitationSourceContent>>,
    ) -> Self {
        self.source_content = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_source_content(
        &self,
    ) -> &::std::option::Option<::std::vec::Vec<crate::types::DocumentCitationSourceContent>> {
        &self.source_content
    }

    /// Consumes the builder and constructs a
    /// [`DocumentCitationEvent`](crate::types::DocumentCitationEvent).
    pub fn build(self) -> crate::types::DocumentCitationEvent {
        crate::types::DocumentCitationEvent {
            source: self.source,
            title: self.title,
            location: self.location,
            source_content: self.source_content,
        }
    }
}
impl ::std::fmt::Debug for DocumentCitationEventBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("DocumentCitationEventBuilder");
        formatter.field("source", &"*** Sensitive Data Redacted ***");
        formatter.field("title", &"*** Sensitive Data Redacted ***");
        formatter.field("location", &self.location);
        formatter.field("source_content", &self.source_content);
        formatter.finish()
    }
}
