// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DocumentCitationSpan {
    #[allow(missing_docs)] // documentation missing in model
    pub document_index: ::std::option::Option<i32>,
    #[allow(missing_docs)] // documentation missing in model
    pub start: ::std::option::Option<i32>,
    #[allow(missing_docs)] // documentation missing in model
    pub end: ::std::option::Option<i32>,
}
impl DocumentCitationSpan {
    #[allow(missing_docs)] // documentation missing in model
    pub fn document_index(&self) -> ::std::option::Option<i32> {
        self.document_index
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn start(&self) -> ::std::option::Option<i32> {
        self.start
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn end(&self) -> ::std::option::Option<i32> {
        self.end
    }
}
impl DocumentCitationSpan {
    /// Creates a new builder-style object to manufacture
    /// [`DocumentCitationSpan`](crate::types::DocumentCitationSpan).
    pub fn builder() -> crate::types::builders::DocumentCitationSpanBuilder {
        crate::types::builders::DocumentCitationSpanBuilder::default()
    }
}

/// A builder for [`DocumentCitationSpan`](crate::types::DocumentCitationSpan).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct DocumentCitationSpanBuilder {
    pub(crate) document_index: ::std::option::Option<i32>,
    pub(crate) start: ::std::option::Option<i32>,
    pub(crate) end: ::std::option::Option<i32>,
}
impl DocumentCitationSpanBuilder {
    #[allow(missing_docs)] // documentation missing in model
    pub fn document_index(mut self, input: i32) -> Self {
        self.document_index = ::std::option::Option::Some(input);
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_document_index(mut self, input: ::std::option::Option<i32>) -> Self {
        self.document_index = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_document_index(&self) -> &::std::option::Option<i32> {
        &self.document_index
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn start(mut self, input: i32) -> Self {
        self.start = ::std::option::Option::Some(input);
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_start(mut self, input: ::std::option::Option<i32>) -> Self {
        self.start = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_start(&self) -> &::std::option::Option<i32> {
        &self.start
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn end(mut self, input: i32) -> Self {
        self.end = ::std::option::Option::Some(input);
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_end(mut self, input: ::std::option::Option<i32>) -> Self {
        self.end = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_end(&self) -> &::std::option::Option<i32> {
        &self.end
    }

    /// Consumes the builder and constructs a
    /// [`DocumentCitationSpan`](crate::types::DocumentCitationSpan).
    pub fn build(self) -> crate::types::DocumentCitationSpan {
        crate::types::DocumentCitationSpan {
            document_index: self.document_index,
            start: self.start,
            end: self.end,
        }
    }
}
