// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Structure representing an inline artifact component.
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub struct InlineArtifact {
    /// DSL to pass to Tela interpreter.
    pub dsl: ::std::string::String,
    /// Summary of the inline artifact.
    pub summary: ::std::string::String,
    /// Title of the inline artifact.
    pub title: ::std::string::String,
    /// Label of the inline artifact.
    pub artifact_label: ::std::string::String,
}
impl InlineArtifact {
    /// DSL to pass to Tela interpreter.
    pub fn dsl(&self) -> &str {
        use std::ops::Deref;
        self.dsl.deref()
    }

    /// Summary of the inline artifact.
    pub fn summary(&self) -> &str {
        use std::ops::Deref;
        self.summary.deref()
    }

    /// Title of the inline artifact.
    pub fn title(&self) -> &str {
        use std::ops::Deref;
        self.title.deref()
    }

    /// Label of the inline artifact.
    pub fn artifact_label(&self) -> &str {
        use std::ops::Deref;
        self.artifact_label.deref()
    }
}
impl ::std::fmt::Debug for InlineArtifact {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("InlineArtifact");
        formatter.field("dsl", &"*** Sensitive Data Redacted ***");
        formatter.field("summary", &"*** Sensitive Data Redacted ***");
        formatter.field("title", &"*** Sensitive Data Redacted ***");
        formatter.field("artifact_label", &"*** Sensitive Data Redacted ***");
        formatter.finish()
    }
}
impl InlineArtifact {
    /// Creates a new builder-style object to manufacture
    /// [`InlineArtifact`](crate::types::InlineArtifact).
    pub fn builder() -> crate::types::builders::InlineArtifactBuilder {
        crate::types::builders::InlineArtifactBuilder::default()
    }
}

/// A builder for [`InlineArtifact`](crate::types::InlineArtifact).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default)]
#[non_exhaustive]
pub struct InlineArtifactBuilder {
    pub(crate) dsl: ::std::option::Option<::std::string::String>,
    pub(crate) summary: ::std::option::Option<::std::string::String>,
    pub(crate) title: ::std::option::Option<::std::string::String>,
    pub(crate) artifact_label: ::std::option::Option<::std::string::String>,
}
impl InlineArtifactBuilder {
    /// DSL to pass to Tela interpreter.
    /// This field is required.
    pub fn dsl(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.dsl = ::std::option::Option::Some(input.into());
        self
    }

    /// DSL to pass to Tela interpreter.
    pub fn set_dsl(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.dsl = input;
        self
    }

    /// DSL to pass to Tela interpreter.
    pub fn get_dsl(&self) -> &::std::option::Option<::std::string::String> {
        &self.dsl
    }

    /// Summary of the inline artifact.
    /// This field is required.
    pub fn summary(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.summary = ::std::option::Option::Some(input.into());
        self
    }

    /// Summary of the inline artifact.
    pub fn set_summary(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.summary = input;
        self
    }

    /// Summary of the inline artifact.
    pub fn get_summary(&self) -> &::std::option::Option<::std::string::String> {
        &self.summary
    }

    /// Title of the inline artifact.
    /// This field is required.
    pub fn title(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.title = ::std::option::Option::Some(input.into());
        self
    }

    /// Title of the inline artifact.
    pub fn set_title(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.title = input;
        self
    }

    /// Title of the inline artifact.
    pub fn get_title(&self) -> &::std::option::Option<::std::string::String> {
        &self.title
    }

    /// Label of the inline artifact.
    /// This field is required.
    pub fn artifact_label(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.artifact_label = ::std::option::Option::Some(input.into());
        self
    }

    /// Label of the inline artifact.
    pub fn set_artifact_label(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.artifact_label = input;
        self
    }

    /// Label of the inline artifact.
    pub fn get_artifact_label(&self) -> &::std::option::Option<::std::string::String> {
        &self.artifact_label
    }

    /// Consumes the builder and constructs a [`InlineArtifact`](crate::types::InlineArtifact).
    /// This method will fail if any of the following fields are not set:
    /// - [`dsl`](crate::types::builders::InlineArtifactBuilder::dsl)
    /// - [`summary`](crate::types::builders::InlineArtifactBuilder::summary)
    /// - [`title`](crate::types::builders::InlineArtifactBuilder::title)
    /// - [`artifact_label`](crate::types::builders::InlineArtifactBuilder::artifact_label)
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::types::InlineArtifact, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::InlineArtifact {
            dsl: self.dsl.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "dsl",
                    "dsl was not specified but it is required when building InlineArtifact",
                )
            })?,
            summary: self.summary.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "summary",
                    "summary was not specified but it is required when building InlineArtifact",
                )
            })?,
            title: self.title.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "title",
                    "title was not specified but it is required when building InlineArtifact",
                )
            })?,
            artifact_label: self.artifact_label.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "artifact_label",
                    "artifact_label was not specified but it is required when building InlineArtifact",
                )
            })?,
        })
    }
}
impl ::std::fmt::Debug for InlineArtifactBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("InlineArtifactBuilder");
        formatter.field("dsl", &"*** Sensitive Data Redacted ***");
        formatter.field("summary", &"*** Sensitive Data Redacted ***");
        formatter.field("title", &"*** Sensitive Data Redacted ***");
        formatter.field("artifact_label", &"*** Sensitive Data Redacted ***");
        formatter.finish()
    }
}
