// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Structure representing a clarification interaction that presents the user with one or more steps
/// of options to choose from.
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct QClarification {
    /// Ordered list of clarification steps.
    pub questions: ::std::vec::Vec<crate::types::ClarificationQuestion>,
    /// Whether the user can dismiss the clarification.
    pub dismissible: ::std::option::Option<bool>,
}
impl QClarification {
    /// Ordered list of clarification steps.
    pub fn questions(&self) -> &[crate::types::ClarificationQuestion] {
        use std::ops::Deref;
        self.questions.deref()
    }

    /// Whether the user can dismiss the clarification.
    pub fn dismissible(&self) -> ::std::option::Option<bool> {
        self.dismissible
    }
}
impl QClarification {
    /// Creates a new builder-style object to manufacture
    /// [`QClarification`](crate::types::QClarification).
    pub fn builder() -> crate::types::builders::QClarificationBuilder {
        crate::types::builders::QClarificationBuilder::default()
    }
}

/// A builder for [`QClarification`](crate::types::QClarification).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct QClarificationBuilder {
    pub(crate) questions: ::std::option::Option<::std::vec::Vec<crate::types::ClarificationQuestion>>,
    pub(crate) dismissible: ::std::option::Option<bool>,
}
impl QClarificationBuilder {
    /// Appends an item to `questions`.
    ///
    /// To override the contents of this collection use [`set_questions`](Self::set_questions).
    ///
    /// Ordered list of clarification steps.
    pub fn questions(mut self, input: crate::types::ClarificationQuestion) -> Self {
        let mut v = self.questions.unwrap_or_default();
        v.push(input);
        self.questions = ::std::option::Option::Some(v);
        self
    }

    /// Ordered list of clarification steps.
    pub fn set_questions(
        mut self,
        input: ::std::option::Option<::std::vec::Vec<crate::types::ClarificationQuestion>>,
    ) -> Self {
        self.questions = input;
        self
    }

    /// Ordered list of clarification steps.
    pub fn get_questions(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::ClarificationQuestion>> {
        &self.questions
    }

    /// Whether the user can dismiss the clarification.
    pub fn dismissible(mut self, input: bool) -> Self {
        self.dismissible = ::std::option::Option::Some(input);
        self
    }

    /// Whether the user can dismiss the clarification.
    pub fn set_dismissible(mut self, input: ::std::option::Option<bool>) -> Self {
        self.dismissible = input;
        self
    }

    /// Whether the user can dismiss the clarification.
    pub fn get_dismissible(&self) -> &::std::option::Option<bool> {
        &self.dismissible
    }

    /// Consumes the builder and constructs a [`QClarification`](crate::types::QClarification).
    /// This method will fail if any of the following fields are not set:
    /// - [`questions`](crate::types::builders::QClarificationBuilder::questions)
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::types::QClarification, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::QClarification {
            questions: self.questions.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "questions",
                    "questions was not specified but it is required when building QClarification",
                )
            })?,
            dismissible: self.dismissible,
        })
    }
}
