// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// When writing a match expression against `RefusalCategory`, it is important to ensure
/// your code is forward-compatible. That is, if a match arm handles a case for a
/// feature that is supported by the service but has not been represented as an enum
/// variant in a current version of SDK, your code should continue to work when you
/// upgrade SDK to a future version in which the enum does include a variant for that
/// feature.
///
/// Here is an example of how you can make a match expression forward-compatible:
///
/// ```text
/// # let refusalcategory = unimplemented!();
/// match refusalcategory {
///     RefusalCategory::Bio => { /* ... */ },
///     RefusalCategory::Cyber => { /* ... */ },
///     RefusalCategory::FrontierLlm => { /* ... */ },
///     RefusalCategory::ReasoningExtraction => { /* ... */ },
///     RefusalCategory::UnknownValue => { /* ... */ },
///     other @ _ if other.as_str() == "NewFeature" => { /* handles a case for `NewFeature` */ },
///     _ => { /* ... */ },
/// }
/// ```
/// The above code demonstrates that when `refusalcategory` represents
/// `NewFeature`, the execution path will lead to the second last match arm,
/// even though the enum does not contain a variant `RefusalCategory::NewFeature`
/// in the current version of SDK. The reason is that the variable `other`,
/// created by the `@` operator, is bound to
/// `RefusalCategory::Unknown(UnknownVariantValue("NewFeature".to_owned()))`
/// and calling `as_str` on it yields `"NewFeature"`.
/// This match expression is forward-compatible when executed with a newer
/// version of SDK where the variant `RefusalCategory::NewFeature` is defined.
/// Specifically, when `refusalcategory` represents `NewFeature`,
/// the execution path will hit the second last match arm as before by virtue of
/// calling `as_str` on `RefusalCategory::NewFeature` also yielding `"NewFeature"`.
///
/// Explicitly matching on the `Unknown` variant should
/// be avoided for two reasons:
/// - The inner data `UnknownVariantValue` is opaque, and no further information can be extracted.
/// - It might inadvertently shadow other intended match arms.
///
/// The category of content filtering that triggered the refusal
///
/// _Note: `RefusalCategory::Unknown` has been renamed to `::UnknownValue`._
#[non_exhaustive]
#[derive(
    ::std::clone::Clone,
    ::std::cmp::Eq,
    ::std::cmp::Ord,
    ::std::cmp::PartialEq,
    ::std::cmp::PartialOrd,
    ::std::fmt::Debug,
    ::std::hash::Hash,
)]
pub enum RefusalCategory {
    /// The request could enable biological harm
    Bio,
    /// The request could enable cyber harm
    Cyber,
    /// The request could assist development of competing AI models
    FrontierLlm,
    /// The request attempts to extract the model's internal reasoning
    ReasoningExtraction,
    /// An unrecognized category was returned by the provider
    ///
    /// _Note: `::Unknown` has been renamed to `::UnknownValue`._
    UnknownValue,
    /// `Unknown` contains new variants that have been added since this code was generated.
    #[deprecated(
        note = "Don't directly match on `Unknown`. See the docs on this enum for the correct way to handle unknown variants."
    )]
    Unknown(crate::primitives::sealed_enum_unknown::UnknownVariantValue),
}
impl ::std::convert::From<&str> for RefusalCategory {
    fn from(s: &str) -> Self {
        match s {
            "BIO" => RefusalCategory::Bio,
            "CYBER" => RefusalCategory::Cyber,
            "FRONTIER_LLM" => RefusalCategory::FrontierLlm,
            "REASONING_EXTRACTION" => RefusalCategory::ReasoningExtraction,
            "UNKNOWN" => RefusalCategory::UnknownValue,
            other => RefusalCategory::Unknown(crate::primitives::sealed_enum_unknown::UnknownVariantValue(
                other.to_owned(),
            )),
        }
    }
}
impl ::std::str::FromStr for RefusalCategory {
    type Err = ::std::convert::Infallible;

    fn from_str(s: &str) -> ::std::result::Result<Self, <Self as ::std::str::FromStr>::Err> {
        ::std::result::Result::Ok(RefusalCategory::from(s))
    }
}
impl RefusalCategory {
    /// Returns the `&str` value of the enum member.
    pub fn as_str(&self) -> &str {
        match self {
            RefusalCategory::Bio => "BIO",
            RefusalCategory::Cyber => "CYBER",
            RefusalCategory::FrontierLlm => "FRONTIER_LLM",
            RefusalCategory::ReasoningExtraction => "REASONING_EXTRACTION",
            RefusalCategory::UnknownValue => "UNKNOWN",
            RefusalCategory::Unknown(value) => value.as_str(),
        }
    }

    /// Returns all the `&str` representations of the enum members.
    pub const fn values() -> &'static [&'static str] {
        &["BIO", "CYBER", "FRONTIER_LLM", "REASONING_EXTRACTION", "UNKNOWN"]
    }
}
impl ::std::convert::AsRef<str> for RefusalCategory {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}
impl RefusalCategory {
    /// Parses the enum value while disallowing unknown variants.
    ///
    /// Unknown variants will result in an error.
    pub fn try_parse(value: &str) -> ::std::result::Result<Self, crate::error::UnknownVariantError> {
        match Self::from(value) {
            #[allow(deprecated)]
            Self::Unknown(_) => ::std::result::Result::Err(crate::error::UnknownVariantError::new(value)),
            known => Ok(known),
        }
    }
}
impl ::std::fmt::Display for RefusalCategory {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        match self {
            RefusalCategory::Bio => write!(f, "BIO"),
            RefusalCategory::Cyber => write!(f, "CYBER"),
            RefusalCategory::FrontierLlm => write!(f, "FRONTIER_LLM"),
            RefusalCategory::ReasoningExtraction => write!(f, "REASONING_EXTRACTION"),
            RefusalCategory::UnknownValue => write!(f, "UNKNOWN"),
            RefusalCategory::Unknown(value) => write!(f, "{value}"),
        }
    }
}
