// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct AddOnMetadata {
    /// Active add-ons (top 5 in FIFO order by purchase date)
    pub add_ons: ::std::option::Option<::std::vec::Vec<crate::types::AddOn>>,
    /// Total limit granted across add-ons active in the current billing month
    pub add_on_total_limit: ::std::option::Option<f64>,
    /// Total usage consumed across add-ons active in the current billing month
    pub add_on_total_usage: ::std::option::Option<f64>,
}
impl AddOnMetadata {
    /// Active add-ons (top 5 in FIFO order by purchase date)
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no
    /// value was sent, use `.add_ons.is_none()`.
    pub fn add_ons(&self) -> &[crate::types::AddOn] {
        self.add_ons.as_deref().unwrap_or_default()
    }

    /// Total limit granted across add-ons active in the current billing month
    pub fn add_on_total_limit(&self) -> ::std::option::Option<f64> {
        self.add_on_total_limit
    }

    /// Total usage consumed across add-ons active in the current billing month
    pub fn add_on_total_usage(&self) -> ::std::option::Option<f64> {
        self.add_on_total_usage
    }
}
impl AddOnMetadata {
    /// Creates a new builder-style object to manufacture
    /// [`AddOnMetadata`](crate::types::AddOnMetadata).
    pub fn builder() -> crate::types::builders::AddOnMetadataBuilder {
        crate::types::builders::AddOnMetadataBuilder::default()
    }
}

/// A builder for [`AddOnMetadata`](crate::types::AddOnMetadata).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct AddOnMetadataBuilder {
    pub(crate) add_ons: ::std::option::Option<::std::vec::Vec<crate::types::AddOn>>,
    pub(crate) add_on_total_limit: ::std::option::Option<f64>,
    pub(crate) add_on_total_usage: ::std::option::Option<f64>,
}
impl AddOnMetadataBuilder {
    /// Appends an item to `add_ons`.
    ///
    /// To override the contents of this collection use [`set_add_ons`](Self::set_add_ons).
    ///
    /// Active add-ons (top 5 in FIFO order by purchase date)
    pub fn add_ons(mut self, input: crate::types::AddOn) -> Self {
        let mut v = self.add_ons.unwrap_or_default();
        v.push(input);
        self.add_ons = ::std::option::Option::Some(v);
        self
    }

    /// Active add-ons (top 5 in FIFO order by purchase date)
    pub fn set_add_ons(mut self, input: ::std::option::Option<::std::vec::Vec<crate::types::AddOn>>) -> Self {
        self.add_ons = input;
        self
    }

    /// Active add-ons (top 5 in FIFO order by purchase date)
    pub fn get_add_ons(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::AddOn>> {
        &self.add_ons
    }

    /// Total limit granted across add-ons active in the current billing month
    pub fn add_on_total_limit(mut self, input: f64) -> Self {
        self.add_on_total_limit = ::std::option::Option::Some(input);
        self
    }

    /// Total limit granted across add-ons active in the current billing month
    pub fn set_add_on_total_limit(mut self, input: ::std::option::Option<f64>) -> Self {
        self.add_on_total_limit = input;
        self
    }

    /// Total limit granted across add-ons active in the current billing month
    pub fn get_add_on_total_limit(&self) -> &::std::option::Option<f64> {
        &self.add_on_total_limit
    }

    /// Total usage consumed across add-ons active in the current billing month
    pub fn add_on_total_usage(mut self, input: f64) -> Self {
        self.add_on_total_usage = ::std::option::Option::Some(input);
        self
    }

    /// Total usage consumed across add-ons active in the current billing month
    pub fn set_add_on_total_usage(mut self, input: ::std::option::Option<f64>) -> Self {
        self.add_on_total_usage = input;
        self
    }

    /// Total usage consumed across add-ons active in the current billing month
    pub fn get_add_on_total_usage(&self) -> &::std::option::Option<f64> {
        &self.add_on_total_usage
    }

    /// Consumes the builder and constructs a [`AddOnMetadata`](crate::types::AddOnMetadata).
    pub fn build(self) -> crate::types::AddOnMetadata {
        crate::types::AddOnMetadata {
            add_ons: self.add_ons,
            add_on_total_limit: self.add_on_total_limit,
            add_on_total_usage: self.add_on_total_usage,
        }
    }
}
