// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct Bonus {
    /// Bonus Code
    pub bonus_code: ::std::string::String,
    /// Display name of the bonus code
    pub display_name: ::std::string::String,
    /// Description of the bonus code
    pub description: ::std::string::String,
    /// Status of the Bonus for this customer
    pub status: crate::types::BonusStatus,
    /// Unix timestamp of free trial expiry in seconds
    pub expires_at: ::aws_smithy_types::DateTime,
    /// Unix timestamp of free trial expiry in seconds
    pub redeemed_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    /// Current Bonus usage with Precision
    pub current_usage: f64,
    /// Bonus usage limit with Precision
    pub usage_limit: f64,
}
impl Bonus {
    /// Bonus Code
    pub fn bonus_code(&self) -> &str {
        use std::ops::Deref;
        self.bonus_code.deref()
    }

    /// Display name of the bonus code
    pub fn display_name(&self) -> &str {
        use std::ops::Deref;
        self.display_name.deref()
    }

    /// Description of the bonus code
    pub fn description(&self) -> &str {
        use std::ops::Deref;
        self.description.deref()
    }

    /// Status of the Bonus for this customer
    pub fn status(&self) -> &crate::types::BonusStatus {
        &self.status
    }

    /// Unix timestamp of free trial expiry in seconds
    pub fn expires_at(&self) -> &::aws_smithy_types::DateTime {
        &self.expires_at
    }

    /// Unix timestamp of free trial expiry in seconds
    pub fn redeemed_at(&self) -> ::std::option::Option<&::aws_smithy_types::DateTime> {
        self.redeemed_at.as_ref()
    }

    /// Current Bonus usage with Precision
    pub fn current_usage(&self) -> f64 {
        self.current_usage
    }

    /// Bonus usage limit with Precision
    pub fn usage_limit(&self) -> f64 {
        self.usage_limit
    }
}
impl Bonus {
    /// Creates a new builder-style object to manufacture [`Bonus`](crate::types::Bonus).
    pub fn builder() -> crate::types::builders::BonusBuilder {
        crate::types::builders::BonusBuilder::default()
    }
}

/// A builder for [`Bonus`](crate::types::Bonus).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct BonusBuilder {
    pub(crate) bonus_code: ::std::option::Option<::std::string::String>,
    pub(crate) display_name: ::std::option::Option<::std::string::String>,
    pub(crate) description: ::std::option::Option<::std::string::String>,
    pub(crate) status: ::std::option::Option<crate::types::BonusStatus>,
    pub(crate) expires_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) redeemed_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) current_usage: ::std::option::Option<f64>,
    pub(crate) usage_limit: ::std::option::Option<f64>,
}
impl BonusBuilder {
    /// Bonus Code
    /// This field is required.
    pub fn bonus_code(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.bonus_code = ::std::option::Option::Some(input.into());
        self
    }

    /// Bonus Code
    pub fn set_bonus_code(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.bonus_code = input;
        self
    }

    /// Bonus Code
    pub fn get_bonus_code(&self) -> &::std::option::Option<::std::string::String> {
        &self.bonus_code
    }

    /// Display name of the bonus code
    /// This field is required.
    pub fn display_name(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.display_name = ::std::option::Option::Some(input.into());
        self
    }

    /// Display name of the bonus code
    pub fn set_display_name(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.display_name = input;
        self
    }

    /// Display name of the bonus code
    pub fn get_display_name(&self) -> &::std::option::Option<::std::string::String> {
        &self.display_name
    }

    /// Description of the bonus code
    /// This field is required.
    pub fn description(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.description = ::std::option::Option::Some(input.into());
        self
    }

    /// Description of the bonus code
    pub fn set_description(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.description = input;
        self
    }

    /// Description of the bonus code
    pub fn get_description(&self) -> &::std::option::Option<::std::string::String> {
        &self.description
    }

    /// Status of the Bonus for this customer
    /// This field is required.
    pub fn status(mut self, input: crate::types::BonusStatus) -> Self {
        self.status = ::std::option::Option::Some(input);
        self
    }

    /// Status of the Bonus for this customer
    pub fn set_status(mut self, input: ::std::option::Option<crate::types::BonusStatus>) -> Self {
        self.status = input;
        self
    }

    /// Status of the Bonus for this customer
    pub fn get_status(&self) -> &::std::option::Option<crate::types::BonusStatus> {
        &self.status
    }

    /// Unix timestamp of free trial expiry in seconds
    /// This field is required.
    pub fn expires_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.expires_at = ::std::option::Option::Some(input);
        self
    }

    /// Unix timestamp of free trial expiry in seconds
    pub fn set_expires_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.expires_at = input;
        self
    }

    /// Unix timestamp of free trial expiry in seconds
    pub fn get_expires_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.expires_at
    }

    /// Unix timestamp of free trial expiry in seconds
    pub fn redeemed_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.redeemed_at = ::std::option::Option::Some(input);
        self
    }

    /// Unix timestamp of free trial expiry in seconds
    pub fn set_redeemed_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.redeemed_at = input;
        self
    }

    /// Unix timestamp of free trial expiry in seconds
    pub fn get_redeemed_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.redeemed_at
    }

    /// Current Bonus usage with Precision
    /// This field is required.
    pub fn current_usage(mut self, input: f64) -> Self {
        self.current_usage = ::std::option::Option::Some(input);
        self
    }

    /// Current Bonus usage with Precision
    pub fn set_current_usage(mut self, input: ::std::option::Option<f64>) -> Self {
        self.current_usage = input;
        self
    }

    /// Current Bonus usage with Precision
    pub fn get_current_usage(&self) -> &::std::option::Option<f64> {
        &self.current_usage
    }

    /// Bonus usage limit with Precision
    /// This field is required.
    pub fn usage_limit(mut self, input: f64) -> Self {
        self.usage_limit = ::std::option::Option::Some(input);
        self
    }

    /// Bonus usage limit with Precision
    pub fn set_usage_limit(mut self, input: ::std::option::Option<f64>) -> Self {
        self.usage_limit = input;
        self
    }

    /// Bonus usage limit with Precision
    pub fn get_usage_limit(&self) -> &::std::option::Option<f64> {
        &self.usage_limit
    }

    /// Consumes the builder and constructs a [`Bonus`](crate::types::Bonus).
    /// This method will fail if any of the following fields are not set:
    /// - [`bonus_code`](crate::types::builders::BonusBuilder::bonus_code)
    /// - [`display_name`](crate::types::builders::BonusBuilder::display_name)
    /// - [`description`](crate::types::builders::BonusBuilder::description)
    /// - [`status`](crate::types::builders::BonusBuilder::status)
    /// - [`expires_at`](crate::types::builders::BonusBuilder::expires_at)
    /// - [`current_usage`](crate::types::builders::BonusBuilder::current_usage)
    /// - [`usage_limit`](crate::types::builders::BonusBuilder::usage_limit)
    pub fn build(self) -> ::std::result::Result<crate::types::Bonus, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::Bonus {
            bonus_code: self.bonus_code.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "bonus_code",
                    "bonus_code was not specified but it is required when building Bonus",
                )
            })?,
            display_name: self.display_name.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "display_name",
                    "display_name was not specified but it is required when building Bonus",
                )
            })?,
            description: self.description.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "description",
                    "description was not specified but it is required when building Bonus",
                )
            })?,
            status: self.status.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "status",
                    "status was not specified but it is required when building Bonus",
                )
            })?,
            expires_at: self.expires_at.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "expires_at",
                    "expires_at was not specified but it is required when building Bonus",
                )
            })?,
            redeemed_at: self.redeemed_at,
            current_usage: self.current_usage.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "current_usage",
                    "current_usage was not specified but it is required when building Bonus",
                )
            })?,
            usage_limit: self.usage_limit.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "usage_limit",
                    "usage_limit was not specified but it is required when building Bonus",
                )
            })?,
        })
    }
}
