// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// When writing a match expression against `ChatAgentMode`, it is important to ensure
/// your code is forward-compatible. That is, if a match arm handles a case for a
/// feature that is supported by the service but has not been represented as an enum
/// variant in a current version of SDK, your code should continue to work when you
/// upgrade SDK to a future version in which the enum does include a variant for that
/// feature.
///
/// Here is an example of how you can make a match expression forward-compatible:
///
/// ```text
/// # let chatagentmode = unimplemented!();
/// match chatagentmode {
///     ChatAgentMode::Autocomplete => { /* ... */ },
///     ChatAgentMode::ExecuteHook => { /* ... */ },
///     ChatAgentMode::GenerateHook => { /* ... */ },
///     ChatAgentMode::GenerateSteering => { /* ... */ },
///     ChatAgentMode::IntentClassification => { /* ... */ },
///     ChatAgentMode::Other => { /* ... */ },
///     ChatAgentMode::RefineDesign => { /* ... */ },
///     ChatAgentMode::RefineRequirements => { /* ... */ },
///     ChatAgentMode::RefineSteering => { /* ... */ },
///     ChatAgentMode::Spec => { /* ... */ },
///     ChatAgentMode::Summarization => { /* ... */ },
///     ChatAgentMode::UpdateTasks => { /* ... */ },
///     ChatAgentMode::Vibe => { /* ... */ },
///     other @ _ if other.as_str() == "NewFeature" => { /* handles a case for `NewFeature` */ },
///     _ => { /* ... */ },
/// }
/// ```
/// The above code demonstrates that when `chatagentmode` represents
/// `NewFeature`, the execution path will lead to the second last match arm,
/// even though the enum does not contain a variant `ChatAgentMode::NewFeature`
/// in the current version of SDK. The reason is that the variable `other`,
/// created by the `@` operator, is bound to
/// `ChatAgentMode::Unknown(UnknownVariantValue("NewFeature".to_owned()))`
/// and calling `as_str` on it yields `"NewFeature"`.
/// This match expression is forward-compatible when executed with a newer
/// version of SDK where the variant `ChatAgentMode::NewFeature` is defined.
/// Specifically, when `chatagentmode` represents `NewFeature`,
/// the execution path will hit the second last match arm as before by virtue of
/// calling `as_str` on `ChatAgentMode::NewFeature` also yielding `"NewFeature"`.
///
/// Explicitly matching on the `Unknown` variant should
/// be avoided for two reasons:
/// - The inner data `UnknownVariantValue` is opaque, and no further information can be extracted.
/// - It might inadvertently shadow other intended match arms.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(
    ::std::clone::Clone,
    ::std::cmp::Eq,
    ::std::cmp::Ord,
    ::std::cmp::PartialEq,
    ::std::cmp::PartialOrd,
    ::std::fmt::Debug,
    ::std::hash::Hash,
)]
pub enum ChatAgentMode {
    #[allow(missing_docs)] // documentation missing in model
    Autocomplete,
    #[allow(missing_docs)] // documentation missing in model
    ExecuteHook,
    #[allow(missing_docs)] // documentation missing in model
    GenerateHook,
    #[allow(missing_docs)] // documentation missing in model
    GenerateSteering,
    #[allow(missing_docs)] // documentation missing in model
    IntentClassification,
    #[allow(missing_docs)] // documentation missing in model
    Other,
    #[allow(missing_docs)] // documentation missing in model
    RefineDesign,
    #[allow(missing_docs)] // documentation missing in model
    RefineRequirements,
    #[allow(missing_docs)] // documentation missing in model
    RefineSteering,
    #[allow(missing_docs)] // documentation missing in model
    Spec,
    #[allow(missing_docs)] // documentation missing in model
    Summarization,
    #[allow(missing_docs)] // documentation missing in model
    UpdateTasks,
    #[allow(missing_docs)] // documentation missing in model
    Vibe,
    /// `Unknown` contains new variants that have been added since this code was generated.
    #[deprecated(
        note = "Don't directly match on `Unknown`. See the docs on this enum for the correct way to handle unknown variants."
    )]
    Unknown(crate::primitives::sealed_enum_unknown::UnknownVariantValue),
}
impl ::std::convert::From<&str> for ChatAgentMode {
    fn from(s: &str) -> Self {
        match s {
            "AUTOCOMPLETE" => ChatAgentMode::Autocomplete,
            "EXECUTE_HOOK" => ChatAgentMode::ExecuteHook,
            "GENERATE_HOOK" => ChatAgentMode::GenerateHook,
            "GENERATE_STEERING" => ChatAgentMode::GenerateSteering,
            "INTENT_CLASSIFICATION" => ChatAgentMode::IntentClassification,
            "OTHER" => ChatAgentMode::Other,
            "REFINE_DESIGN" => ChatAgentMode::RefineDesign,
            "REFINE_REQUIREMENTS" => ChatAgentMode::RefineRequirements,
            "REFINE_STEERING" => ChatAgentMode::RefineSteering,
            "SPEC" => ChatAgentMode::Spec,
            "SUMMARIZATION" => ChatAgentMode::Summarization,
            "UPDATE_TASKS" => ChatAgentMode::UpdateTasks,
            "VIBE" => ChatAgentMode::Vibe,
            other => ChatAgentMode::Unknown(crate::primitives::sealed_enum_unknown::UnknownVariantValue(
                other.to_owned(),
            )),
        }
    }
}
impl ::std::str::FromStr for ChatAgentMode {
    type Err = ::std::convert::Infallible;

    fn from_str(s: &str) -> ::std::result::Result<Self, <Self as ::std::str::FromStr>::Err> {
        ::std::result::Result::Ok(ChatAgentMode::from(s))
    }
}
impl ChatAgentMode {
    /// Returns the `&str` value of the enum member.
    pub fn as_str(&self) -> &str {
        match self {
            ChatAgentMode::Autocomplete => "AUTOCOMPLETE",
            ChatAgentMode::ExecuteHook => "EXECUTE_HOOK",
            ChatAgentMode::GenerateHook => "GENERATE_HOOK",
            ChatAgentMode::GenerateSteering => "GENERATE_STEERING",
            ChatAgentMode::IntentClassification => "INTENT_CLASSIFICATION",
            ChatAgentMode::Other => "OTHER",
            ChatAgentMode::RefineDesign => "REFINE_DESIGN",
            ChatAgentMode::RefineRequirements => "REFINE_REQUIREMENTS",
            ChatAgentMode::RefineSteering => "REFINE_STEERING",
            ChatAgentMode::Spec => "SPEC",
            ChatAgentMode::Summarization => "SUMMARIZATION",
            ChatAgentMode::UpdateTasks => "UPDATE_TASKS",
            ChatAgentMode::Vibe => "VIBE",
            ChatAgentMode::Unknown(value) => value.as_str(),
        }
    }

    /// Returns all the `&str` representations of the enum members.
    pub const fn values() -> &'static [&'static str] {
        &[
            "AUTOCOMPLETE",
            "EXECUTE_HOOK",
            "GENERATE_HOOK",
            "GENERATE_STEERING",
            "INTENT_CLASSIFICATION",
            "OTHER",
            "REFINE_DESIGN",
            "REFINE_REQUIREMENTS",
            "REFINE_STEERING",
            "SPEC",
            "SUMMARIZATION",
            "UPDATE_TASKS",
            "VIBE",
        ]
    }
}
impl ::std::convert::AsRef<str> for ChatAgentMode {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}
impl ChatAgentMode {
    /// Parses the enum value while disallowing unknown variants.
    ///
    /// Unknown variants will result in an error.
    pub fn try_parse(value: &str) -> ::std::result::Result<Self, crate::error::UnknownVariantError> {
        match Self::from(value) {
            #[allow(deprecated)]
            Self::Unknown(_) => ::std::result::Result::Err(crate::error::UnknownVariantError::new(value)),
            known => Ok(known),
        }
    }
}
impl ::std::fmt::Display for ChatAgentMode {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        match self {
            ChatAgentMode::Autocomplete => write!(f, "AUTOCOMPLETE"),
            ChatAgentMode::ExecuteHook => write!(f, "EXECUTE_HOOK"),
            ChatAgentMode::GenerateHook => write!(f, "GENERATE_HOOK"),
            ChatAgentMode::GenerateSteering => write!(f, "GENERATE_STEERING"),
            ChatAgentMode::IntentClassification => write!(f, "INTENT_CLASSIFICATION"),
            ChatAgentMode::Other => write!(f, "OTHER"),
            ChatAgentMode::RefineDesign => write!(f, "REFINE_DESIGN"),
            ChatAgentMode::RefineRequirements => write!(f, "REFINE_REQUIREMENTS"),
            ChatAgentMode::RefineSteering => write!(f, "REFINE_STEERING"),
            ChatAgentMode::Spec => write!(f, "SPEC"),
            ChatAgentMode::Summarization => write!(f, "SUMMARIZATION"),
            ChatAgentMode::UpdateTasks => write!(f, "UPDATE_TASKS"),
            ChatAgentMode::Vibe => write!(f, "VIBE"),
            ChatAgentMode::Unknown(value) => write!(f, "{value}"),
        }
    }
}
