// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ContinuousLearning {
    #[allow(missing_docs)] // documentation missing in model
    pub toggle: crate::types::OptInFeatureToggle,
}
impl ContinuousLearning {
    #[allow(missing_docs)] // documentation missing in model
    pub fn toggle(&self) -> &crate::types::OptInFeatureToggle {
        &self.toggle
    }
}
impl ContinuousLearning {
    /// Creates a new builder-style object to manufacture
    /// [`ContinuousLearning`](crate::types::ContinuousLearning).
    pub fn builder() -> crate::types::builders::ContinuousLearningBuilder {
        crate::types::builders::ContinuousLearningBuilder::default()
    }
}

/// A builder for [`ContinuousLearning`](crate::types::ContinuousLearning).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ContinuousLearningBuilder {
    pub(crate) toggle: ::std::option::Option<crate::types::OptInFeatureToggle>,
}
impl ContinuousLearningBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn toggle(mut self, input: crate::types::OptInFeatureToggle) -> Self {
        self.toggle = ::std::option::Option::Some(input);
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_toggle(mut self, input: ::std::option::Option<crate::types::OptInFeatureToggle>) -> Self {
        self.toggle = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_toggle(&self) -> &::std::option::Option<crate::types::OptInFeatureToggle> {
        &self.toggle
    }

    /// Consumes the builder and constructs a
    /// [`ContinuousLearning`](crate::types::ContinuousLearning). This method will fail if any
    /// of the following fields are not set:
    /// - [`toggle`](crate::types::builders::ContinuousLearningBuilder::toggle)
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::types::ContinuousLearning, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::ContinuousLearning {
            toggle: self.toggle.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "toggle",
                    "toggle was not specified but it is required when building ContinuousLearning",
                )
            })?,
        })
    }
}
