// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub struct DocumentBlock {
    #[allow(missing_docs)] // documentation missing in model
    pub name: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub format: crate::types::DocumentFormat,
    #[allow(missing_docs)] // documentation missing in model
    pub source: crate::types::DocumentSource,
}
impl DocumentBlock {
    #[allow(missing_docs)] // documentation missing in model
    pub fn name(&self) -> &str {
        use std::ops::Deref;
        self.name.deref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn format(&self) -> &crate::types::DocumentFormat {
        &self.format
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn source(&self) -> &crate::types::DocumentSource {
        &self.source
    }
}
impl ::std::fmt::Debug for DocumentBlock {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("DocumentBlock");
        formatter.field("name", &self.name);
        formatter.field("format", &self.format);
        formatter.field("source", &"*** Sensitive Data Redacted ***");
        formatter.finish()
    }
}
impl DocumentBlock {
    /// Creates a new builder-style object to manufacture
    /// [`DocumentBlock`](crate::types::DocumentBlock).
    pub fn builder() -> crate::types::builders::DocumentBlockBuilder {
        crate::types::builders::DocumentBlockBuilder::default()
    }
}

/// A builder for [`DocumentBlock`](crate::types::DocumentBlock).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default)]
#[non_exhaustive]
pub struct DocumentBlockBuilder {
    pub(crate) name: ::std::option::Option<::std::string::String>,
    pub(crate) format: ::std::option::Option<crate::types::DocumentFormat>,
    pub(crate) source: ::std::option::Option<crate::types::DocumentSource>,
}
impl DocumentBlockBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn name(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.name = ::std::option::Option::Some(input.into());
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_name(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.name = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_name(&self) -> &::std::option::Option<::std::string::String> {
        &self.name
    }

    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn format(mut self, input: crate::types::DocumentFormat) -> Self {
        self.format = ::std::option::Option::Some(input);
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_format(mut self, input: ::std::option::Option<crate::types::DocumentFormat>) -> Self {
        self.format = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_format(&self) -> &::std::option::Option<crate::types::DocumentFormat> {
        &self.format
    }

    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn source(mut self, input: crate::types::DocumentSource) -> Self {
        self.source = ::std::option::Option::Some(input);
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_source(mut self, input: ::std::option::Option<crate::types::DocumentSource>) -> Self {
        self.source = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_source(&self) -> &::std::option::Option<crate::types::DocumentSource> {
        &self.source
    }

    /// Consumes the builder and constructs a [`DocumentBlock`](crate::types::DocumentBlock).
    /// This method will fail if any of the following fields are not set:
    /// - [`name`](crate::types::builders::DocumentBlockBuilder::name)
    /// - [`format`](crate::types::builders::DocumentBlockBuilder::format)
    /// - [`source`](crate::types::builders::DocumentBlockBuilder::source)
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::types::DocumentBlock, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::DocumentBlock {
            name: self.name.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "name",
                    "name was not specified but it is required when building DocumentBlock",
                )
            })?,
            format: self.format.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "format",
                    "format was not specified but it is required when building DocumentBlock",
                )
            })?,
            source: self.source.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "source",
                    "source was not specified but it is required when building DocumentBlock",
                )
            })?,
        })
    }
}
impl ::std::fmt::Debug for DocumentBlockBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("DocumentBlockBuilder");
        formatter.field("name", &self.name);
        formatter.field("format", &self.format);
        formatter.field("source", &"*** Sensitive Data Redacted ***");
        formatter.finish()
    }
}
