// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct OverageCredit {
    /// Credits consumed from this purchased pack
    pub current_usage: f64,
    /// Total credits granted by this purchased pack
    pub usage_limit: f64,
    /// When this credit pack expires
    pub expires_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    /// How this credit pack was acquired
    pub source: ::std::option::Option<::std::string::String>,
}
impl OverageCredit {
    /// Credits consumed from this purchased pack
    pub fn current_usage(&self) -> f64 {
        self.current_usage
    }

    /// Total credits granted by this purchased pack
    pub fn usage_limit(&self) -> f64 {
        self.usage_limit
    }

    /// When this credit pack expires
    pub fn expires_at(&self) -> ::std::option::Option<&::aws_smithy_types::DateTime> {
        self.expires_at.as_ref()
    }

    /// How this credit pack was acquired
    pub fn source(&self) -> ::std::option::Option<&str> {
        self.source.as_deref()
    }
}
impl OverageCredit {
    /// Creates a new builder-style object to manufacture
    /// [`OverageCredit`](crate::types::OverageCredit).
    pub fn builder() -> crate::types::builders::OverageCreditBuilder {
        crate::types::builders::OverageCreditBuilder::default()
    }
}

/// A builder for [`OverageCredit`](crate::types::OverageCredit).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct OverageCreditBuilder {
    pub(crate) current_usage: ::std::option::Option<f64>,
    pub(crate) usage_limit: ::std::option::Option<f64>,
    pub(crate) expires_at: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) source: ::std::option::Option<::std::string::String>,
}
impl OverageCreditBuilder {
    /// Credits consumed from this purchased pack
    /// This field is required.
    pub fn current_usage(mut self, input: f64) -> Self {
        self.current_usage = ::std::option::Option::Some(input);
        self
    }

    /// Credits consumed from this purchased pack
    pub fn set_current_usage(mut self, input: ::std::option::Option<f64>) -> Self {
        self.current_usage = input;
        self
    }

    /// Credits consumed from this purchased pack
    pub fn get_current_usage(&self) -> &::std::option::Option<f64> {
        &self.current_usage
    }

    /// Total credits granted by this purchased pack
    /// This field is required.
    pub fn usage_limit(mut self, input: f64) -> Self {
        self.usage_limit = ::std::option::Option::Some(input);
        self
    }

    /// Total credits granted by this purchased pack
    pub fn set_usage_limit(mut self, input: ::std::option::Option<f64>) -> Self {
        self.usage_limit = input;
        self
    }

    /// Total credits granted by this purchased pack
    pub fn get_usage_limit(&self) -> &::std::option::Option<f64> {
        &self.usage_limit
    }

    /// When this credit pack expires
    pub fn expires_at(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.expires_at = ::std::option::Option::Some(input);
        self
    }

    /// When this credit pack expires
    pub fn set_expires_at(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.expires_at = input;
        self
    }

    /// When this credit pack expires
    pub fn get_expires_at(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.expires_at
    }

    /// How this credit pack was acquired
    pub fn source(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.source = ::std::option::Option::Some(input.into());
        self
    }

    /// How this credit pack was acquired
    pub fn set_source(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.source = input;
        self
    }

    /// How this credit pack was acquired
    pub fn get_source(&self) -> &::std::option::Option<::std::string::String> {
        &self.source
    }

    /// Consumes the builder and constructs a [`OverageCredit`](crate::types::OverageCredit).
    /// This method will fail if any of the following fields are not set:
    /// - [`current_usage`](crate::types::builders::OverageCreditBuilder::current_usage)
    /// - [`usage_limit`](crate::types::builders::OverageCreditBuilder::usage_limit)
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::types::OverageCredit, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::OverageCredit {
            current_usage: self.current_usage.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "current_usage",
                    "current_usage was not specified but it is required when building OverageCredit",
                )
            })?,
            usage_limit: self.usage_limit.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "usage_limit",
                    "usage_limit was not specified but it is required when building OverageCredit",
                )
            })?,
            expires_at: self.expires_at,
            source: self.source,
        })
    }
}
