// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct TotalUsage {
    /// Maximum overage limit allowed
    pub max_overage_limit: ::std::option::Option<f64>,
    /// Current overage limit
    pub overage_limit: ::std::option::Option<f64>,
    /// Total overage charges incurred
    pub total_overage_charges: ::std::option::Option<f64>,
}
impl TotalUsage {
    /// Maximum overage limit allowed
    pub fn max_overage_limit(&self) -> ::std::option::Option<f64> {
        self.max_overage_limit
    }

    /// Current overage limit
    pub fn overage_limit(&self) -> ::std::option::Option<f64> {
        self.overage_limit
    }

    /// Total overage charges incurred
    pub fn total_overage_charges(&self) -> ::std::option::Option<f64> {
        self.total_overage_charges
    }
}
impl TotalUsage {
    /// Creates a new builder-style object to manufacture [`TotalUsage`](crate::types::TotalUsage).
    pub fn builder() -> crate::types::builders::TotalUsageBuilder {
        crate::types::builders::TotalUsageBuilder::default()
    }
}

/// A builder for [`TotalUsage`](crate::types::TotalUsage).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct TotalUsageBuilder {
    pub(crate) max_overage_limit: ::std::option::Option<f64>,
    pub(crate) overage_limit: ::std::option::Option<f64>,
    pub(crate) total_overage_charges: ::std::option::Option<f64>,
}
impl TotalUsageBuilder {
    /// Maximum overage limit allowed
    pub fn max_overage_limit(mut self, input: f64) -> Self {
        self.max_overage_limit = ::std::option::Option::Some(input);
        self
    }

    /// Maximum overage limit allowed
    pub fn set_max_overage_limit(mut self, input: ::std::option::Option<f64>) -> Self {
        self.max_overage_limit = input;
        self
    }

    /// Maximum overage limit allowed
    pub fn get_max_overage_limit(&self) -> &::std::option::Option<f64> {
        &self.max_overage_limit
    }

    /// Current overage limit
    pub fn overage_limit(mut self, input: f64) -> Self {
        self.overage_limit = ::std::option::Option::Some(input);
        self
    }

    /// Current overage limit
    pub fn set_overage_limit(mut self, input: ::std::option::Option<f64>) -> Self {
        self.overage_limit = input;
        self
    }

    /// Current overage limit
    pub fn get_overage_limit(&self) -> &::std::option::Option<f64> {
        &self.overage_limit
    }

    /// Total overage charges incurred
    pub fn total_overage_charges(mut self, input: f64) -> Self {
        self.total_overage_charges = ::std::option::Option::Some(input);
        self
    }

    /// Total overage charges incurred
    pub fn set_total_overage_charges(mut self, input: ::std::option::Option<f64>) -> Self {
        self.total_overage_charges = input;
        self
    }

    /// Total overage charges incurred
    pub fn get_total_overage_charges(&self) -> &::std::option::Option<f64> {
        &self.total_overage_charges
    }

    /// Consumes the builder and constructs a [`TotalUsage`](crate::types::TotalUsage).
    pub fn build(self) -> crate::types::TotalUsage {
        crate::types::TotalUsage {
            max_overage_limit: self.max_overage_limit,
            overage_limit: self.overage_limit,
            total_overage_charges: self.total_overage_charges,
        }
    }
}
