[package]
name = "fig_auth"
version = "0.1.0"
authors = ["fig developers"]
edition = "2021"
homepage = "https://fig.io"
publish = false

[dependencies]
anyhow = "1.0.58"
base64 = "0.13.0"
cfg-if = "1.0.0"
fig_directories = { path = "../fig_directories" }
jwt = "0.16.0"
rand = "0.8.5"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
thiserror = "1.0.30"
time = { version = "0.3.11", features = ["serde-human-readable", "local-offset", "formatting", "macros", "serde-well-known"] }
tokio = { version = "1.19.2", features = ["time"] }
uuid = { version = "1.1.2", features = ["v4"] }

[target.'cfg(not(target_os = "macos"))'.dependencies]
aws-sdk-cognitoidentityprovider = { version = "0.14.0", default-features = false, features = ["rt-tokio", "native-tls"] }

[target.'cfg(target_os = "macos")'.dependencies]
aws-sdk-cognitoidentityprovider = "0.14.0"
aws-smithy-async = "0.44.0"
aws-smithy-client = { version = "0.44.0", features = ["client-hyper"] }
hyper-rustls = { version = "0.23.0", features = ["webpki-tokio"] }

