[package]
name = "fig_auth"
version = "0.1.0"
authors = ["fig developers"]
edition = "2021"
homepage = "https://fig.io"
publish = false

[dependencies]
anyhow = "1.0.56"
aws-sdk-cognitoidentityprovider = "0.10.1"
aws-smithy-async = "0.40.2"
aws-smithy-client = { version = "0.40.2", features = ["client-hyper"] }
base64 = "0.13.0"
fig_directories = { path = "../fig_directories" }
hyper-rustls = { version = "0.23.0", features = ["webpki-tokio"] }
jwt = "0.16.0"
rand = "0.8.5"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
thiserror = "1.0.30"
time = { version = "0.3.7", features = ["serde-human-readable", "local-offset", "formatting", "macros", "serde-well-known"] }
tokio = { version = "1.17.0", features = ["time"] }
uuid = { version = "1.0.0", features = ["v4"] }
