[package]
name = "fig_auth"
version = "0.1.0"
authors = ["fig developers"]
edition = "2021"
homepage = "https://fig.io"
publish = false

[dependencies]
aws-sdk-cognitoidentityprovider = { version = "0.18.0", default-features = false }
aws-smithy-async = { version = "0.48.0", default-features = false }
aws-smithy-client = { version = "0.48.0", default-features = false }
aws-smithy-http = { version = "0.48.0", default-features = false }
base64 = "0.13.0"
cfg-if = "1.0.0"
fig_settings = { path = "../fig_settings" }
fig_util = { path = "../fig_util" }
http = "0.2.8"
jwt = "0.16.0"
once_cell = "1.14.0"
rand = "0.8.5"
reqwest = { version = "0.11.11", default-features = false, features = [
  "json",
  "rustls-tls-webpki-roots",
  "rustls-tls-native-roots",
  "socks",
  "cookies",
] }
rustls-native-certs = "0.6.2"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.85"
thiserror = "1.0.34"
time = { version = "0.3.14", features = ["serde-human-readable", "local-offset", "formatting", "macros", "serde-well-known"] }
tokio = { version = "1.20.1", features = ["time"] }
tracing = "0.1.36"
uuid = { version = "1.1.2", features = ["v4"] }

