[package]
name = "fig_auth"
version = "0.1.0"
authors = ["fig developers"]
edition = "2021"
homepage = "https://fig.io"
publish = false

[dependencies]
aws-sdk-cognitoidentityprovider = "0.16.0"
aws-smithy-async = "0.46.0"
aws-smithy-client = { version = "0.46.0", features = ["client-hyper"] }
base64 = "0.13.0"
cfg-if = "1.0.0"
fig_directories = { path = "../fig_directories" }
hyper-rustls = { version = "0.23.0", default-features = false, features = ["webpki-tokio", "http1", "tls12", "logging" ] }
jwt = "0.16.0"
rand = "0.8.5"
serde = { version = "1.0.141", features = ["derive"] }
serde_json = "1.0.82"
thiserror = "1.0.30"
time = { version = "0.3.12", features = ["serde-human-readable", "local-offset", "formatting", "macros", "serde-well-known"] }
tokio = { version = "1.20.1", features = ["time"] }
uuid = { version = "1.1.2", features = ["v4"] }

