[package]
name = "newton"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
crossterm = { version = "0.25.0", features = ["serde"] }

[dev-dependencies]
rand = { version = "0.8.5", features = ["std_rng"] }
