[package]
name = "newton"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
crossterm = { version = "0.25.0", features = ["serde"] }

[dev-dependencies]
noise = "0.7.0"
rand = { version = "0.8.5", features = ["std_rng"] }
