services:
  dotenv-base:
    image: dotenv-base
    platform: linux/arm64
    build:
      context: ../
      dockerfile: ./dotenv/Dockerfile
    volumes:
      - ./:/usr/home/app/
      - /usr/home/app/node_modules
