version: "3.9"
services:
  dotenv-base:
    image: dotenv-base
    build:
      context: ../
      dockerfile: ./dotenv/Dockerfile
    volumes:
      - ./:/usr/home/app/
      - /usr/home/app/node_modules
    entrypoint: echo
  blank:
    build: ./configs/blank
    command: tests/bash tests/zsh tests/config
    volumes_from:
      - dotenv-base
    environment:
      ENV_NAME: blank
