services:
  dotenv-base:
    image: dotenv-base
    build:
      context: ../
      dockerfile: ./dotenv/Dockerfile
    extends:
      file: common.yaml
      service: common-options
    entrypoint: echo
  blank:
    container_name: blank
    build: ./configs/blank
    command: tests/bash tests/zsh tests/config
    extends:
      file: common.yaml
      service: common-options
  emulate:
    container_name: emulate
    build: ./configs/emulate
    command: tests/zsh
    extends:
      file: common.yaml
      service: common-options
  oh-my-zsh:
    container_name: oh-my-zsh
    build: ./configs/oh-my-zsh/
    command: tests/zsh
    extends:
      file: common.yaml
      service: common-options
    environment:
      ZSH_THEME: robyrussell
  prezto:
    container_name: prezto
    build: ./configs/prezto/
    command: tests/zsh
    extends:
      file: common.yaml
      service: common-options
  starship:
    container_name: starship
    build: ./configs/starship/
    command: tests/bash tests/zsh
    extends:
      file: common.yaml
      service: common-options
  startup:
    container_name: startup
    build: ./configs/startup/
    command: tests/startup
    extends:
      file: common.yaml
      service: common-options
