[package]
name = "fig_integrations"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
cfg-if = "1.0.0"
clap = { version = "4.0.16", features = ["derive", "deprecated"] }
fig_util = { path = "../fig_util" }
regex = "1.6.0"
serde = { version = "1.0.143", features = ["derive"] }
thiserror = "1.0.36"

[target.'cfg(target_os = "linux")'.dependencies]
sysinfo = "0.26.5"

[target.'cfg(target_os = "macos")'.dependencies]
macos_accessibility_position = { path = "../macos_accessibility_position" }
fig_telemetry = { path = "../fig_telemetry" }
tokio = { version = "1", features = ["full"] }
accessibility-sys = { path = "../macos_accessibility_position/accessibility-master/accessibility-sys", version = "0.1.3" }
core-foundation = "0.9.3"
objc = "0.2.7"
