[package]
name = "fig_integrations"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
cfg-if = "1.0.0"
clap = { version = "4.0.6", features = ["derive", "deprecated"] }
fig_util = { path = "../fig_util" }
regex = "1.6.0"
serde = { version = "1.0.143", features = ["derive"] }
thiserror = "1.0.36"
