[package]
name = "fig_integrations"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
cfg-if = "1.0.0"
clap = { version = "3.2.16", features = ["derive"] }
fig_util = { path = "../fig_util" }
regex = "1.6.0"
serde = { version = "1.0.143", features = ["derive"] }
thiserror = "1.0.32"
time = { version = "0.3.14", features = ["macros", "formatting"] }

[target.'cfg(target_os = "linux")'.dependencies]
sysinfo = "0.25.3"
