[package]
name = "fig_integrations"
version = "0.1.0"
edition = "2021"

[dependencies]
fig_directories = { path = "../fig_directories" }
anyhow = "1.0.57"
thiserror = "1.0.31"
time = "0.3.9"
regex = "1.5.6"
clap = { version = "3.1.18", features = ["derive"] }
serde = { version = "1.0.137", features = ["derive"] }
fig_util = { path = "../fig_util" }

