[package]
name = "fig_integrations"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
cfg-if = "1.0.0"
clap = { version = "4.0.6", features = ["derive", "deprecated"] }
fig_util = { path = "../fig_util" }
regex = "1.6.0"
serde = { version = "1.0.143", features = ["derive"] }
thiserror = "1.0.36"
