[package]
name = "fig_integrations"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.59"
cfg-if = "1.0.0"
clap = { version = "3.2.15", features = ["derive"] }
fig_directories = { path = "../fig_directories" }
fig_util = { path = "../fig_util" }
regex = "1.6.0"
serde = { version = "1.0.141", features = ["derive"] }
thiserror = "1.0.31"
time = { version = "0.3.12", features = ["macros", "formatting"] }

