// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub(crate) fn de_interaction_component<'a, I>(
    tokens: &mut ::std::iter::Peekable<I>,
    _value: &'a [u8],
    depth: u32,
) -> ::std::result::Result<
    Option<crate::types::InteractionComponent>,
    ::aws_smithy_json::deserialize::error::DeserializeError,
>
where
    I: Iterator<
        Item = Result<
            ::aws_smithy_json::deserialize::Token<'a>,
            ::aws_smithy_json::deserialize::error::DeserializeError,
        >,
    >,
{
    if depth >= 128u32 {
        return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(
            "maximum nesting depth exceeded",
        ));
    }
    match tokens.next().transpose()? {
        Some(::aws_smithy_json::deserialize::Token::ValueNull { .. }) => Ok(None),
        Some(::aws_smithy_json::deserialize::Token::StartObject { .. }) => {
            #[allow(unused_mut)]
            let mut builder = crate::types::builders::InteractionComponentBuilder::default();
            loop {
                match tokens.next().transpose()? {
                    Some(::aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
                    Some(::aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => match key
                        .to_unescaped()?
                        .as_ref()
                    {
                        "text" => {
                            builder = builder.set_text(crate::protocol_serde::shape_text::de_text(
                                tokens,
                                _value,
                                depth + 1,
                            )?);
                        },
                        "alert" => {
                            builder = builder.set_alert(crate::protocol_serde::shape_alert::de_alert(
                                tokens,
                                _value,
                                depth + 1,
                            )?);
                        },
                        "infrastructureUpdate" => {
                            builder = builder.set_infrastructure_update(
                                crate::protocol_serde::shape_infrastructure_update::de_infrastructure_update(
                                    tokens,
                                    _value,
                                    depth + 1,
                                )?,
                            );
                        },
                        "progress" => {
                            builder = builder.set_progress(crate::protocol_serde::shape_progress::de_progress(
                                tokens,
                                _value,
                                depth + 1,
                            )?);
                        },
                        "step" => {
                            builder = builder.set_step(crate::protocol_serde::shape_step::de_step(
                                tokens,
                                _value,
                                depth + 1,
                            )?);
                        },
                        "taskDetails" => {
                            builder = builder.set_task_details(
                                crate::protocol_serde::shape_task_details::de_task_details(tokens, _value, depth + 1)?,
                            );
                        },
                        "taskReference" => {
                            builder = builder.set_task_reference(
                                crate::protocol_serde::shape_task_reference::de_task_reference(
                                    tokens,
                                    _value,
                                    depth + 1,
                                )?,
                            );
                        },
                        "suggestions" => {
                            builder = builder.set_suggestions(
                                crate::protocol_serde::shape_suggestions::de_suggestions(tokens, _value, depth + 1)?,
                            );
                        },
                        "section" => {
                            builder = builder.set_section(crate::protocol_serde::shape_section::de_section(
                                tokens,
                                _value,
                                depth + 1,
                            )?);
                        },
                        "resource" => {
                            builder = builder.set_resource(crate::protocol_serde::shape_resource::de_resource(
                                tokens,
                                _value,
                                depth + 1,
                            )?);
                        },
                        "resourceList" => {
                            builder = builder.set_resource_list(
                                crate::protocol_serde::shape_resource_list::de_resource_list(
                                    tokens,
                                    _value,
                                    depth + 1,
                                )?,
                            );
                        },
                        "action" => {
                            builder = builder.set_action(crate::protocol_serde::shape_action::de_action(
                                tokens,
                                _value,
                                depth + 1,
                            )?);
                        },
                        _ => ::aws_smithy_json::deserialize::token::skip_value(tokens)?,
                    },
                    other => {
                        return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(
                            format!("expected object key or end object, found: {other:?}"),
                        ));
                    },
                }
            }
            Ok(Some(builder.build()))
        },
        _ => Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(
            "expected start object or null",
        )),
    }
}
