[package]
name = "fig_test"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tempfile = "3.3.0"
tokio = { version = "1", features = [
    "macros",
    "rt-multi-thread",
    "sync",
    "parking_lot",
] }
