#!/usr/bin/env tsx
/**
 * sprite-extract.ts — Convert a PNG image to a twinki animation sprite
 *
 * Usage:
 *   npx tsx scripts/sprite-extract.ts <image.png> [width] [height] [--palette <chars>]
 *
 * Output:
 *   TypeScript const declaration ready to paste into your animation file.
 *   Palette entries for COLOR_RGB.
 *
 * Requires: Python 3 + Pillow (pip install Pillow)
 * The heavy lifting is done by Python since Node has no built-in PNG decoder.
 *
 * Example:
 *   npx tsx scripts/sprite-extract.ts ghost.png 32 32
 *   npx tsx scripts/sprite-extract.ts mario.png 24 39 --name MARIO_IDLE
 */

import { execSync } from 'node:child_process';
import { writeFileSync, existsSync } from 'node:fs';
import { resolve, basename, extname } from 'node:path';

const args = process.argv.slice(2);
if (args.length === 0 || args[0] === '--help') {
	console.log('Usage: npx tsx scripts/sprite-extract.ts <image.png> [width=32] [height=32] [--name NAME] [--out file.ts]');
	process.exit(0);
}

const src = resolve(args[0]!);
if (!existsSync(src)) { console.error(`File not found: ${src}`); process.exit(1); }

const W = parseInt(args[1] ?? '32');
const H = parseInt(args[2] ?? '32');
const nameIdx = args.indexOf('--name');
const outIdx = args.indexOf('--out');
const spriteName = nameIdx >= 0 ? args[nameIdx + 1]! : basename(src, extname(src)).toUpperCase().replace(/[^A-Z0-9_]/g, '_');
const outFile = outIdx >= 0 ? args[outIdx + 1]! : null;

// Inline Python script (same logic as extract-sprite.py)
const PYTHON = `
import sys, json
from PIL import Image

src, W, H = sys.argv[1], int(sys.argv[2]), int(sys.argv[3])
img = Image.open(src).convert('RGBA').resize((W, H), Image.LANCZOS)
px = img.load()

# Detect background: sample corners
corners = [px[0,0], px[W-1,0], px[0,H-1], px[W-1,H-1]]
bg_candidates = [(r,g,b) for r,g,b,a in corners if a > 200]
if bg_candidates:
    bg = tuple(sum(c[i] for c in bg_candidates)//len(bg_candidates) for i in range(3))
else:
    bg = (0,0,0)

def is_bg(r,g,b,a):
    if a < 30: return True
    return (r-bg[0])**2+(g-bg[1])**2+(b-bg[2])**2 < 600

CHARS = 'WwxKkeabcdfghijklmnopqrstuvyzABCDEFGHIJLMNOPQRSTUVXYZ0123456789'
palette = {}

def nearest(r,g,b):
    best,bestd = None,float('inf')
    for (pr,pg,pb),ch in palette.items():
        d=(r-pr)**2+(g-pg)**2+(b-pb)**2
        if d<bestd: bestd,best=d,ch
    return best

rows = []
for y in range(H):
    row = ''
    for x in range(W):
        r,g,b,a = px[x,y]
        if is_bg(r,g,b,a):
            row += '.'
            continue
        key = (r,g,b)
        if key not in palette:
            if len(palette) < len(CHARS):
                palette[key] = CHARS[len(palette)]
            else:
                row += nearest(r,g,b)
                continue
        row += palette[key]
    rows.append(row)

print(json.dumps({'rows': rows, 'palette': {f'{r},{g},{b}': ch for (r,g,b),ch in palette.items()}}))
`;

let result: { rows: string[]; palette: Record<string, string> };
try {
	const out = execSync(`python3 -c ${JSON.stringify(PYTHON)} ${JSON.stringify(src)} ${W} ${H}`, { encoding: 'utf8' });
	result = JSON.parse(out);
} catch (e: any) {
	console.error('Python extraction failed. Make sure Python 3 + Pillow are installed.');
	console.error(e.message);
	process.exit(1);
}

// Build TypeScript output
const lines: string[] = [
	`// Sprite extracted from ${basename(src)} (${W}×${H})`,
	`// Generated by scripts/sprite-extract.ts`,
	`const ${spriteName}: string[] = [`,
	...result.rows.map(r => `\t'${r}',`),
	`];`,
	``,
	`// Add these entries to COLOR_RGB:`,
	...Object.entries(result.palette).map(([rgb, ch]) => {
		const [r, g, b] = rgb.split(',');
		return `// '${ch}': [${r},${g},${b}],`;
	}),
];

const output = lines.join('\n') + '\n';

if (outFile) {
	writeFileSync(outFile, output);
	console.log(`Written to ${outFile}`);
} else {
	process.stdout.write(output);
}
