[package]
name = "figterm"
version = "4.1.2"
authors = ["Fig"]
edition = "2021"
description = "A layer between the terminal and shell."
homepage = "https://fig.io"
repository = "https://github.com/withfig/macos"
publish = false

[features]
default = ["desktop-tests"]
# Tests that do not work on CI
desktop-tests = []

[dependencies]
alacritty_terminal = { path = "../rust-lib/alacritty_terminal" }
anyhow = "1.0.53"
bytes = "1.1.0"
clap = { version = "3.1.0", features = ["derive"] }
crossbeam = "0.8.1"
dashmap = "5.1.0"
dirs = "4.0.0"
fig-auth = { path = "../rust-lib/fig-auth" }
fig-ipc = { path = "../rust-lib/fig-ipc" }
fig-proto = { path = "../rust-lib/fig-proto" }
flume = "0.10.10"
fnv = "1.0.7"
nix = "0.23.1"
once_cell = "1.9.0"
parking_lot = "0.12.0"
regex = "1.5.4"
rusqlite = { version = "0.27.0", features = ["bundled"] }
sentry = { version = "0.24.2", features = ["anyhow"] }
signal-hook = "0.3.13"
tokio = { version = "1.17.0", features = ["full"] }
tracing = "0.1.31"
tracing-subscriber = { version = "0.3.9", features = ["fmt", "time", "parking_lot"] }
