[package]
name = "figterm"
version = "4.4.0"
authors = ["fig developers"]
edition = "2021"
description = "A layer between the terminal and shell."
homepage = "https://fig.io"
publish = false

[features]
default = ["desktop-tests"]
# Tests that do not work on CI
desktop-tests = []

[dependencies]
alacritty_terminal = { path = "../rust-lib/alacritty_terminal" }
anyhow = "1.0.53"
bitflags = "1.3.2"
bytes = "1.1.0"
clap = { version = "3.1.0", features = ["derive"] }
crossbeam = "0.8.1"
dashmap = "5.1.0"
fig_auth = { path = "../rust-lib/fig_auth" }
fig_directories = { path = "../rust-lib/fig_directories" }
fig_ipc = { path = "../rust-lib/fig_ipc" }
fig_proto = { path = "../rust-lib/fig_proto" }
fig_settings = { path = "../rust-lib/fig_settings" }
fig_telemetry = { path = "../rust-lib/fig_telemetry" }
fig_util = { path = "../rust-lib/fig_util" }
flume = "0.10.10"
fnv = "1.0.7"
heapless = "0.7.10"
nix = "0.24.1"
once_cell = "1.12.0"
parking_lot = "0.12.0"
regex = "1.5.4"
rusqlite = { version = "0.27.0", features = ["bundled"] }
sentry = { version = "0.26.0", features = ["anyhow"] }
signal-hook = "0.3.13"
tokio = { version = "1.17.0", features = ["full"] }
tracing = "0.1.31"
tracing-subscriber = { version = "0.3.9", features = ["fmt", "time", "parking_lot"] }
