[package]
name = "figterm"
version = "0.1.0"
authors = ["grant0417"]
edition = "2021"
description = ""
homepage = "https://fig.io"
repository = "https://github.com/withfig/macos"
publish = false

[dependencies]

# System Libs
nix = "0.23"
signal-hook = "0.3"
tokio = { version = "1", features = ["full"] }
alacritty_terminal = "0.15"

# Logging
log = { version = "0.4", features = ["std"] }

# User dirs
dirs = "4.0.0"

# Protocal buffers
prost = "0.9"
bytes = "1.1"

# Error Handling
anyhow = "1.0"

# Cmd arg parsing
clap = { version = "3.0.0-rc.4", features = ["derive"] }

[build-dependencies]
prost-build = "0.9"
