[package]
name = "figterm"
version = "5.2.0"
authors = ["fig developers"]
edition = "2021"
description = "A layer between the terminal and shell."
homepage = "https://fig.io"
publish = false

[features]
# Tests that do not work on CI
desktop-tests = []

[dependencies]
alacritty_terminal = { path = "../rust-lib/alacritty_terminal" }
anyhow = "1.0.64"
async-trait = "0.1.57"
bitflags = "1.3.2"
bytes = "1.2.1"
cfg-if = "1.0.0"
clap = { version = "3.2.20", features = ["derive"] }
dashmap = "5.3.4"
fig_api_client = { path = "../rust-lib/fig_api_client" }
fig_auth = { path = "../rust-lib/fig_auth" }
fig_color = { path = "../rust-lib/fig_color" }
fig_ipc = { path = "../rust-lib/fig_ipc" }
fig_proto = { path = "../rust-lib/fig_proto" }
fig_settings = { path = "../rust-lib/fig_settings" }
fig_telemetry = { path = "../rust-lib/fig_telemetry" }
fig_util = { path = "../rust-lib/fig_util" }
filedescriptor = "0.8"
flume = "0.10.14"
fnv = "1.0.7"
memmem = "0.1.1"
num-traits = "0.2"
once_cell = "1.13.1"
parking_lot = "0.12.1"
pin-project = "1.0.12"
portable-pty = "0.7.0"
regex = "1.6.0"
rusqlite = { version = "0.27.0", features = ["bundled"] }
shell-words = "1.1"
tokio = { version = "1.20.1", features = ["full"] }
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["fmt", "time", "parking_lot"] }
uuid = { version = "1.1.2", features = ["v4", "fast-rng"] }

[target.'cfg(target_os = "linux")'.dependencies]
procfs = "0.14.0"

[target.'cfg(unix)'.dependencies]
nix = "0.25.0"

[target.'cfg(windows)'.dependencies]
lazy_static = "1.4"
shared_library = "0.1"
windows = { version = "0.39.0", features = ["Win32_System_Threading"] }
winapi = { version = "0.3", features = [
    "winuser",
    "winnls",
    "consoleapi",
    "handleapi",
    "fileapi",
    "namedpipeapi",
    "synchapi",
] }
winreg = "0.10"

