[package]
name = "dbus"
version = "0.1.0"
edition = "2021"
publish = false

[target.'cfg(target_os = "linux")'.dependencies]
once_cell = "1.15.0"
thiserror = "1.0"
tokio = { version = "1", features = ["process", "sync", "parking_lot"] }
tracing = "0.1.36"
zbus = { version = "3", default-features = false, features = ["tokio"] }
