[package]
name = "dbus"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
once_cell = "1.13.1"
thiserror = "1.0"
tokio = { version = "1", features = ["process", "sync", "parking_lot"] }
zbus = { version = "2", default-features = false, features = ["tokio"] }
