[package]
name = "dbus"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
flume = "0.10.14"
once_cell = "1.13.1"
thiserror = "1.0"
tokio = { version = "1", features = ["process", "sync", "parking_lot"] }
tracing = "0.1.36"
zbus = { version = "3", default-features = false, features = ["tokio"] }
