[package]
name = "fig_settings"
version = "0.1.0"
authors = ["fig developers"]
edition = "2021"
homepage = "https://fig.io"
publish = false

[dependencies]
fig_auth = { path = "../fig_auth" }
fig_util = { path = "../fig_util" }
once_cell = { version = "1.13.0", features = ["parking_lot"] }
regex = "1.6.0"
reqwest = { version = "0.11.10", default-features = false, features = ["json", "rustls-tls-webpki-roots"] }
serde = { version = "1.0.141", features = ["derive"] }
serde_json = "1.0.82"
thiserror = "1.0.32"
time = { version = "0.3.12", features = ["serde-well-known"] }
tokio = { version = "1.20.1", features = ["full"] }
url = "2.2.2"

[dev-dependencies]
tempfile = "3.3.0"
