[package]
name = "fig_settings"
version = "0.1.0"
authors = ["fig developers"]
edition = "2021"
homepage = "https://fig.io"
publish = false

[dependencies]
bitflags = "1.3.2"
futures = { version = "0.3.21", features = ["executor"] } 
fig_auth = { path = "../fig_auth" }
fig_directories = { path = "../fig_directories" }
reqwest = { version = "0.11.9", features = ["json"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
thiserror = "1.0.30"
tokio = { version = "1.19.2", features = ["full"] }
time = { version = "0.3.7", features = ["serde-well-known"] }
url = "2.2.2"
