[package]
name = "fig_settings"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
fd-lock = "3.0.6"
fig_util = { path = "../fig_util" }
parking_lot = "0.12.1"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.85"
thiserror = "1.0.36"
tokio = { version = "1.20.1", features = ["full"] }
url = "2.3.1"

[dev-dependencies]
fig_test = { path = "../fig_test" }
tempfile = "3.3.0"
