// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Structure representing a single step in a clarification flow.
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub struct ClarificationQuestion {
    /// The question to present to the user.
    pub question: ::std::string::String,
    /// List of options for the user to choose from.
    pub options: ::std::vec::Vec<crate::types::ClarificationAnswerOption>,
    /// Whether the user can provide a custom response instead of selecting an option.
    pub allow_custom: ::std::option::Option<bool>,
    /// Whether the user can skip this question.
    pub skippable: ::std::option::Option<bool>,
}
impl ClarificationQuestion {
    /// The question to present to the user.
    pub fn question(&self) -> &str {
        use std::ops::Deref;
        self.question.deref()
    }

    /// List of options for the user to choose from.
    pub fn options(&self) -> &[crate::types::ClarificationAnswerOption] {
        use std::ops::Deref;
        self.options.deref()
    }

    /// Whether the user can provide a custom response instead of selecting an option.
    pub fn allow_custom(&self) -> ::std::option::Option<bool> {
        self.allow_custom
    }

    /// Whether the user can skip this question.
    pub fn skippable(&self) -> ::std::option::Option<bool> {
        self.skippable
    }
}
impl ::std::fmt::Debug for ClarificationQuestion {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("ClarificationQuestion");
        formatter.field("question", &"*** Sensitive Data Redacted ***");
        formatter.field("options", &self.options);
        formatter.field("allow_custom", &self.allow_custom);
        formatter.field("skippable", &self.skippable);
        formatter.finish()
    }
}
impl ClarificationQuestion {
    /// Creates a new builder-style object to manufacture
    /// [`ClarificationQuestion`](crate::types::ClarificationQuestion).
    pub fn builder() -> crate::types::builders::ClarificationQuestionBuilder {
        crate::types::builders::ClarificationQuestionBuilder::default()
    }
}

/// A builder for [`ClarificationQuestion`](crate::types::ClarificationQuestion).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default)]
#[non_exhaustive]
pub struct ClarificationQuestionBuilder {
    pub(crate) question: ::std::option::Option<::std::string::String>,
    pub(crate) options: ::std::option::Option<::std::vec::Vec<crate::types::ClarificationAnswerOption>>,
    pub(crate) allow_custom: ::std::option::Option<bool>,
    pub(crate) skippable: ::std::option::Option<bool>,
}
impl ClarificationQuestionBuilder {
    /// The question to present to the user.
    /// This field is required.
    pub fn question(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.question = ::std::option::Option::Some(input.into());
        self
    }

    /// The question to present to the user.
    pub fn set_question(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.question = input;
        self
    }

    /// The question to present to the user.
    pub fn get_question(&self) -> &::std::option::Option<::std::string::String> {
        &self.question
    }

    /// Appends an item to `options`.
    ///
    /// To override the contents of this collection use [`set_options`](Self::set_options).
    ///
    /// List of options for the user to choose from.
    pub fn options(mut self, input: crate::types::ClarificationAnswerOption) -> Self {
        let mut v = self.options.unwrap_or_default();
        v.push(input);
        self.options = ::std::option::Option::Some(v);
        self
    }

    /// List of options for the user to choose from.
    pub fn set_options(
        mut self,
        input: ::std::option::Option<::std::vec::Vec<crate::types::ClarificationAnswerOption>>,
    ) -> Self {
        self.options = input;
        self
    }

    /// List of options for the user to choose from.
    pub fn get_options(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::ClarificationAnswerOption>> {
        &self.options
    }

    /// Whether the user can provide a custom response instead of selecting an option.
    pub fn allow_custom(mut self, input: bool) -> Self {
        self.allow_custom = ::std::option::Option::Some(input);
        self
    }

    /// Whether the user can provide a custom response instead of selecting an option.
    pub fn set_allow_custom(mut self, input: ::std::option::Option<bool>) -> Self {
        self.allow_custom = input;
        self
    }

    /// Whether the user can provide a custom response instead of selecting an option.
    pub fn get_allow_custom(&self) -> &::std::option::Option<bool> {
        &self.allow_custom
    }

    /// Whether the user can skip this question.
    pub fn skippable(mut self, input: bool) -> Self {
        self.skippable = ::std::option::Option::Some(input);
        self
    }

    /// Whether the user can skip this question.
    pub fn set_skippable(mut self, input: ::std::option::Option<bool>) -> Self {
        self.skippable = input;
        self
    }

    /// Whether the user can skip this question.
    pub fn get_skippable(&self) -> &::std::option::Option<bool> {
        &self.skippable
    }

    /// Consumes the builder and constructs a
    /// [`ClarificationQuestion`](crate::types::ClarificationQuestion). This method will fail if
    /// any of the following fields are not set:
    /// - [`question`](crate::types::builders::ClarificationQuestionBuilder::question)
    /// - [`options`](crate::types::builders::ClarificationQuestionBuilder::options)
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::types::ClarificationQuestion, ::aws_smithy_types::error::operation::BuildError>
    {
        ::std::result::Result::Ok(crate::types::ClarificationQuestion {
            question: self.question.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "question",
                    "question was not specified but it is required when building ClarificationQuestion",
                )
            })?,
            options: self.options.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "options",
                    "options was not specified but it is required when building ClarificationQuestion",
                )
            })?,
            allow_custom: self.allow_custom,
            skippable: self.skippable,
        })
    }
}
impl ::std::fmt::Debug for ClarificationQuestionBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("ClarificationQuestionBuilder");
        formatter.field("question", &"*** Sensitive Data Redacted ***");
        formatter.field("options", &self.options);
        formatter.field("allow_custom", &self.allow_custom);
        formatter.field("skippable", &self.skippable);
        formatter.finish()
    }
}
