// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// JSON-RPC 2.0 message - supports both notifications (method+params) and responses
/// (id+result/error)
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub struct JsonRpcStreamEvent {
    /// JSON-RPC protocol version
    pub jsonrpc: ::std::string::String,
    /// Method name for notifications/requests
    pub method: ::std::option::Option<::std::string::String>,
    /// Method parameters for notifications/requests
    pub params: ::std::option::Option<::aws_smithy_types::Document>,
    /// Request identifier for response correlation. Absent for notifications per JSON-RPC spec.
    pub id: ::std::option::Option<::aws_smithy_types::Document>,
    /// Success result (for responses only, mutually exclusive with error)
    pub result: ::std::option::Option<::aws_smithy_types::Document>,
    /// Error information (for responses only, mutually exclusive with result)
    pub error: ::std::option::Option<crate::types::JsonRpcError>,
}
impl JsonRpcStreamEvent {
    /// JSON-RPC protocol version
    pub fn jsonrpc(&self) -> &str {
        use std::ops::Deref;
        self.jsonrpc.deref()
    }

    /// Method name for notifications/requests
    pub fn method(&self) -> ::std::option::Option<&str> {
        self.method.as_deref()
    }

    /// Method parameters for notifications/requests
    pub fn params(&self) -> ::std::option::Option<&::aws_smithy_types::Document> {
        self.params.as_ref()
    }

    /// Request identifier for response correlation. Absent for notifications per JSON-RPC spec.
    pub fn id(&self) -> ::std::option::Option<&::aws_smithy_types::Document> {
        self.id.as_ref()
    }

    /// Success result (for responses only, mutually exclusive with error)
    pub fn result(&self) -> ::std::option::Option<&::aws_smithy_types::Document> {
        self.result.as_ref()
    }

    /// Error information (for responses only, mutually exclusive with result)
    pub fn error(&self) -> ::std::option::Option<&crate::types::JsonRpcError> {
        self.error.as_ref()
    }
}
impl ::std::fmt::Debug for JsonRpcStreamEvent {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("JsonRpcStreamEvent");
        formatter.field("jsonrpc", &self.jsonrpc);
        formatter.field("method", &self.method);
        formatter.field("params", &"*** Sensitive Data Redacted ***");
        formatter.field("id", &self.id);
        formatter.field("result", &"*** Sensitive Data Redacted ***");
        formatter.field("error", &self.error);
        formatter.finish()
    }
}
impl JsonRpcStreamEvent {
    /// Creates a new builder-style object to manufacture
    /// [`JsonRpcStreamEvent`](crate::types::JsonRpcStreamEvent).
    pub fn builder() -> crate::types::builders::JsonRpcStreamEventBuilder {
        crate::types::builders::JsonRpcStreamEventBuilder::default()
    }
}

/// A builder for [`JsonRpcStreamEvent`](crate::types::JsonRpcStreamEvent).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default)]
#[non_exhaustive]
pub struct JsonRpcStreamEventBuilder {
    pub(crate) jsonrpc: ::std::option::Option<::std::string::String>,
    pub(crate) method: ::std::option::Option<::std::string::String>,
    pub(crate) params: ::std::option::Option<::aws_smithy_types::Document>,
    pub(crate) id: ::std::option::Option<::aws_smithy_types::Document>,
    pub(crate) result: ::std::option::Option<::aws_smithy_types::Document>,
    pub(crate) error: ::std::option::Option<crate::types::JsonRpcError>,
}
impl JsonRpcStreamEventBuilder {
    /// JSON-RPC protocol version
    /// This field is required.
    pub fn jsonrpc(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.jsonrpc = ::std::option::Option::Some(input.into());
        self
    }

    /// JSON-RPC protocol version
    pub fn set_jsonrpc(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.jsonrpc = input;
        self
    }

    /// JSON-RPC protocol version
    pub fn get_jsonrpc(&self) -> &::std::option::Option<::std::string::String> {
        &self.jsonrpc
    }

    /// Method name for notifications/requests
    pub fn method(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.method = ::std::option::Option::Some(input.into());
        self
    }

    /// Method name for notifications/requests
    pub fn set_method(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.method = input;
        self
    }

    /// Method name for notifications/requests
    pub fn get_method(&self) -> &::std::option::Option<::std::string::String> {
        &self.method
    }

    /// Method parameters for notifications/requests
    pub fn params(mut self, input: ::aws_smithy_types::Document) -> Self {
        self.params = ::std::option::Option::Some(input);
        self
    }

    /// Method parameters for notifications/requests
    pub fn set_params(mut self, input: ::std::option::Option<::aws_smithy_types::Document>) -> Self {
        self.params = input;
        self
    }

    /// Method parameters for notifications/requests
    pub fn get_params(&self) -> &::std::option::Option<::aws_smithy_types::Document> {
        &self.params
    }

    /// Request identifier for response correlation. Absent for notifications per JSON-RPC spec.
    pub fn id(mut self, input: ::aws_smithy_types::Document) -> Self {
        self.id = ::std::option::Option::Some(input);
        self
    }

    /// Request identifier for response correlation. Absent for notifications per JSON-RPC spec.
    pub fn set_id(mut self, input: ::std::option::Option<::aws_smithy_types::Document>) -> Self {
        self.id = input;
        self
    }

    /// Request identifier for response correlation. Absent for notifications per JSON-RPC spec.
    pub fn get_id(&self) -> &::std::option::Option<::aws_smithy_types::Document> {
        &self.id
    }

    /// Success result (for responses only, mutually exclusive with error)
    pub fn result(mut self, input: ::aws_smithy_types::Document) -> Self {
        self.result = ::std::option::Option::Some(input);
        self
    }

    /// Success result (for responses only, mutually exclusive with error)
    pub fn set_result(mut self, input: ::std::option::Option<::aws_smithy_types::Document>) -> Self {
        self.result = input;
        self
    }

    /// Success result (for responses only, mutually exclusive with error)
    pub fn get_result(&self) -> &::std::option::Option<::aws_smithy_types::Document> {
        &self.result
    }

    /// Error information (for responses only, mutually exclusive with result)
    pub fn error(mut self, input: crate::types::JsonRpcError) -> Self {
        self.error = ::std::option::Option::Some(input);
        self
    }

    /// Error information (for responses only, mutually exclusive with result)
    pub fn set_error(mut self, input: ::std::option::Option<crate::types::JsonRpcError>) -> Self {
        self.error = input;
        self
    }

    /// Error information (for responses only, mutually exclusive with result)
    pub fn get_error(&self) -> &::std::option::Option<crate::types::JsonRpcError> {
        &self.error
    }

    /// Consumes the builder and constructs a
    /// [`JsonRpcStreamEvent`](crate::types::JsonRpcStreamEvent). This method will fail if any
    /// of the following fields are not set:
    /// - [`jsonrpc`](crate::types::builders::JsonRpcStreamEventBuilder::jsonrpc)
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::types::JsonRpcStreamEvent, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::JsonRpcStreamEvent {
            jsonrpc: self.jsonrpc.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "jsonrpc",
                    "jsonrpc was not specified but it is required when building JsonRpcStreamEvent",
                )
            })?,
            method: self.method,
            params: self.params,
            id: self.id,
            result: self.result,
            error: self.error,
        })
    }
}
impl ::std::fmt::Debug for JsonRpcStreamEventBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("JsonRpcStreamEventBuilder");
        formatter.field("jsonrpc", &self.jsonrpc);
        formatter.field("method", &self.method);
        formatter.field("params", &"*** Sensitive Data Redacted ***");
        formatter.field("id", &self.id);
        formatter.field("result", &"*** Sensitive Data Redacted ***");
        formatter.field("error", &self.error);
        formatter.finish()
    }
}
