// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Details about the model's refusal due to content policy.
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct RefusalDetails {
    /// The category of refusal (cyber, bio, frontier_llm, reasoning_extraction)
    pub category: ::std::option::Option<crate::types::RefusalCategory>,
    /// Human-readable explanation supplied by the provider
    pub explanation: ::std::option::Option<::std::string::String>,
    /// A model the provider recommends as an alternative
    pub recommended_model: ::std::option::Option<::std::string::String>,
}
impl RefusalDetails {
    /// The category of refusal (cyber, bio, frontier_llm, reasoning_extraction)
    pub fn category(&self) -> ::std::option::Option<&crate::types::RefusalCategory> {
        self.category.as_ref()
    }

    /// Human-readable explanation supplied by the provider
    pub fn explanation(&self) -> ::std::option::Option<&str> {
        self.explanation.as_deref()
    }

    /// A model the provider recommends as an alternative
    pub fn recommended_model(&self) -> ::std::option::Option<&str> {
        self.recommended_model.as_deref()
    }
}
impl RefusalDetails {
    /// Creates a new builder-style object to manufacture
    /// [`RefusalDetails`](crate::types::RefusalDetails).
    pub fn builder() -> crate::types::builders::RefusalDetailsBuilder {
        crate::types::builders::RefusalDetailsBuilder::default()
    }
}

/// A builder for [`RefusalDetails`](crate::types::RefusalDetails).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct RefusalDetailsBuilder {
    pub(crate) category: ::std::option::Option<crate::types::RefusalCategory>,
    pub(crate) explanation: ::std::option::Option<::std::string::String>,
    pub(crate) recommended_model: ::std::option::Option<::std::string::String>,
}
impl RefusalDetailsBuilder {
    /// The category of refusal (cyber, bio, frontier_llm, reasoning_extraction)
    pub fn category(mut self, input: crate::types::RefusalCategory) -> Self {
        self.category = ::std::option::Option::Some(input);
        self
    }

    /// The category of refusal (cyber, bio, frontier_llm, reasoning_extraction)
    pub fn set_category(mut self, input: ::std::option::Option<crate::types::RefusalCategory>) -> Self {
        self.category = input;
        self
    }

    /// The category of refusal (cyber, bio, frontier_llm, reasoning_extraction)
    pub fn get_category(&self) -> &::std::option::Option<crate::types::RefusalCategory> {
        &self.category
    }

    /// Human-readable explanation supplied by the provider
    pub fn explanation(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.explanation = ::std::option::Option::Some(input.into());
        self
    }

    /// Human-readable explanation supplied by the provider
    pub fn set_explanation(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.explanation = input;
        self
    }

    /// Human-readable explanation supplied by the provider
    pub fn get_explanation(&self) -> &::std::option::Option<::std::string::String> {
        &self.explanation
    }

    /// A model the provider recommends as an alternative
    pub fn recommended_model(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.recommended_model = ::std::option::Option::Some(input.into());
        self
    }

    /// A model the provider recommends as an alternative
    pub fn set_recommended_model(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.recommended_model = input;
        self
    }

    /// A model the provider recommends as an alternative
    pub fn get_recommended_model(&self) -> &::std::option::Option<::std::string::String> {
        &self.recommended_model
    }

    /// Consumes the builder and constructs a [`RefusalDetails`](crate::types::RefusalDetails).
    pub fn build(self) -> crate::types::RefusalDetails {
        crate::types::RefusalDetails {
            category: self.category,
            explanation: self.explanation,
            recommended_model: self.recommended_model,
        }
    }
}
