name: "Build tauri cli"

on:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: tauri-apps/tauri
          ref: dev

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Install brew dependencies
        run: |
          brew install openssl

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@578b235f6e5f613f7727f1c17bd3305b4d4d4e1f

      - name: Build
        run: cd tooling/cli && cargo build --release --package tauri-cli --target ${{ matrix.target }}

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}"
          automatic_release_tag: "tauri-cli-macos"
          title: "tauri-cli macos release"
          files: tooling/cli/target/${{ matrix.target }}/release/cargo-tauri
