name: docs-generator

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Number of PR to document'
        required: true
        type: string

jobs:
  generate_docs:
    runs-on: ubuntu-latest
    env:
      PR_FILE: "pr-contents.txt"
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source ~/.cargo/env

    - name: Generate PR contents file
      run: ./docs-generation/read-pr.sh ${{ inputs.pr_number }}

    # For testing purposes, we're building from source
    - name: Update docs
      run: ./docs-generation/update-docs.sh

    - name: Create PR
      if: success()
      run: ./docs-generation/create-docs-pr.sh ${{ inputs.pr_number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    
    


      
