name: Install script upload

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  upload-install-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fig_cli 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Install AWS CLI"
        uses: chrislennon/action-aws-cli@v1.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Upload to S3 Bucket
        run: |
          # s3 determines Content-Type based on file extension at upload
          mv ./install_script.sh ./install_script.html
          aws s3 cp ./install_script.html s3://get-fig-io/index.html
          aws s3 cp ./readability.js s3://get-fig-io/readability.js

          aws cloudfront create-invalidation --distribution-id E1HTOEOFYWKMTG --paths "/index.html"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DOTFILESD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DOTFILESD_AWS_SECRET_ACCESS_KEY }}

