name: Proto CI

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "*.proto"
    branches:
      - develop
  push:
    paths:
      - "*.proto"
    branches:
      - develop

concurrency:
  group: proto-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  protos-breaking:
    name: Protos Breaking
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: proto
          against: "https://github.com/withfig/macos.git#branch=develop,subdir=proto"

  protos-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: proto

  protos-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
      - name: Format Lint
        working-directory: proto
        run: buf format --exit-code > /dev/null || (echo "Please run 'buf format' and commit the changes" && exit 1)
