name: Publish package to NPM

on:
  workflow_dispatch:
  push:
    paths: 
      - typescript-api-bindings/src/*.ts
      - typescript-api-bindings/codegen/*.ts
      - typescript-api-bindings/package.json
      - proto/fig.proto

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    ## We only want to publish a package if it is on develop branch
    if: ${{ github.ref == 'refs/heads/develop' }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Install Protobuf
        run: |
          curl -L -o /tmp/protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v21.6/protoc-21.6-linux-x86_64.zip \
          && unzip /tmp/protoc.zip -d /tmp/protoc \
          && sudo cp /tmp/protoc/bin/protoc /usr/local/bin/ \
          && sudo cp -r /tmp/protoc/include/google /usr/local/include/

      - name: Install Protobuf tooling
        working-directory: ./typescript-api-bindings
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
        run: yarn install --frozen-lockfile

      - name: Generate Protobuf Artifacts
        run: make api-ts
        working-directory: ./proto
          
      - name: Generate Requests and Lint
        working-directory: ./typescript-api-bindings
        run: |
          yarn generate-requests
          yarn lint --fix

      - name: Automated Version Bump
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}
          PACKAGEJSON_DIR:  'typescript-api-bindings'
        with:
          skip-tag: "true"

      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v2
        with:
          access: public
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          package: typescript-api-bindings/package.json
