name: Publish package to NPM

on:
  workflow_dispatch:
  push:
    paths: typescript-api-bindings/src/*.ts

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    ## We only want to publish a package if it is on develop branch
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install Protobuf tooling
        run:  |
          brew install protobuf
          npm install -g ts-proto
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1

      - name: Generate Protobuf Artifacts
        run: make api-ts
        working-directory: ./proto
          
      - name: Navigate to typescript-api-bindings
        run: cd typescript-api-bindings
      - name: "Install package.json dependencies"
        run: |
          cd typescript-api-bindings
          yarn install --frozen-lockfile
          yarn generate-requests
          yarn lint --fix

      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}
          PACKAGEJSON_DIR:  'typescript-api-bindings'
        with:
          skip-tag: "true"

      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          access: public
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          package: typescript-api-bindings/package.json
