
name: Release Notification

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  prepare_message:
    name: Prepare Release Message
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.build-message.outputs.message }}
    steps:
      - name: Build Message
        id: build-message
        env:
          RELEASE_DESCRIPTION: ${{ github.event.release.body }}
        run: |
          jq -n \
            --arg release_name "${{ github.event.release.name }}" \
            --arg tag_name "${{ github.event.release.tag_name }}" \
            --arg release_url "${{ github.event.release.html_url }}" \
            --arg author_name "${{ github.event.release.author.login }}" \
            --arg repository_name "${{ github.event.repository.name }}" \
            --arg repository_url "${{ github.event.repository.html_url }}" \
            --arg release_description "$RELEASE_DESCRIPTION" \
            '{
              release_name: $release_name,
              tag_name: $tag_name,
              release_url: $release_url,
              author_name: $author_name,
              repository_name: $repository_name,
              repository_url: $repository_url,
              release_description: $release_description
            }' > message.json
          echo "message<<JSONEOF" >> $GITHUB_OUTPUT
          cat message.json >> $GITHUB_OUTPUT
          echo "JSONEOF" >> $GITHUB_OUTPUT

  notify:
    name: Send Notification
    needs: prepare_message
    uses: ./.github/workflows/notify-slack.yml
    secrets:
      WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      message: ${{ needs.prepare_message.outputs.message }}
