
name: Release Notification

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  prepare_message:
    name: Prepare Release Message
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.build-message.outputs.message }}
    steps:
      - name: Build Message
        id: build-message
        run: |
          cat << 'EOF' > message.json
          {
            "release_name": "${{ github.event.release.name }}",
            "tag_name": "${{ github.event.release.tag_name }}",
            "release_url": "${{ github.event.release.html_url }}",
            "author_name": "${{ github.event.release.author.login }}",
            "repository_name": "${{ github.event.repository.name }}",
            "repository_url": "${{ github.event.repository.html_url }}",
            "release_description": ${{ toJSON(github.event.release.body) }}
          }
          EOF
          echo "message=$(cat message.json | jq -c .)" >> $GITHUB_OUTPUT

  notify:
    name: Send Notification
    needs: prepare_message
    uses: ./.github/workflows/notify-slack.yml
    secrets:
      WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      message: ${{ needs.prepare_message.outputs.message }}
