name: Rust checks

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Clippy
      run: cargo clippy --locked --color always -- -D warnings
    - name: Fmt
      run: 
        rustup toolchain install nightly
        cargo +nightly fmt --check -- --color always
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
