name: Rust CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "rust-lib/**"
      - "figterm/**"
      - "figcli/**"
      - "proto/**"
      - ".github/workflows/rust-ci.yaml"
  push:
    paths:
      - "rust-lib/**"
      - "figterm/**"
      - "figcli/**"
      - "proto/**"
      - ".github/workflows/rust-ci.yaml"
    branches:
      - master
      - staging
      - develop

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-build-and-test:
    name: Rust Build and Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          #- [self-hosted, macos, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # If on Ubuntu, install dependencies
      - name: Install Ubuntu dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install -y libxcb1-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - uses: actions/cache@v2
        with:
          path: target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Compile
        run: cargo test --no-run --locked

      - name: Test
        run: cargo test --no-default-features -- --nocapture --quiet

  rust-clippy-lint:
    name: Rust Clippy Lint
    runs-on: [self-hosted, macos, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: clippy

      - uses: actions/cache@v2
        with:
          path: target/
          key: rust-ci-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            rust-ci-${{ runner.os }}-cargo-

      - name: Clippy Lint
        run: cargo clippy --all-targets --all-features -- -D warnings

  rust-fmt-lint:
    name: Rust Fmt Lint
    runs-on: [self-hosted, macos, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt
          
      - uses: Swatinem/rust-cache@v1

      - name: Fmt Lint
        run: cargo fmt -- --color always --check
