name: Update AUR Package

on:
  workflow_dispatch:
    inputs:
      channel:
        description: "Channel"
        required: true
        type: choice
        options:
          - stable
          - beta
          - nightly
      version:
        description: "Version"
        required: true
      pkgrel:
        description: "Package release"
        default: "1"
      headless:
        description: "Headless"
        default: false

jobs:
  aur-publish:
    name: Publish ${{ github.event.inputs.channel }} ${{ github.event.inputs.version }}-${{ github.event.inputs.pkgrel }} to AUR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate PKGBUILD
        id: generate-pkgbuild
        run: |
          set -eox pipefail

          # pkgname from the channel
          case "${{ github.event.inputs.channel }}+${{ github.event.inputs.headless }}" in
            stable+false)
              export aur_pkgname="fig"
              ;;
            stable+true)
              export aur_pkgname="fig-headless-bin"
              ;;
            beta+false)
              export aur_pkgname="fig-beta"
              ;;
            beta+true)
              exit 1
              ;;
            nightly+false)
              export aur_pkgname="fig-nightly-bin"
              ;;
            nightly+true)
              exit 1
              ;;
          esac

          echo "pkgname=${aur_pkgname}" >> $GITHUB_OUTPUT

          export aur_pkgver=$(echo ${{ github.event.inputs.version }} | sed 's/-/_/g')
          export aur_channel=${{ github.event.inputs.channel }}
          export aur_pkgrel=${{ github.event.inputs.pkgrel }}

          if [ "${aur_pkgname}" == "fig" ]; then
            export aur_provides=""
          else
            export aur_provides=$(printf "\nprovides=('fig')\nconflicts=('fig')")
          fi

          if [ "${{ github.event.inputs.headless }}" == "true" ]; then
            export template_file="PKGBUILD.headless.template"
            export download_url="https://repo.fig.io/generic/${{ github.event.inputs.channel }}/asset/${{ github.event.inputs.version }}/x86_64/fig_headless.tar.xz"
          else
            export template_file="PKGBUILD.template"
            export download_url="https://repo.fig.io/generic/${{ github.event.inputs.channel }}/asset/${{ github.event.inputs.version }}/x86_64/fig.tar.xz"
          fi

          curl -sL -o fig.tar.xz $download_url
          export aur_sha256sum=$(sha256sum fig.tar.xz | cut -d ' ' -f 1)

          envsubst '${aur_pkgname} ${aur_pkgver} ${aur_channel} ${aur_pkgrel} ${aur_provides} ${aur_sha256sum}' < "bundle/archlinux/${template_file}" > PKGBUILD

          cat PKGBUILD

      - name: Publish flyctl-bin to the AUR
        uses: superfly/aur-releaser@ba29a0a809d7221713a104f9c9a23c34ee5b0742
        with:
          pkgname: ${{ steps.generate-pkgbuild.outputs.pkgname }}
          pkgbuild: PKGBUILD
          commit_username: Grant G
          commit_email: grant@fig.io
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: ${{ github.event.inputs.version }}-${{ github.event.inputs.pkgrel }}
          force_push: "true"
