name: Update TS API Bindings Docs & Website

on:
  workflow_dispatch:
  push:
    paths: typescript-api-bindings/src/*.ts

jobs:
  update-docs:
    if: github.ref == 'refs/heads/master'
    runs-on: "ubuntu-latest"
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.UPDATE_SITE_TOKEN }}
        repository: withfig/public-site-nextjs
        event-type: fig-api-docs
