#!/bin/bash
set -e

# Ensure we have changes to merge
if [ -z "$(git status --porcelain -- . ':!pr-contents.txt')" ]; then
    echo "No changes to commit"
    exit 0
fi

git config user.name "docs-generator[bot]"
git config user.email "docs-generator[bot]@amazon.com"

# Push (branch should have already been created in update-docs.sh)
git add docs
git commit -m "Update docs based on PR #$PR_NUMBER

Auto-generated by Q"

git push -u origin "$BRANCH_NAME"

# Create PR
gh pr create \
  --title "Update docs based on PR #$PR_NUMBER" \
  --body "Auto-generated documentation updates based on changes in PR #$PR_NUMBER" \
  --base main \
  --head "$BRANCH_NAME"
