#!/bin/bash
set -e

PR_NUMBER=$1
BRANCH_NAME="docs-update-for-pr-$PR_NUMBER"

# Ensure we have changes to merge
if [ -z "$(git status --porcelain)" ]; then
    echo "No changes to commit"
    exit 0
fi

git config user.name "docs-generator[bot]"
git config user.email "docs-generator[bot]@amazon.com"

# Create branch, pull if needed (for updating existing docs PRs), and push
git checkout -B "$BRANCH_NAME"
if git ls-remote --exit-code --heads origin $BRANCH_NAME; then
    git pull origin $BRANCH_NAME
fi
git add docs
git commit -m "Update docs based on PR #$PR_NUMBER

Auto-generated by Q"

git push origin "$BRANCH_NAME"

# Create PR
gh pr create \
  --title "Update docs based on PR #$PR_NUMBER" \
  --body "Auto-generated documentation updates based on changes in PR #$PR_NUMBER" \
  --base main \
  --head "$BRANCH_NAME"
